src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Card_CVN__c</fullName>
        <label>Card CVN</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Month_Expiry__c</fullName>
        <label>Card Month Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Year_Expiry__c</fullName>
        <label>Card Year Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_CVN__c</fullName>
        <label>Card CVN</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Month_Expiry__c</fullName>
        <label>Card Month Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <displayFormat>CN{0000000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Amount_Credited__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Amount Credited</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount Paid</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Eway payment records</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Eway2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eway Failure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Chargebacks.cls
public with sharing class Chargebacks {
	public List<Invoice__c> invoices = new List<Invoice__c>();
	public Account acc {get;set;}
	public boolean PageRefresh {get;set;}
	public String invoiceNumber {get;set;}
	public Decimal invoiceTotal {get;set;}
	public Decimal invoiceAmountDue {get;set;}
	public Decimal invoiceAmountPaid {get;set;}
	public Date invoiceDueDate {get;set;}
	public Date invoiceIssuedDate {get;set;}
	public Decimal amountPaid {get; set;}
	public String PaymentType {get;set;}
	public String PaymentReference {get;set;}
	public Decimal partialRefundAmount {get;set;}
	public Decimal paymentAmount {get;set;}
	public String invoiceId {get;set;}
	public Decimal  totalRefund {get;set;}
	public Integer  invoicesSelected {get;set;}
	public String message {get;set;}
	public Payment__c inputPayment = new Payment__c();
	public Payment__c inputPaymentPartial = new Payment__c();
	
	public Payment__c getinputPayment() {
		return this.inputPayment;
	}
	public void setinputPayment(Payment__c value){
		this.inputPayment = value;
	}
	public Payment__c getinputPaymentPartial() {
		return this.inputPaymentPartial;
	}
	public void setinputPaymentPartial(Payment__c value){
		this.inputPaymentPartial = value;
	}
	
	public List<Invoice__c> getinvoices() {
		return this.invoices;
	}
	public void setinvoices(list<Invoice__c> value) {
		this.invoices = value;
	}
	
	public List<SelectOption> getInvoiceNumbers() {
    	List<SelectOption> options = new List<SelectOption>();
    	if(this.invoices != null){
	        for(Invoice__c thisInvoice : this.invoices){
	        	options.add(new SelectOption(thisInvoice.Invoice_Number__c,thisInvoice.Invoice_Number__c));	
	        }
    	}
    	return options;
	}
	
	public Chargebacks(ApexPages.StandardController controller){
		this.acc = (Account)controller.getRecord();
		this.PageRefresh = false;
		this.message = '';
	}
	
	public PageReference updateInvoices(){
		//this.invoices = this.invoices;
		update this.invoices;
		this.totalRefund = 0;
		this.invoicesSelected = 0;
		for(Invoice__c invoice : this.invoices){
			if(invoice.Checked__c){
				this.totalRefund += invoice.Amount_Paid__c;
				this.invoicesSelected += 1;
			}
			
		}
		return null;
	}
	public PageReference PageLoad(){
			
		this.invoices = [
			SELECT 
				Id, 
				Name,
				Amount_Credited__c, 
				Account__r.Payment_Option__c,
				Account__r.Name_On_Card__c,
				Account__r.Card_Number__c, 
				Account__r.Card_CVN__c,
				Account__r.Card_Month_Expiry__c,
				Account__r.Card_Year_Expiry__c, 
				Account_Product__c, 
				Account_Product__r.Name,
				Account_Product__r.OwnerId,
				Account_Product__r.Payment_Option__c,
				Account_Product__r.Name_On_Card__c,
				Account_Product__r.Card_Number__c,
				Account_Product__r.Card_Month_Expiry__c,
				Account_Product__r.Card_Year_Expiry__c,
				Account_Product__r.Card_CVN__c, 
				Account_Product__r.SLX_Product__r.company_name__c,
				Account__c, 
				Checked__c, 
				Invoice_Number__c, 
				Invoice_Total__c, 
				Amount_Paid__c, 
				Amount_Due__c, 
				Due_Date__c, 
				Issue_Date__c, 
				Amount_Refunded__c,
				Payment_Response__c,
				CurrencyIsoCode
			FROM 
				Invoice__c 
			WHERE 
				Account__c=:acc.Id 
			AND 
				(Status__c = 'PAID')
			order by
        		Issue_Date__c
		];
		for(Invoice__c thisInvoice : this.invoices){
			thisInvoice.Checked__c = false;
			this.invoiceNumber = thisInvoice.Invoice_Number__c;
		}
		//try{
		updateInvoices();
		ChangeInvoiceNumber();
		//}
		//catch(Exception e){
			
		//}
		return null;
	
	}
	public pageReference SingleChargeback() {
		
		
		List<Invoice__c> SelectedInvoices = new List<Invoice__c>();
		for(Invoice__c invoice: this.invoices){
			if(invoice.Invoice_Number__c == this.invoiceNumber){
				SelectedInvoices.add(invoice);
			}
		}
		
		List<Payment__c> ChargebackPayments = new List<Payment__c>();
		List<Credit__c> RefundCredits = new List<Credit__c>();
		List<Invoice__c> updateInvoices = new List<Invoice__c>();
		for(Invoice__c invoice: SelectedInvoices){
			//process chargeback
			
			Payment__c ChargebackPayment = new Payment__c();
			
			Decimal ChargebackAmount = invoice.Amount_Paid__c;
			
			ChargebackPayment.Account__c = acc.Id;
			ChargebackPayment.Payment_Type__c = 'Chargeback';
			ChargebackPayment.Payment_Amount__c = -partialRefundAmount;
			ChargebackPayment.Invoice__c = invoice.Id;
			ChargebackPayment.Invoice_Number__c = invoice.Invoice_Number__c;
			ChargebackPayment.Notes__c = inputPayment.Notes__c;
			ChargebackPayment.Payment_Date__c = Date.today();
			ChargebackPayment.Payment_Option__c = invoice.Account_Product__r.Payment_Option__c;
			ChargebackPayment.CurrencyIsoCode = invoice.CurrencyIsoCode;
			ChargebackPayment.Account_Product__c = invoice.Account_Product__c;
			ChargebackPayment.Payment_Owner__c = invoice.Account_Product__r.OwnerId;
			ChargebackPayments.add(ChargebackPayment);
			
			if(invoice.Amount_Refunded__c == null) invoice.Amount_Refunded__c = 0;
			invoice.Amount_Refunded__c = invoice.Amount_Refunded__c + partialRefundAmount;
			system.debug(invoice.Invoice_Total__c);
			system.debug(invoice.Amount_Refunded__c);
			if(invoice.Invoice_Total__c == invoice.Amount_Refunded__c) invoice.Status__c = 'CHARGEBACK';
			invoice.Amount_Paid__c = invoice.Amount_Paid__c - partialRefundAmount;
			updateInvoices.add(invoice);
		}
		insert ChargebackPayments;
		update updateInvoices;
		
		this.invoices = [
			SELECT 
				Id, 
				Name,
				Amount_Credited__c, 
				Account__r.Payment_Option__c,
				Account__r.Name_On_Card__c,
				Account__r.Card_Number__c, 
				Account__r.Card_CVN__c,
				Account__r.Card_Month_Expiry__c,
				Account__r.Card_Year_Expiry__c, 
				Account_Product__c, 
				Account_Product__r.Name,
				Account_Product__r.Payment_Option__c,
				Account_Product__r.Name_On_Card__c,
				Account_Product__r.Card_Number__c,
				Account_Product__r.Card_Month_Expiry__c,
				Account_Product__r.Card_Year_Expiry__c,
				Account_Product__r.Card_CVN__c, 
				Account__c, 
				Checked__c, 
				Invoice_Number__c, 
				Invoice_Total__c, 
				Amount_Paid__c, 
				Amount_Due__c, 
				Due_Date__c, 
				Issue_Date__c, 
				Amount_Refunded__c,
				CurrencyIsoCode
			FROM 
				Invoice__c 
			WHERE 
				Account__c=:acc.Id 
			AND 
				(Status__c = 'PAID' OR Status__c = 'PARTIALLY PAID' OR Status__c = 'PARTIALLY REFUNDED')
			order by
        		Issue_Date__c
		];
		this.totalRefund = 0;
		this.invoicesSelected = 0;
		this.inputPayment = new Payment__c();
		this.inputPaymentPartial = new Payment__c();
		
		
		PageReference MakeARefundPage = new PageReference('/apex/Chargebacks');
        MakeARefundPage.getParameters().put('id',this.acc.id);
        MakeARefundPage.setRedirect(true);
        return MakeARefundPage;
	}
	
	public void ChangeInvoiceNumber() {
		for(Invoice__c thisInvoice : this.invoices){
			if (thisInvoice.Invoice_Number__c == this.invoiceNumber) {
				this.invoiceNumber 		= thisInvoice.Invoice_Number__c;
		  		this.invoiceTotal 		= thisInvoice.Amount_Due__c;
		  		this.paymentAmount 		= thisInvoice.Amount_Due__c;
		  		this.PaymentReference 	= thisInvoice.Invoice_Number__c;
		  		this.PaymentType 		= thisInvoice.Account_Product__r.Payment_Option__c;
		  		this.amountPaid         = thisInvoice.Amount_Paid__c;
		  		this.InvoiceId			= thisInvoice.Id;
		  		if(thisInvoice.Amount_Refunded__c == null){thisInvoice.Amount_Refunded__c = 0;}
		  		this.partialRefundAmount = thisInvoice.Invoice_Total__c - thisInvoice.Amount_Refunded__c;
		  		
		  		this.invoiceAmountDue 	= thisInvoice.Amount_Due__c;
				this.invoiceAmountPaid 	= thisInvoice.Amount_Paid__c;
				this.invoiceDueDate		= thisInvoice.Due_Date__c;
				this.invoiceIssuedDate 	= thisInvoice.Issue_Date__c;
		  	}
		}		
	}
	public PageReference returnToAccount() {
    	PageReference AccountPage = new ApexPages.StandardController(this.acc).view();
        AccountPage.setRedirect(true);
        return AccountPage;
    }
}