src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>IF(OR(CONTAINS(Name,&quot;Adwords&quot;),(CONTAINS(Name, &quot;AdWords&quot;))), &apos;AdWords Management&apos;,
IF(CONTAINS(Name,&quot;SEO&quot;),&apos;SEO&apos;,
IF(CONTAINS(Name,&quot;Facebook&quot;), &apos;Social Marketing&apos;, 
IF(CONTAINS(Name,&quot;Social&quot;), &apos;Social Marketing&apos;,
IF(CONTAINS(Name,&quot;Converto&quot;), &apos;ConvertoPages&apos;, &apos;&apos;) ))))</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Resolution__c</fullName>
        <label>Account Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved to SEO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Account_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>Other Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosting Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reassign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday Discount</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <description>Please provide as much info as possible</description>
        <label>Case Reason</label>
        <picklist>
            <picklistValues>
                <fullName>BTS:Act of God</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Issues re SLX or Google Fees/Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Signup not compl by Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Technical/Legal/Industry std issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>----------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Sold to other products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Client referred a client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Sold to pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Relationship Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Alter billing method</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: EOM discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Holiday Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-----------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Bad reassign from last CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Didn&apos;t see account was down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Forced Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Insufficient contact with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Pause Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Lack of ROI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Resume off pause - now cancelling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: CM error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM          - Tech issue (Scripts not running)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM - Poor Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Google billing down 2+ weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - 3+ SLX invoices unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Agreed work not completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Insufficient Contact With Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Save Strat Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>---------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client:Bad site, said no to landing page</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>Account_Product__r.Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resolution Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CasesProcessor.cls
public class CasesProcessor {
    private String RESOLUTION_NOTE_MSG = 'Because of no active Manager, Ben take over the case';

    /*
    public void calEscalatedNumberManualShare(List<Cases__c> myCases,Set<Id> updateCaseIds ){
        
        //List<Cases__c> myCases = Trigger.new;
            
        integer loopOld = 0;
        Cases__c oldItem;        
        Boolean isChanged = false;    
        List<Cases__Share> mySharings = new List<Cases__Share>();  
        List<AccountShare> myAccountSharings= new List<AccountShare>(); 
        Decimal currentEscalateNo = ForCaseManage__c.getValues('EscalateNo').CaseNumber__c;    
        Integer numOfResolutionManager = TriggerUtilities.getNumberOfResolutionManager();
    
        //List<Cases__c> myOldCases = [SELECT id, Account__r.Id, Account_Product__r.id FROM Cases__c WHERE Id in :Trigger.newMap.keySet()];
        List<Cases__c> myOldCases = [SELECT id, Account__r.Id, Account_Product__r.id FROM Cases__c WHERE Id in :updateCaseIds];
    
        for(Cases__c item : myCases) {
            if((item.Status__c == 'Escalated') && (item.EscalateNo__c == null)){            
                isChanged = true;            
                item.EscalateNo__c = math.mod(Integer.valueOf(currentEscalateNo++),numOfResolutionManager) + 1;            
                User resolutionMan = TriggerUtilities.getAvailableResultionManager(Integer.valueOf(item.EscalateNo__c));           
                item.Resolution_Manager__c = resolutionMan.id;
                
                Cases__Share mySharing = new Cases__Share();
                mySharing.ParentId = item.Id;
                mySharing.UserOrGroupId = resolutionMan.id; 
                mySharing.AccessLevel = 'Edit';
                mySharing.RowCause = Schema.Cases__Share.RowCause.Manual;
                mySharings.add(mySharing);
                
                oldItem = myOldCases.get(loopOld);
                AccountShare myAccountSharing = new AccountShare();
                myAccountSharing.AccountId = oldItem.Account__r.Id;
                myAccountSharing.UserOrGroupId  = resolutionMan.id; 
                myAccountSharing.AccountAccessLevel = 'Read';
                myAccountSharing.ContactAccessLevel = 'Read';
                myAccountSharing.CaseAccessLevel = 'Read';
                myAccountSharing.OpportunityAccessLevel= 'Read';
                myAccountSharing.RowCause = Schema.AccountShare.RowCause.Manual;
                myAccountSharings.add(myAccountSharing);            
    
                //System.debug('UpdateCaseToEscalatedStatus :: EscalateNo__c =' + item.EscalateNo__c + ' numOfResolutionManager=' + numOfResolutionManager);
            }           
        }
        
        
        if(isChanged){
            try{
                // update custom setting to get ready for next case counter
                List<ForCaseManage__c> currentNumber = [SELECT id, Name, CaseNumber__c FROM ForCaseManage__c];
                currentNumber[0].CaseNumber__c = currentEscalateNo;
                update currentNumber;
                
                // update case object sharing
                List<Database.SaveResult> results = Database.insert(mySharings,false);
                
                //update account object sharing        
                List<Database.SaveResult> accountResults = Database.insert(myAccountSharings);
                
                for(Database.SaveResult item:results){
                      if(!item.isSuccess()){
                         // Get first save result error.
                         Database.Error err = item.getErrors()[0];
                         System.debug('CasesProcessor Error' + err.getMessage());
                      }
                }
                
                for(Database.SaveResult item:results){
                      if(!item.isSuccess()){
                         // Get first save result error.
                         Database.Error err = item.getErrors()[0];
                         System.debug('CasesProcessor Error' + err.getMessage());
                      }
                }
                
            }catch(DMLException ex){
                System.debug('CasesProcessor:: DMLException occured' + ex.getMessage());
            }        
        }
    }
    */
        
    public void assignEscalatedCase(List<Cases__c> myCases,Set<Id> updateCaseIds ){    
        integer loopOld = 0;
        Cases__c oldItem;        
        Boolean isChanged = false;    
        List<Cases__Share> mySharings = new List<Cases__Share>();  
        List<AccountShare> myAccountSharings= new List<AccountShare>(); 

        
        List<Cases__c> myOldCases = [SELECT id, Account__r.Id, Account_Product__r.id, OwnerId,Account_Resolution__c , Case_Reason__c FROM Cases__c WHERE Id in :updateCaseIds];

        // get new owner 
        List<id> newOwnerIDs = new List<id>();
        for(Cases__c item: myCases){
            newOwnerIDs.add(item.OwnerId);
        }

        // get cases owner manager
        Map<Id,User> newOwners = new Map<Id, User>([SELECT id, ManagerId FROM User WHERE isActive = true AND Id in :newOwnerIDs]);
       
        //get default resolution manager 
        User defaultManager = [SELECT id FROM USER WHERE Name = 'Ben Bradshaw' AND IsActive = true];

        //Map<id, id> newOwnerMans = new Map<id,id>();
        //for(User item: newOwners){
        //    newOwnerMans.put(item.id, item.ManagerId);
        //}

        for(Cases__c item : myCases) {
            if((item.Status__c == 'Escalated') &&  ((item.Product_Type__c == 'Social Marketing') || (item.Product_Type__c == 'AdWords Management')) 
                && (item.CaseType__c == 'Cancellation') &&  ( (item.Account_Resolution__c!= null && item.Account_Resolution__c.equals('Save')) || (item.Case_Reason__c!=null && item.Case_Reason__c.containsIgnoreCase('BTS'))) ){ 
                
                isChanged = true;                
                // update Resolution Manager
                item.Resolution_Manager__c = newOwners.get(item.OwnerId).ManagerId;
                if (item.Resolution_Manager__c  == null){
                    item.Resolution_Manager__c = defaultManager.Id;
                }                
                System.debug('item.Resolution_Manager__c = ' + item.Resolution_Manager__c);

                //update case access                
                Cases__Share mySharing = new Cases__Share();
                mySharing.ParentId = item.Id;
                mySharing.UserOrGroupId = item.Resolution_Manager__c; 
                mySharing.AccessLevel = 'Edit';
                mySharing.RowCause = Schema.Cases__Share.RowCause.Manual;
                mySharings.add(mySharing);
                
                //update account access
                oldItem = myOldCases.get(loopOld++);
                AccountShare myAccountSharing = new AccountShare();
                myAccountSharing.AccountId = oldItem.Account__r.Id;
                myAccountSharing.UserOrGroupId  = item.Resolution_Manager__c; 
                myAccountSharing.AccountAccessLevel = 'Read';
                myAccountSharing.ContactAccessLevel = 'Read';
                myAccountSharing.CaseAccessLevel = 'Read';
                myAccountSharing.OpportunityAccessLevel= 'Read';
                myAccountSharing.RowCause = Schema.AccountShare.RowCause.Manual;
                myAccountSharings.add(myAccountSharing);           
                

            }else if((item.Status__c == 'Escalated') && (item.Resolution_Manager__c == null) && ((item.Product_Type__c == 'Social Marketing') || (item.Product_Type__c == 'AdWords Management')) 
                && (item.CaseType__c == 'Cancellation')){            
                isChanged = true;            
                User resolutionMan = TriggerUtilities.getAvailableResolutionManagerByCap();

                // update Resolution Manager
                if( resolutionMan == null){                    
                    resolutionMan= defaultManager;                 
                }                
                item.Resolution_Manager__c = resolutionMan.id;
                System.debug('item.Resolution_Manager__c = ' + item.Resolution_Manager__c);

                Cases__Share mySharing = new Cases__Share();
                mySharing.ParentId = item.Id;
                mySharing.UserOrGroupId = resolutionMan.id; 
                mySharing.AccessLevel = 'Edit';
                mySharing.RowCause = Schema.Cases__Share.RowCause.Manual;
                mySharings.add(mySharing);
                
                oldItem = myOldCases.get(loopOld++);
                AccountShare myAccountSharing = new AccountShare();
                myAccountSharing.AccountId = oldItem.Account__r.Id;
                myAccountSharing.UserOrGroupId  = resolutionMan.id; 
                myAccountSharing.AccountAccessLevel = 'Read';
                myAccountSharing.ContactAccessLevel = 'Read';
                myAccountSharing.CaseAccessLevel = 'Read';
                myAccountSharing.OpportunityAccessLevel= 'Read';
                myAccountSharing.RowCause = Schema.AccountShare.RowCause.Manual;
                myAccountSharings.add(myAccountSharing);           
                
                //System.debug('UpdateCaseToEscalatedStatus :: EscalateNo__c =' + item.EscalateNo__c + ' numOfResolutionManager=' + numOfResolutionManager);
            }           
        }
        
        
        if(isChanged){
            try{
                // update case object sharing
                List<Database.SaveResult> results = Database.insert(mySharings,false);
                
                //update account object sharing        
                List<Database.SaveResult> accountResults = Database.insert(myAccountSharings);
                
                for(Database.SaveResult item:results){
                    if(!item.isSuccess()){
                        // Get first save result error.
                        Database.Error err = item.getErrors()[0];
                        System.debug('UpdateCaseToEscalatedStatus Error' + err.getMessage());
                    }
                }
                
                for(Database.SaveResult item:accountResults){
                    if(!item.isSuccess()){
                        // Get first save result error.
                        Database.Error err = item.getErrors()[0];
                        System.debug('UpdateCaseToEscalatedStatus Error' + err.getMessage());
                    }
                }
                
            }catch(DMLException ex){
                System.debug('UpdateCaseToEscalatedStatus:: DMLException occured' + ex.getMessage());
            }      
        }    
    }    
}