src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Days__c</fullName>
        <label>Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Days__c</fullName>
        <label>Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Product__c</fullName>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Client_Histories</relationshipLabel>
        <relationshipName>Client_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lasting_Days__c</fullName>
        <formula>IF(ISNULL(End_Date__c), today() -Start_Date__c+1, End_Date__c - Start_Date__c+1)</formula>
        <label>Lasting Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client_History</label>
    <nameField>
        <label>ClientHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client_Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProductActiveDaysBatch.cls
global class ProductActiveDaysBatch implements Database.batchable<Account>,Database.AllowsCallouts, Database.Stateful {
	
	global Iterable<Account> start(Database.batchableContext info) {
		System.debug('Start getting Account!');
		return new ProductActiveDaysIterator();
	}
	
	
	global void execute(Database.batchableContext info, List<Account> scope) {
		System.debug('Scope: ' + scope);
		for(Account account : scope){
			
			Decimal account_active_days = 0;
			
			Account_Product__c[] aps = [select
											Id,
											Active_Days__c
									  from
									  		Account_Product__c
									  where
									  		(Name like '%Adwords%' 
	                                        or Name like '%Facebook%' 
	                                        or Name like '%Yahoo%' 
	                                        or Name like '%Admob%'
	                                        or Name like '%Converto%')
									  and 
									   		(Recurring_Period__c != null and Recurring_Period__c!='N/A')
									  and 
									  		Product_Status__c != 'Paused'
									  and 
									  		Account__c =: account.Id];
			if(aps.size() > 0 ){
				for(Account_Product__c ap : aps){
					Decimal product_active_days = 0;
					
					Client_History__c[] chs = [select 
													Lasting_Days__c 
											   from 
											 		Client_History__c 
											   where 
											 		Type__c = 'Active'
											   and 
											 		Account_Product__c =: ap.Id];
					if(chs.size() > 0 ){
						for(Client_History__c ch : chs){
							product_active_days += ch.Lasting_Days__c;
						}
					}
					ap.Active_Days__c = product_active_days;
					try{
						update ap;
					}catch(Exception e){
						system.debug(e.getMessage());
					}
					//if(!ap.Name.contains('ConvertoPages')){
						account_active_days += product_active_days;
				//	}
				}
			}
			account.Active_Days__c = account_active_days;
			//account.Phone          = account.Contacts[0].Phone;
			update account;
		}
		
	}
	
	global void finish(Database.batchableContext info){
		
	}

}