src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the company which manages this account</description>
        <inlineHelpText>the company which manages this account</inlineHelpText>
        <label>BJB Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_CVN__c</fullName>
        <label>Card CVN</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Month_Expiry__c</fullName>
        <label>Card Month Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Number_Masked__c</fullName>
        <label>Card Number Masked</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year_Expiry__c</fullName>
        <label>Card Year Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkout_Site__c</fullName>
        <label>Checkout Site</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Gateway__c</fullName>
        <globalPicklist>Payment_Gateways</globalPicklist>
        <label>Payment Gateway</label>
        <type>Picklist</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemVars__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Miscellaneous system variables</description>
    <fields>
        <fullName>salt__c</fullName>
        <label>salt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>System Vars</label>
</CustomObject>

src/classes/ClientPanelAccountBillingTest.cls
@isTest
private class ClientPanelAccountBillingTest {
	
	@isTest
    static void testSubmit() {
        string sitename = 'checkout_SLX';

        User siteUserSLX = [SELECT Id, Name FROM User WHERE Name = 'Checkout SLX Site Guest User'];

        String salt = 'abcdefg';

        // Load payment gateway config
        // Eway2
        insert new SystemVars__c(
            Name                = 'main',
            salt__c      		= salt
        );

        // Setup companies
        Company__c company = new Company__c(
            Name = 'SponsoredLinX',
            Business_Name__c = 'SponsoredLinX',
            Checkout_Site__c = 'checkout_SLX',
            Payment_Gateway__c = 'Eway2',
            CurrencyIsoCode  = 'AUD'
        );
        insert company;

        // Setup existing account
        Account existingAccount = new Account(
            Name                    = 'Steve Existingclient',
            username__c             = 'steve.existingclient@sponsoredlinx.com',
            bjb_company__c          = company.Id,
            name_on_card__c         = 'Steve Clientman',
            card_number_masked__c   = '5454111122221111',
            card_month_expiry__c    = '9',
            card_year_expiry__c     = '2028',
            card_cvn__c             = '789'
        );
        insert existingAccount;

        // Share account with the checkout user. This is to emulate the sharing rule, which salesforce doesn't
        // apply in test cases. See https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_bulk_sharing_understanding.htm
        insert new AccountShare(
            AccountId = existingAccount.Id,
            UserOrGroupId = siteUserSLX.Id,
            AccountAccessLevel = 'Edit',
            OpportunityAccessLevel = 'Edit'
        );

        // run tests
        test.starttest();

        system.runAs(siteUserSLX) {
            String sigData = existingAccount.Id + existingAccount.username__c + salt;
            String accountSig = EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueof(sigData)));

            // Test error case with no account id
        	ClientPanelAccountBilling controller1 = new ClientPanelAccountBilling();
        	controller1.index();

        	// Test normal case with account id
        	pagereference pageref = page.ClientPanelAccountBilling;
            pageref.getParameters().put('accountid', existingAccount.id ); // To test loading existing account
            pageref.getParameters().put('sig', accountSig);
            test.setCurrentPage(pageref);
        	ClientPanelAccountBilling controller2 = new ClientPanelAccountBilling();
        	controller2.index();

        	controller2.index();
        	controller2.getMonthOptions();
        	controller2.getCardYearOptions();
        	controller2.getSiteWrapperURL();
        	controller2.submitUpdateBilling();
		}

		test.stoptest();
	}
	
}