src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_ID__c</fullName>
        <label>Adwords ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>IF(OR(CONTAINS(Name,&quot;Adwords&quot;),(CONTAINS(Name, &quot;AdWords&quot;))), &apos;AdWords Management&apos;,
IF(CONTAINS(Name,&quot;SEO&quot;),&apos;SEO&apos;,
IF(CONTAINS(Name,&quot;Facebook&quot;), &apos;Social Marketing&apos;, 
IF(CONTAINS(Name,&quot;Social&quot;), &apos;Social Marketing&apos;,
IF(CONTAINS(Name,&quot;Converto&quot;), &apos;ConvertoPages&apos;, &apos;&apos;) ))))</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SLXOpportunity__c.object
<CustomObject>
    <description>Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_ID__c</fullName>
        <label>Adwords ID</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adwords_Keyword__c</fullName>
        <description>Top adwords keywords of this client</description>
        <label>Adwords Keyword</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adwords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+ Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Upgrade</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>BJB Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BJBOpportunityHelper.cls
public class BJBOpportunityHelper {

	list<SLXOpportunity__c> objects{get;set;}
	SLXOpportunity__c myOpp{get;set;}
	
	//constructor
	public void BJBOpportunityHelper(){

	}

	public String getValidAdwordID( SLXOpportunity__c opp){		
		
		//get required fields from opp
		//this.myOpp = [SELECT id,Account__c,Adwords_Keyword__c FROM SLXOpportunity__c WHERE id = :opp.Id];

		// get all active product with type is Adword Management and recursive is not null
		List<Account_Product__c> products = [ 	SELECT Id, Adwords_ID__c, Product_Status__c, Recurring_Period__c, Product_Type__c
												FROM Account_Product__c
												WHERE Product_Type__c = 'AdWords Management'  
														AND Product_Status__c = 'Active' 
														AND Account__c= :opp.Account__c];
		if((products!= null) && (products.size()>0)){
			for(Account_Product__c item:products){
				if ((item.Recurring_Period__c != null) && (item.Recurring_Period__c != 'N/A')  && (item.Adwords_ID__c != null)){
					return item.Adwords_ID__c;
				}
			}
		}

		return 'N/A';
	}

}