src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amex__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amex</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amex__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amex</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <displayFormat>P{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLX_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SLX Product</label>
        <referenceTo>SLX_Product__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <formula>TEXT(Account.Payment_Option__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Option</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Amex__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amex</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount_Credited__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Amount Credited</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount Due</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount Paid</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Refunded__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Refunded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Invoice Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Issue_Date__c</fullName>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Eway payment records</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Eway2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eway Failure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SLX_Product__c.object
<CustomObject>
    <fields>
        <fullName>company_name__c</fullName>
        <label>Company Name</label>
        <picklist>
            <picklistValues>
                <fullName>SponsoredLinx</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Get More Traffic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crank IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iiConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJB Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SponsoredLinX New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Get More Traffic New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>recurring_period__c</fullName>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BJB Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/printInvoice.cls
public with sharing class printInvoice {
	public Invoice__c invoice {set;get;}
	public List<tran> trans {set; get;}
	public boolean isNewZealand {set; get;}
	public String dateRange {set; get;}
	public String priceBreakDown {set; get;}
	public Company__c company {set;get;}
	
	public printInvoice(ApexPages.StandardController controller){
		Invoice__c inv = (Invoice__c)controller.getRecord();
		this.invoice   = [select 
								Id, 
								Account__c, 
								Reference__c, 
								Payment_Option__c, 
								Account_Product__r.Name, 
								Account_Product__r.Product_Number__c, 
								Account_Product__r.Description__c, 
								Account_Product__r.recurring_period__c, 
								Account_Product__r.SLX_Product__r.company_name__c,
								Account__r.Name, 
								Account__r.website, 
								Account__r.BillingStreet, 
								Account__r.BillingCity, 
								Account__r.BillingState, 
								Account__r.BillingPostalCode, 
								Account__r.BillingCountry, 
								Invoice_Number__c, 
								Issue_Date__c, 
								Amount_Due__c, 
								Amount_Refunded__c, 
								Amount_Credited__c,
								Due_Date__c,
								Amount_Paid__c,
								Invoice_Total__c, 
								Amex__c 
							from 
								Invoice__c 
							where 
								Id=:inv.Id
							];
							
		this.invoice.Account__r.Name = this.invoice.Account__r.Name.removeStart('GetMoreTraffic - ');					
							
		this.company = [select
                            Id,
                            Name,
                            Address__c,
                            Business_Name__c,
                            Email__c,
                            Logo_Code__c,
                            Phone__c,
                            ABN__c,
                            term_page__c,
                            Account_Name__c,
                            Account_Number__c,
                            BSB__c,
                            Display_Invoice_Direct_Debit__c,
                            Display_Invoice_Pay_By_Phone__c,
                            Display_Invoice_Direct_Bank_Deposit__c,
                            Display_Invoice_Client_Panel__c
                        FROM 
                        	Company__c
                        WHERE 
                        	Name =: this.invoice.Account_Product__r.SLX_Product__r.company_name__c
						];
							
		Payment__c[] payments = [select 
							Id,
							Payment_Date__c, 
							Payment_Type__c,
							Payment_Option__c, 
							Payment_Amount__c 
					from 
							Payment__c
					where 
							invoice__c =: invoice.Id
					Order By
							Payment_Date__c DESC
					];
		
		trans = new List<tran>();
		for(Payment__c p : payments) {
			String payDate = p.Payment_Date__c.format();
			Decimal payAmount = p.Payment_Amount__c;
			String payType;
			if(p.Payment_Type__c == 'Eway') {
				payType = 'Credit Card';
			} else if (p.Payment_Type__c == 'Payment' && p.Payment_Option__c == 'Eway') {
				payType = 'Credit Card';
			} else if (p.Payment_Type__c == 'Payment' && p.Payment_Option__c != 'Eway') {
				payType = p.Payment_Option__c;
			} else if (p.Payment_Type__c == 'Credit') {
				payType = 'Credit Note';
			} else {
				payType = p.Payment_Type__c;
			}
			tran t = new tran(payDate, payType, payAmount);
			trans.add(t);
		}
							
		if ((invoice.Account__r.website != null && invoice.Account__r.website.endsWithIgnoreCase('.nz') == true) || this.company.name.containsIgnoreCase('New Zealand')) {
			isNewZealand = true;
		} else {
			isNewZealand = false;
		}
		
		if(isNewZealand){
			priceBreakDown = 'There is no GST included in the invoice amount';
		}else{
			priceBreakDown = 'Tax breakdown: $' + (invoice.Invoice_Total__c*10/11).setScale(2, RoundingMode.HALF_UP) + ' Price + $'
							+ (invoice.Invoice_Total__c/11).setScale(2, RoundingMode.HALF_UP) + ' GST = $' 
							+ invoice.Invoice_Total__c + ' Total';
		}


		if (invoice.Account_Product__r.recurring_period__c == 'Weekly') {
			Date endDate = invoice.Issue_Date__c.addDays(-1);
			Date startDate = endDate.addDays(-6);
			dateRange = startDate.format() + ' - ' + endDate.format();
		} else if (invoice.Account_Product__r.recurring_period__c == 'Fortnightly') {
			Date startDate = invoice.Issue_Date__c;
			Date endDate = startDate.addDays(13);
			dateRange = startDate.format() + ' - ' + endDate.format();			
		} else if (invoice.Account_Product__r.recurring_period__c == 'Monthly') {
			Date startDate = invoice.Issue_Date__c;
			Date endDate = startDate.addMonths(1).addDays(-1);
			dateRange = startDate.format() + ' - ' + endDate.format();
		} else if (invoice.Account_Product__r.recurring_period__c == 'Quarterly') {
			Date startDate = invoice.Issue_Date__c;
			Date endDate = startDate.addMonths(3).addDays(-1);
			dateRange = startDate.format() + ' - ' + endDate.format();
		} else if (invoice.Account_Product__r.recurring_period__c == 'Half Yearly') {
			Date startDate = invoice.Issue_Date__c;
			Date endDate = startDate.addMonths(6).addDays(-1);
			dateRange = startDate.format() + ' - ' + endDate.format();
		} else if (invoice.Account_Product__r.recurring_period__c == 'Yearly') {
			Date startDate = invoice.Issue_Date__c;
			Date endDate = startDate.addYears(1).addDays(-1);
			dateRange = startDate.format() + ' - ' + endDate.format();
		} else if (invoice.Account_Product__r.recurring_period__c == '2 Yearly') {
			Date startDate = invoice.Issue_Date__c;
			Date endDate = startDate.addYears(2).addDays(-1);
			dateRange = startDate.format() + ' - ' + endDate.format();
		} else {
			dateRange = '';
		}
	}
	
	public class tran {
		public String tranDate {get; set;}
    	public String tranType {get; set;}
    	public Decimal tranAmount {get; set;}
    	
    	public tran(String d, String t, Decimal a) {
            this.tranDate = d;
            this.tranType = t;
            this.tranAmount = a;
        }
	}
		
	public static testMethod void testprintInvoice(){
		Test.startTest();
		Account acc = new Account(name='test',company__c='test',username__c='test',password__c='test');
		insert acc;
		Contact con = new Contact(FirstName='test',LastName='test',Title='Billing',AccountId=acc.id);
		con.MailingStreet='sdfsadfsa\r\ndfsafa\r\nsfsdfsdfs\r\ndfsdfs\r\ndfsdf';
		con.MailingCity='Brisbane';
		con.MailingState='queensland';
		con.MailingPostalCode='4444';
		con.MailingCountry='Australia';
		insert con;
		
		Company__c com = new Company__c();
		com.name = 'test company';
		insert com;
		
		SLX_Product__c product = new SLX_Product__c();
		product.company_name__c = com.name;
		product.product_price__c = 10;
		insert product;
				
		Account_Product__c ap1 = new Account_Product__c(name = 'test', product_price__c=50, Account__c = acc.Id,recurring_period__c='Weekly', SLX_Product__c=product.id);
		insert ap1;
		
		Invoice__c invoice1 = new Invoice__c( Account__c = acc.Id, Issue_Date__c = Date.today(), Invoice_Total__c = 10, account_product__c=ap1.Id);
		insert invoice1;
		
		Account_Product__c ap2 = new Account_Product__c(name = 'test', Account__c = acc.Id, product_price__c=50, recurring_period__c='Fortnightly', SLX_Product__c=product.id);
		insert ap2;
		
		Invoice__c invoice2 = new Invoice__c( Account__c = acc.Id, Issue_Date__c = Date.today(), Invoice_Total__c = 10, account_product__c=ap2.Id);
		insert invoice2;
		
		Account_Product__c ap3 = new Account_Product__c(name = 'test', Account__c = acc.Id, product_price__c=50, recurring_period__c='Monthly', SLX_Product__c=product.id);
		insert ap3;
		
		Invoice__c invoice3 = new Invoice__c( Account__c = acc.Id, Issue_Date__c = Date.today(), Invoice_Total__c = 10, account_product__c=ap3.Id);
		insert invoice3;
		
		Account_Product__c ap4 = new Account_Product__c(name = 'test', Account__c = acc.Id, product_price__c=50, recurring_period__c='Quarterly', SLX_Product__c=product.id);
		insert ap4;
		
		Invoice__c invoice4 = new Invoice__c( Account__c = acc.Id, Issue_Date__c = Date.today(), Invoice_Total__c = 10, account_product__c=ap4.Id);
		insert invoice4;
		
		Account_Product__c ap5 = new Account_Product__c(name = 'test', Account__c = acc.Id, product_price__c=50, recurring_period__c='Yearly', SLX_Product__c=product.id);
		insert ap5;
		
		Invoice__c invoice5 = new Invoice__c( Account__c = acc.Id, Issue_Date__c = Date.today(), Invoice_Total__c = 10, account_product__c=ap5.Id);
		insert invoice5;
		
		Account_Product__c ap6 = new Account_Product__c(name = 'test', Account__c = acc.Id, product_price__c=50, recurring_period__c='2 Yearly', SLX_Product__c=product.id);
		insert ap6;
		
		Invoice__c invoice6 = new Invoice__c( Account__c = acc.Id, Issue_Date__c = Date.today(), Invoice_Total__c = 10, account_product__c=ap6.Id);
		insert invoice6;
		
		Payment__c payment1 = new Payment__c(Account__c=acc.Id, payment_Amount__c=60, Payment_Date__c=date.today(), Invoice__c = invoice1.Id, payment_type__c='Eway');
		insert payment1;
		Payment__c payment2 = new Payment__c(Account__c=acc.Id, payment_Amount__c=60,Payment_Date__c=date.today(), Invoice__c = invoice2.Id, payment_type__c='Payment', payment_Option__c='Eway');
		insert payment2;
		Payment__c payment3 = new Payment__c(Account__c=acc.Id, payment_Amount__c=60,Payment_Date__c=date.today(), Invoice__c = invoice3.Id, payment_type__c='Payment');
		insert payment3;
		Payment__c payment4 = new Payment__c(Account__c=acc.Id, payment_Amount__c=60,Payment_Date__c=date.today(), Invoice__c = invoice4.Id, payment_type__c='Payment');
		insert payment4;
		Payment__c payment5 = new Payment__c(Account__c=acc.Id, payment_Amount__c=60,Payment_Date__c=date.today(), Invoice__c = invoice5.Id, payment_type__c='Payment');
		insert payment5;
		Payment__c payment6 = new Payment__c(Account__c=acc.Id, payment_Amount__c=60,Payment_Date__c=date.today(), Invoice__c = invoice6.Id, payment_type__c='Payment');
		insert payment6;
		ApexPages.standardController controller1 = new ApexPages.standardController(invoice1);
		printInvoice printInv1 =  new printInvoice(controller1);
		
		ApexPages.standardController controller2 = new ApexPages.standardController(invoice2);
		printInvoice printInv2 =  new printInvoice(controller2);
		
		ApexPages.standardController controller3 = new ApexPages.standardController(invoice3);
		printInvoice printInv3 =  new printInvoice(controller3);
		
		ApexPages.standardController controller4 = new ApexPages.standardController(invoice4);
		printInvoice printInv4 =  new printInvoice(controller4);
		
		ApexPages.standardController controller5 = new ApexPages.standardController(invoice5);
		printInvoice printInv5 =  new printInvoice(controller5);
		
		ApexPages.standardController controller6 = new ApexPages.standardController(invoice6);
		printInvoice printInv6 =  new printInvoice(controller6);
		
		Test.stopTest();
	}
	
	
	
	
	
}