src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Num_of_Escalated_Case__c</fullName>
        <description>Number of Escalated Case still waiting for processing under this account</description>
        <inlineHelpText>Number of Escalated Case still waiting for processing under this account</inlineHelpText>
        <label>Number of Escalated Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_ID__c</fullName>
        <label>Adwords ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>IF(OR(CONTAINS(Name,&quot;Adwords&quot;),(CONTAINS(Name, &quot;AdWords&quot;))), &apos;AdWords Management&apos;,
IF(CONTAINS(Name,&quot;SEO&quot;),&apos;SEO&apos;,
IF(CONTAINS(Name,&quot;Facebook&quot;), &apos;Social Marketing&apos;, 
IF(CONTAINS(Name,&quot;Social&quot;), &apos;Social Marketing&apos;,
IF(CONTAINS(Name,&quot;Converto&quot;), &apos;ConvertoPages&apos;, &apos;&apos;) ))))</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account)</relationshipLabel>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Leads</description>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncontactable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Lead - Old</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads - Old</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Product Type</description>
        <inlineHelpText>Product Type</inlineHelpText>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO &amp; Adwords</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO &amp; Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdWords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SLXOpportunity__c.object
<CustomObject>
    <description>Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_Daily_Budget__c</fullName>
        <label>Adwords Daily Budget</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adwords_ID__c</fullName>
        <label>Adwords ID</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Importance__c</fullName>
        <label>Importance</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adwords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+ Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Upgrade</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>SLX_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SLX Lead</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipName>SLX_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_to_Salesperson__c</fullName>
        <label>Send to Salesperson (no longer used)</label>
        <picklist>
            <picklistValues>
                <fullName>Gretel Phillips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daniel Andreotti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tate Wotton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simon Golding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meg Arreza</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joshua Beatty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Teamleader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abigail Harrison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ngawai Mason</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>BJB Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Adwords_ID__c</fullName>
        <label>Adwords ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>Password</label>
        <length>30</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BJBOpportunityHelperTest.cls
@isTest
private class BJBOpportunityHelperTest {

	@testSetup static void setup(){
			List<Account> testAccts = new List<Account>();
		    //create account
            Account itemAcc = new Account(Name = 'TestAccount1', username__c = 'TestAccount1', password__c = 'TestAccount1', CurrencyIsoCode = 'AUD',Num_of_Escalated_Case__c =10, phone='1300859600');
            testAccts.add(itemAcc);
            itemAcc = new Account(Name = 'TestAccount2', username__c = 'TestAccount2', password__c = 'TestAccount2', CurrencyIsoCode = 'USD',Num_of_Escalated_Case__c =10, phone='1300859600');
            testAccts.add(itemAcc);
            insert testAccts;

            // create account products
            List<Account_Product__c> testProducts = new List<Account_Product__c>();
            for (Integer i = 0; i < 2; i++) {
                Account_Product__c item = new Account_Product__c(Name = 'Adwords Management' + 1, Product_Price__c = 1000, CurrencyIsoCode = 'AUD', Account__c = testAccts.get(0).id, Recurring_Period__c = 'Weekly', Product_Status__c='Active', Adwords_ID__c= '123-456-7890');
                testProducts.add(item);
            }
            insert testProducts;

            List<Contact> contacts = new List<Contact>();
            for (Integer i = 0; i < testAccts.size(); i++) {
                Account item = testAccts.get(i);
                Contact con = new Contact(AccountId = item.id, LastName = 'test contact', Title='Billing');
                contacts.add(con);
            }
            insert contacts;

            //create user with Resolution Manager Profiles
            Profile p = [select Id, name from Profile where Name = 'Resolution Manager' limit 1];
            List<User> users = new List<User>();
            for (Integer i = 0; i < testAccts.size(); i++) {
                User newUser = new User(profileId = p.id,
                        username = 'myTestUser' + i + '@yahoo.com',
                        email = 'testUser1@ff.com',
                        emailencodingkey = 'UTF-8',
                        localesidkey = 'en_US',
                        languagelocalekey = 'en_US',
                        timezonesidkey = 'America/Los_Angeles',
                        alias = 'nuser',
                        lastname = 'testuser_lastname' + i,
                        IsActive = true
                );
                users.add(newUser);
            }
            insert users;

            // create a lead, because of leadStatusChangeOnOpp trigger on SLX opportunity object
            Lead__c myLead = new Lead__c(Name='My Test Lead', Lead_Status__c = 'New');
            insert myLead;


            // create main test object - SLX opp
            SLXOpportunity__c opp = new SLXOpportunity__c(Account__c = testAccts.get(0).id , Name = 'Test Opp 1 ',  Product_Type__c ='Adwords Management',
                                                        Send_to_Salesperson__c='Gretel Phillips', Website__c='abc.com.au',  Adwords_Daily_Budget__c=10, 
                                                        Importance__c='High', Contact_Name__c='abc', Contact_Email__c='abc@gmail.com', SLX_Lead__c = myLead.Id);

            insert opp;



	}

	@isTest static void test_getValidAdwordID() {
		// Implement test code
		//List<Account> accs =  [SELECT id FROM Account ];
        
		SLXOpportunity__c opp = [select Adwords_ID__c FROM SLXOpportunity__c LIMIT 1];
		System.assertEquals('123-456-7890', opp.Adwords_ID__c);
	}
	
}