src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_Email__c</fullName>
        <label>Adwords Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Adwords_ID__c</fullName>
        <label>Adwords ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Category</label>
        <referenceTo>Product_Category__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Package</label>
        <referenceTo>Product_Package__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Frequency__c</fullName>
        <description>The frequency of this product to be billed</description>
        <label>Recurring Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reseller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reseller</label>
        <referenceTo>Reseller__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLX_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SLX Product</label>
        <referenceTo>SLX_Product__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Category__c.object
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Package__c.object
<CustomObject>
    <label>Product Package</label>
    <nameField>
        <label>Product Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reseller__c.object
<CustomObject>
    <fields>
        <fullName>Template_Name__c</fullName>
        <label>Template Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reseller</label>
    <nameField>
        <label>Reseller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SLX_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Package__c</fullName>
        <label>Product Package</label>
        <picklist>
            <picklistValues>
                <fullName>No Package</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optimised Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate BRONZE Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate SILVER Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate GOLD Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate DIAMOND Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate PLATINUM Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>350MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>450MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>600MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Starter Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Business Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Article Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Article Writing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Brand Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Platinum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local &amp; National Campaign Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local Campaign Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local Campaign + Analytics Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO National Campaign Package</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>recurring_period__c</fullName>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BJB Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AdwordsWebService.cls
global class AdwordsWebService {
	public class InvalidParamsException extends Exception {}

	global class WebServiceResultAdwordsProduct {
		WebService Boolean status;
		WebService List<Account_Product__c> result;
		WebService String message;
	}


	WebService static WebServiceResultAdwordsProduct getActiveAdwordsProducts() {
		WebServiceResultAdwordsProduct return_result = new WebServiceResultAdwordsProduct();

		List<Account_Product__c> account_products =
			[
				SELECT
					Name,
					Description__c,
					Adwords_ID__c,
					Adwords_Email__c,
					Product_Status__c,
					Product_Package__c,
					Product_Category__c,
					SLX_Product__c,
					Recurring_Frequency__c,
					Recurring_Period__c,
					Reseller__r.Name,
					Reseller__r.Template_Name__c,
					Account__r.Name
				FROM Account_Product__c
				WHERE Product_Status__c = 'Active'
				AND Name LIKE '%Adwords%' AND (NOT Name LIKE '%Setup%')
				AND (Adwords_ID__c != '' AND Adwords_ID__c != NULL)
				AND CreatedDate < LAST_WEEK
			];

		if(account_products.size() > 0) {
			return_result.status = true;
			return_result.result = account_products;
			return_result.message = 'Successfully fetch active AdWords products';
			System.debug('Account Products: ' + account_products);
		}
		else {
			return_result.status = false;
			return_result.result = null;
			return_result.message = 'There is no active AdWords product';
		}

		return return_result;
	}

	static testMethod void getActiveAdwordsProductsTest() {
		AdwordsWebService.getActiveAdwordsProducts();
	}

}