src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Infusionsoft_id__c</fullName>
        <label>Infusionsoft_id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Psycho__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Do not send any email to this client once marked as Do Not Contact</description>
        <inlineHelpText>Do not send any email to this client once marked as Do Not Contact</inlineHelpText>
        <label>Do Not Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/infusionsoftIterable.cls
global class infusionsoftIterable implements Iterator<Account> {
	
	List<Account> accounts = new List<Account>();
	Integer i {get;set;}
	
	public infusionsoftIterable(){
		Date today = System.today();
		Date startOfWeek = today.toStartOfWeek();
		Integer dayOfWeek = today.day()-startOfWeek.day();
		
		this.i = 0;
		
		try{
			if(dayOfWeek == 6 ){
				this.accounts = [select Id, Name, Owner.Name, Payment_Option__c, Website, infusionsoft_Id__c, Active__c, Psycho__c FROM Account where Type != 'Employee'];
			}else{
				this.accounts = [select Id, Name, Website, Payment_Option__c, infusionsoft_Id__c, Active__c, Psycho__c FROM Account where Type != 'Employee'];
			}
			}catch(Exception e){
				System.debug(e.getMessage());
			}
	}
	
	global boolean hasNext() {
	    if(this.i >= this.accounts.size()) 
	        return false; 
	    else 
	        return true;  
    }
    
	global Account next() {
		return this.accounts[this.i++];  
	}
	
	public static testMethod void testinfusionsoftIterable() {
        Test.startTest();
        Account account = new Account();
		account.Name = 'Test Account';
		account.Company__c = 'SponsoredLinX';
		account.username__c = 'test@test.com';
		account.password__c = 'test';
		insert account;
        
        infusionsoftIterable infusionsoftIterable = new infusionsoftIterable();
        if(infusionsoftIterable.hasNext()){
        	Account account1 = infusionsoftIterable.next();
        }
        Test.stopTest();
    }
}