src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the company which manages this account</description>
        <inlineHelpText>the company which manages this account</inlineHelpText>
        <label>BJB Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_CVN__c</fullName>
        <label>Card CVN</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Month_Expiry__c</fullName>
        <label>Card Month Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Number_Masked__c</fullName>
        <label>Card Number Masked</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Year_Expiry__c</fullName>
        <label>Card Year Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountBilling.cls
public with sharing class AccountBilling {

    public Account acc {get;set;}
    public CardDetails cardDetails {get; set;} {cardDetails = new CardDetails();}

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public AccountBilling(ApexPages.StandardController controller) {
        if (!Test.isRunningTest()) controller.addFields(new String[]{'Id', 'Name', 'Card_Number__c', 'Card_Number_Masked__c', 'Name_On_Card__c', 'Card_Month_Expiry__c', 'Card_Year_Expiry__c', 'Card_CVN__c', 'Unique_Id__c', 'currencyIsoCode', 'BJB_Company__c'});
        this.acc = (Account)controller.getRecord();

        // Populate the card number field with the previous masked value from the account
        this.cardDetails.Card_Number = this.acc.Card_Number_Masked__c;
    }

    // Submit 'update'
    public PageReference submitUpdate() {
        // Error checking
        if (String.isBlank(this.cardDetails.Card_Number)){
            System.debug('Error: Please enter a card number');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please enter a card number'));
        }

        if (String.isBlank(this.acc.Name_On_Card__c)){
            System.debug('Error: Please enter the name on the credit card');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please enter the name on the credit card'));
        }

        if (String.isBlank(this.acc.Card_Month_Expiry__c)){
            System.debug('Error: Please enter the card month expiry');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please enter the card month expiry'));
        }

        if (String.isBlank(this.acc.Card_Year_Expiry__c)){
            System.debug('Error: Please enter the card year expiry');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please enter the card year expiry'));
        }

        // create card transaction payment
        if ( !ApexPages.hasMessages() ) {
            try{
                paymentGateway pay = new paymentGateway();
                pay.updateAccountToken(this.acc, this.cardDetails.Card_Number, this.cardDetails.Card_CVN);
                update this.acc;
            } catch (Exception e) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            }
        }

        if ( ApexPages.hasMessages() ) {
            // Display errors
            return null;
        } else {
            PageReference MyPage = new PageReference('/'+this.acc.id);
            MyPage.setRedirect(true);
            return MyPage;
        }

    }

    // Return to the account page
    public PageReference returnToAccount() {
        PageReference AccountPage = new ApexPages.StandardController(this.acc).view();
        AccountPage.setRedirect(true);
        return AccountPage;
    }
}