src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employee_Department__c</fullName>
        <label>Employee Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support &amp; Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SLXOpportunity__c.object
<CustomObject>
    <description>Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BJB Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityContacts.cls
public with sharing class OpportunityContacts {
	
	public List<Contact> contacts {get; set;}
	public SLXOpportunity__c opp {get;set;}
	
	public OpportunityContacts(ApexPages.StandardController controller){
		this.opp = (SLXOpportunity__c)controller.getRecord();
		try{
			this.opp = [select Id, Account__c from SLXOpportunity__c where Id =: this.opp.Id limit 1];
			this.contacts = [select Id, Name, Phone,Department, MobilePhone, Email, Title from Contact where Account.Id =: this.opp.Account__c];
		}catch(Exception e){
			System.debug(e.getMessage());
		}
	}
	
	
	public static testMethod void testoppContacts() {
		Account acc = new Account();
		acc.Employee_Department__c = 'Sales';
		acc.Type = 'Employee';
		acc.Active__c = true;
		acc.username__c = 'test123456';
		acc.password__c = '123';
		acc.Name        = 'test';
		insert acc;
		Contact con = new Contact(FirstName='test',LastName='test',Title='Billing',AccountId=acc.id);
		con.MailingStreet='sdfsadfsa\r\ndfsafa\r\nsfsdfsdfs\r\ndfsdfs\r\ndfsdf';
		con.MailingCity='Brisbane';
		con.MailingState='queensland';
		con.MailingPostalCode='4444';
		con.MailingCountry='Australia';
		con.AccountId = acc.Id;
		insert con;
		SLXOpportunity__c opp = new SLXOpportunity__c();
		ApexPages.standardController controller = new ApexPages.standardController(opp);
		OpportunityContacts a = new OpportunityContacts(controller);
	}
}