src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Card_Number_Masked__c</fullName>
        <label>Card Number Masked</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Amount_Credited__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Amount Credited</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount Due</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount Paid</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exclude_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Batch</label>
        <referenceTo>Invoice_Batch__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Invoice Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Issue_Date__c</fullName>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Batch</label>
        <referenceTo>Invoice_Batch__c</referenceTo>
        <relationshipLabel>Invoices (Payment Batch)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Message__c</fullName>
        <label>Payment Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Response__c</fullName>
        <label>Payment Response</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Message__c</fullName>
        <label>Process Message</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AUTHORISED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REFUNDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO CHARGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CREDITED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY CREDITED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY REFUNDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAD DEBT/WRITTEN OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGEBACK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Xero_Contact_Id__c</fullName>
        <label>Xero Contact Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Id__c</fullName>
        <label>Xero Invoice Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>Batch Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Batch_Processed__c</fullName>
        <label>Batch Processed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <label>Batch Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoices</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Batch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Batch Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Batch</label>
    <nameField>
        <label>Invoice Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Reminder_Exclude__c.object
<CustomObject>
    <description>List of invoice reminders that we don&apos;t want to send to client via email</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Reminder Exclude</relationshipLabel>
        <relationshipName>Invoice_Reminder_Exclude</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <externalId>true</externalId>
        <label>Invoice Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Invoice Reminder Exclude</label>
    <nameField>
        <label>Invoice Reminder Exclude Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Reminder Exclude</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceReminder.cls
global with sharing class InvoiceReminder {
  public static boolean isTest = false;
  public static String consumerkey  = 'CJSE8SW0UHFRWFRSJVNVF4YEUVATZY';
  public static String privatekey   = 'MIICXAIBAAKBgQCZjhkaqM5rb0O3d/50XuzagfDz51ZQZH52/QRH/uVOqA8OWcSv\n'
                + 'RB2LtaiVosnxlB6Bji69sx3pM8AEaNrCWjetjktgdF/611Aqy83IABFLT926KWxt\n'
                + 'nmE2EfdeC3PE/gTf1ASgQ+seD6LyxWpy62G75dtz56bxoERkN6LYLfF5IQIDAQAB\n'
                + 'AoGAUR0B39ZJ6/CDadgl/tzh6u73FDAgpSjgsQQojct0397gzSjYP+kQXmugWSL7\n'
                + '3/PpRXCQ+j4yz6w5g1rMLBwyClds5nn0Tsi2TZbxx/uGdcb8/ulYfEySw7CJspDk\n'
                + 'Bw7m37IHDJn/bLHHZdxKQMed4/8Z8HBzGbaRz8kMhU8f+x0CQQDMnVIChO9BVYb1\n'
                + 'd1PL+eVQWzY2bOxs+yfFrw6RYCvIpEsVGpvuFLYD4NKCD/3YDwNzFVCsIyiFKCxX\n'
                + 'vn2aGhjbAkEAwB4pfRFW9fKqiuDr+Xohn2L/5eYiwtqDrFKzCS7zwDFRCjPKP7oY\n'
                + 'FaqoW+c3bRdBJ99otB6lWsSd9elSCgXIswJBAJv2ZmZpMX1ZVc+QrxzRVAtWGxKN\n'
                + 'IAFJx10VPENvTLBZGqnxaF2nB74ZBhwBWHnxp61219D904r7viD7n/1wWvUCQBdu\n'
                + 'Vk8Lo1iBzSz8+6rEq38d+unWJJ0xO2fz+iP/lvj0ytZ8tIkLME7MLpZu38KtWGP9\n'
                + 'im6VYkNswXsxhrD0PaMCQGMmLGr8gsq9GeRkBetGTH4QiLFEpLanNXoCnStmuAF8\n'
                + '6Wikk/7w1vjZNzJUX43BWBkYKT2O9waibBowkVP4EBQ=\n';

  global class WebServiceResultExcludeInvoice {
    WebService Boolean status;
    WebService String message;
  }

  global class WebServiceResultIncludeInvoice {
    WebService Boolean status;
    WebService String message;
  }


  WebService static WebServiceResultExcludeInvoice excludeInvoiceReminder(String invoice_number) {
    WebServiceResultExcludeInvoice return_result = new WebServiceResultExcludeInvoice();
    List<Invoice__c> invoices = [SELECT Id, Name, Account__c, Invoice_Number__c, Exclude_Reminder__c FROM Invoice__c WHERE Invoice__c.Invoice_Number__c =: invoice_number];
    List<Invoice_Reminder_Exclude__c> excludes = [SELECT Id, Invoice_Number__c FROM Invoice_Reminder_Exclude__c];

    if(invoices.size() > 0) {
      Invoice__c the_invoice = invoices[0];
      Boolean found = false;
      if(excludes.size() > 0) {
        for(Invoice_Reminder_Exclude__c invoice_reminder_exclude : excludes) {
          if(invoice_reminder_exclude.Invoice_Number__c == the_invoice.Invoice_Number__c) {
            found = true;
          }
        }
      }

      if(found == false) {
      	/*
        // if we can not find it in the list we ADD it into the list
        Invoice_Reminder_Exclude__c invoice_reminder_exclude = new Invoice_Reminder_Exclude__c();
        invoice_reminder_exclude.Name = the_invoice.Name;
        invoice_reminder_exclude.Invoice_Number__c = invoice_number;
        invoice_reminder_exclude.Account__c = the_invoice.Account__c;
        insert invoice_reminder_exclude;

        System.debug('This invoice has been ADDED into invoice reminder exclude list: ' + the_invoice);
        return_result.status = true;
        return_result.message = 'This invoice has been added into invoice reminder exclude list';
        */
      }
      else {
        return_result.status = true;
        return_result.message = 'This invoice is already in the invoice reminder exclude list';
      }

      // now we set ALL invoices with this number to be excluded
      for(Integer i = 0; i < invoices.size(); i++) {      
        invoices[i].Exclude_Reminder__c = true;
      }
      update invoices;
    }
    else {
      return_result.status = false;
      return_result.message = 'Can not find invoice with this number';
    }

    return return_result;
  }


  WebService static WebServiceResultIncludeInvoice includeInvoiceReminder(String invoice_number) {
    WebServiceResultIncludeInvoice return_result = new WebServiceResultIncludeInvoice();
    List<Invoice__c> invoices = [SELECT Id, Name, Account__c, Invoice_Number__c, Exclude_Reminder__c FROM Invoice__c WHERE Invoice__c.Invoice_Number__c =: invoice_number];
    List<Invoice_Reminder_Exclude__c> excludes = [SELECT Id, Invoice_Number__c FROM Invoice_Reminder_Exclude__c];

    if(invoices.size() > 0) {
      Invoice__c the_invoice = invoices[0];
      Boolean found = false;
      if(excludes.size() > 0) {
        for(Invoice_Reminder_Exclude__c invoice_reminder_exclude : excludes) {
          if(invoice_reminder_exclude.Invoice_Number__c == the_invoice.Invoice_Number__c) {
            found = true;
            delete invoice_reminder_exclude;

            System.debug('This invoice has been ADDED into invoice reminder exclude list: ' + the_invoice);
            return_result.status = true;
            return_result.message = 'This invoice has been removed from invoice reminder exclude list';
          }
        }
      }

      if(found == false) {
        return_result.status = true;
        return_result.message = 'This invoice was not in invoice reminder exclude list';
      }

      // now we set ALL invoices with this number to be excluded
      for(Integer i = 0; i < invoices.size(); i++) {      
        invoices[i].Exclude_Reminder__c = false;
      }
      update invoices;
    }
    else {
      return_result.status = false;
      return_result.message = 'Can not find invoice with this number';
    }

    return return_result;
  }


  @future (callout=false)
  public static void setInvoiceReminderExcludeFlag() {
    // we loop the list of today's invoice
    List<Invoice_Batch__c> todaysBatches = [SELECT Id, Name, Batch_Date__c, Batch_Number__c, Batch_Processed__c, status__c, Batch_Type__c FROM Invoice_Batch__c WHERE Batch_Type__c = 'Invoices' AND Batch_Date__c =: Date.today()];
    /*
    if(todaysBatches.size() > 0) {
      Invoice_Batch__c todaysBatch = todaysBatches[0];
      // grab the list of invoices
      List<Invoice__c> invoices = [SELECT Id,Name,Payment_Batch__c,Payment_Message__c,Payment_Response__c,Account__c,Account_Product__c,Amount_Credited__c,Amount_Due__c,Amount_Paid__c,Due_Date__c,Invoice_Batch__c,Invoice_Number__c,Invoice_Total__c,Issue_Date__c,Payment_Option__c,Processed__c,Process_Message__c,Reference__c,Xero_Contact_Id__c,Xero_Invoice_Id__c, Exclude_Invoice__c, Exclude_Reminder__c FROM Invoice__c WHERE Invoice_Batch__c =: todaysBatch.Id];
      System.debug('All Invoices: ' + invoices);

      // grabthe list of excluded invoices
      List<Invoice_Reminder_Exclude__c> invoices_reminder_exclude = [SELECT Invoice_Number__c FROM Invoice_Reminder_Exclude__c];
      if(invoices_reminder_exclude.size() > 0) {
        // match them, loop over the invoice list and for each invoice
        // we loop the exclude list and match the invoice number. if
        // found a match, current invoice needs to be set as 'excluded'
            for(Integer i = 0; i < invoices.size(); i++) {
          System.debug('Updating Invoice: ' + invoices[i]);
          for(Invoice_Reminder_Exclude__c invoice_reminder_exclude : invoices_reminder_exclude) {
            if(invoices[i].Invoice_Number__c == invoice_reminder_exclude.Invoice_Number__c) {
              invoices[i].Exclude_Reminder__c = true;
            }
          }
            }
      }

      update invoices;
    }
    */
  }


  public static testMethod void excludeInvoiceReminderTest() {
    Test.startTest();
    
    Account acc = new Account(Name ='TestAccount1', username__c='TestAccount1', password__c='TestAccount1', CurrencyIsoCode ='AUD', Phone='78456213',Active__c= true , card_number__c ='3413551010014590', Card_Number_Masked__c ='34XX-XXXX-XXXX-4590' );
    insert acc;

    List<Account_Product__c> testProducts = new List<Account_Product__c>();
    for(Integer i=0;i<1;i++) {                              
        Account_Product__c item = new Account_Product__c(Name ='Social Engage '+1, Product_Status__c ='Active', Product_Price__c=1000, CurrencyIsoCode ='AUD', Account__c = acc.id , 
                      recordTypeId =Schema.SObjectType.Account_Product__c.getRecordTypeInfosByName().get('Tiger Pistol Product').getRecordTypeId());
        testProducts.add(item);
    }
    insert testProducts; 

	
    Invoice__c invoice1 = new Invoice__c();
    invoice1.name = 'test invoice';
    invoice1.Payment_Option__c = 'Other';
    invoice1.Invoice_Number__c = 'test--001';
    invoice1.Invoice_Batch__c = null;
    invoice1.Payment_Batch__c = null;
    invoice1.Xero_Contact_Id__c = 'E786047F-6DD3-4D62-B28D-6100D373AA08';
    invoice1.Account__c = acc.Id;
    invoice1.Account_Product__c = testProducts.get(0).Id;
    invoice1.Amount_Due__c = 4.50;
    insert invoice1;

    Invoice_Reminder_Exclude__c exclude = new Invoice_Reminder_Exclude__c();
    exclude.name = 'test invoice';
    exclude.Invoice_Number__c = 'test--001';
    exclude.Account__c = null;
    exclude.Email__c = null;
    insert exclude;

    InvoiceReminder.excludeInvoiceReminder(invoice1.Invoice_Number__c);
    Test.stopTest();
  }

  public static testMethod void excludeInvoiceReminderErrorTest() {
    Test.startTest();
    
    Account acc = new Account(Name ='TestAccount1', username__c='TestAccount1', password__c='TestAccount1', CurrencyIsoCode ='AUD', Phone='78456213',Active__c= true , card_number__c ='3413551010014590', Card_Number_Masked__c ='34XX-XXXX-XXXX-4590' );
    insert acc;

    List<Account_Product__c> testProducts = new List<Account_Product__c>();
    for(Integer i=0;i<1;i++) {                              
        Account_Product__c item = new Account_Product__c(Name ='Social Engage '+1, Product_Status__c ='Active', Product_Price__c=1000, CurrencyIsoCode ='AUD', Account__c = acc.id , 
                      recordTypeId =Schema.SObjectType.Account_Product__c.getRecordTypeInfosByName().get('Tiger Pistol Product').getRecordTypeId());
        testProducts.add(item);
    }
    insert testProducts; 



    Invoice__c invoice1 = new Invoice__c();
    invoice1.name = 'test invoice';
    invoice1.Payment_Option__c = 'Other';
    invoice1.Invoice_Number__c = 'test--001';
    invoice1.Invoice_Batch__c = null;
    invoice1.Payment_Batch__c = null;
    invoice1.Xero_Contact_Id__c = 'E786047F-6DD3-4D62-B28D-6100D373AA08';
    invoice1.Account__c = acc.Id;
    invoice1.Account_Product__c = testProducts.get(0).Id;
    invoice1.Amount_Due__c = 4.50;
    insert invoice1;

    Invoice_Reminder_Exclude__c exclude = new Invoice_Reminder_Exclude__c();
    exclude.name = 'test invoice';
    exclude.Invoice_Number__c = 'test--001';
    exclude.Account__c = null;
    exclude.Email__c = null;
    insert exclude;

    InvoiceReminder.excludeInvoiceReminder('fakeinvoicenumber');
    Test.stopTest();
  }

  public static testMethod void includeReminderInvoiceTest() {
    Test.startTest();
    
    Account acc = new Account(Name ='TestAccount1', username__c='TestAccount1', password__c='TestAccount1', CurrencyIsoCode ='AUD', Phone='78456213',Active__c= true , card_number__c ='3413551010014590', Card_Number_Masked__c ='34XX-XXXX-XXXX-4590' );
    insert acc;

    List<Account_Product__c> testProducts = new List<Account_Product__c>();
    for(Integer i=0;i<1;i++) {                              
        Account_Product__c item = new Account_Product__c(Name ='Social Engage '+1, Product_Status__c ='Active', Product_Price__c=1000, CurrencyIsoCode ='AUD', Account__c = acc.id , 
                      recordTypeId =Schema.SObjectType.Account_Product__c.getRecordTypeInfosByName().get('Tiger Pistol Product').getRecordTypeId());
        testProducts.add(item);
    }
    insert testProducts; 

    Invoice__c invoice1 = new Invoice__c();
    invoice1.name = 'test invoice';
    invoice1.Payment_Option__c = 'Other';
    invoice1.Invoice_Number__c = 'test--001';
    invoice1.Invoice_Batch__c = null;
    invoice1.Payment_Batch__c = null;
    invoice1.Xero_Contact_Id__c = 'E786047F-6DD3-4D62-B28D-6100D373AA08';
    invoice1.Account__c = acc.Id;
    invoice1.Account_Product__c = testProducts.get(0).Id;
    invoice1.Amount_Due__c = 4.50;
    invoice1.Exclude_Invoice__c = true;
    invoice1.Exclude_Reminder__c = true;
    insert invoice1;

    Invoice_Reminder_Exclude__c exclude = new Invoice_Reminder_Exclude__c();
    exclude.name = 'test invoice';
    exclude.Invoice_Number__c = 'test--001';
    exclude.Account__c = null;
    exclude.Email__c = null;
    insert exclude;

    InvoiceReminder.includeInvoiceReminder(invoice1.Invoice_Number__c);
    Test.stopTest();
  }

  public static testMethod void setInvoiceReminderExcludeFlagTest() {
    Test.startTest();

    Invoice_Batch__c batch1 = new Invoice_Batch__c();
    batch1.Name = '';
    batch1.Batch_Date__c = Date.today();
    batch1.Batch_Type__c = 'Invoices';
    
    Account acc = new Account(Name ='TestAccount1', username__c='TestAccount1', password__c='TestAccount1', CurrencyIsoCode ='AUD', Phone='78456213',Active__c= true , card_number__c ='3413551010014590', Card_Number_Masked__c ='34XX-XXXX-XXXX-4590' );
    insert acc;

    List<Account_Product__c> testProducts = new List<Account_Product__c>();
    for(Integer i=0;i<1;i++) {                              
        Account_Product__c item = new Account_Product__c(Name ='Social Engage '+1, Product_Status__c ='Active', Product_Price__c=1000, CurrencyIsoCode ='AUD', Account__c = acc.id , 
                      recordTypeId =Schema.SObjectType.Account_Product__c.getRecordTypeInfosByName().get('Traditional Products').getRecordTypeId());
        testProducts.add(item);
    }
    insert testProducts; 

    Invoice__c invoice1 = new Invoice__c();
    invoice1.name = 'test invoice';
    invoice1.Payment_Option__c = 'Other';
    invoice1.Invoice_Number__c = 'test--001';
    invoice1.Invoice_Batch__c = batch1.Id;
    invoice1.Payment_Batch__c = null;
    invoice1.Xero_Contact_Id__c = 'E786047F-6DD3-4D62-B28D-6100D373AA08';
    invoice1.Account__c = acc.Id;
    invoice1.Account_Product__c = testProducts.get(0).Id;
    invoice1.Amount_Due__c = 4.50;
    invoice1.Exclude_Invoice__c = false;
    invoice1.Exclude_Reminder__c = false;
    insert invoice1;

    Invoice_Reminder_Exclude__c exclude = new Invoice_Reminder_Exclude__c();
    exclude.name = 'test invoice';
    exclude.Invoice_Number__c = 'test--001';
    exclude.Account__c = null;
    exclude.Email__c = null;
    insert exclude;

    InvoiceReminder.setInvoiceReminderExcludeFlag();
    Test.stopTest();
  }

}