src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_14_days_num_of_calls__c</fullName>
        <description>Last 14 days num of calls</description>
        <inlineHelpText>Last 14 days num of calls</inlineHelpText>
        <label>Last 14 days num of calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_14_days_num_of_emails__c</fullName>
        <description>Last 14 days num of emails</description>
        <inlineHelpText>Last 14 days num of emails</inlineHelpText>
        <label>Last 14 days num of emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_7_days_num_of_calls__c</fullName>
        <description>Last 7 days num of calls</description>
        <inlineHelpText>Last 7 days num of calls</inlineHelpText>
        <label>Last 7 days num of calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_7_days_num_of_emails__c</fullName>
        <description>Last 7 days num of emails</description>
        <inlineHelpText>Last 7 days num of emails</inlineHelpText>
        <label>Last 7 days num of emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountProductHelperTest.cls
@isTest
private class AccountProductHelperTest {
	@testSetup static void setup(){
        // Create common test accounts
        List<Account> testAccts = new List<Account>();
        try{               
                Account itemAcc = new Account(Name ='TestAccount1', username__c='TestAccount1', password__c='TestAccount1', CurrencyIsoCode ='AUD', Phone='78456213',Active__c= true);
                testAccts.add(itemAcc);
                itemAcc = new Account(Name ='TestAccount2', username__c='TestAccount2', password__c='TestAccount2', CurrencyIsoCode ='AUD', Phone='78456213', Active__c= true);
                testAccts.add(itemAcc);
                insert testAccts; 
                
                // create account products
                List<Account_Product__c> testProducts = new List<Account_Product__c>();
                for(Integer i=0;i<2;i++) {            
                    Account_Product__c item = new Account_Product__c(Name ='Adword'+1, Product_Price__c=1000, CurrencyIsoCode ='AUD', Account__c =testAccts.get(0).id, Product_Status__c ='Active' );
                    testProducts.add(item);
                }
                insert testProducts; 
                
                List<Contact> contacts= new List<Contact>();
                for(Integer i =0; i< testAccts.size(); i++){
                    Account item = testAccts.get(i);
                    Contact con = new Contact (AccountId = item.id,LastName = 'test contact'); 
                    contacts.add(con);
                }
                insert contacts;

                String userID = ''+ UserInfo.getUserId() ;
                List<Task> tasks = new List<Task>();
				Task tsk1 = new Task(WhatId = testAccts[0].Id, Subject = '→ Email: apex test', ActivityDate = date.today(), Status = 'Completed' , OwnerID = userID );
				tasks.add(tsk1);
				Task tsk2 = new Task(WhatId = testAccts[0].Id, Subject = 'Outbound call: apex test', ActivityDate = date.today(), Status = 'Completed', OwnerID = userID );
				tasks.add(tsk2);				
				Task tsk3 = new Task(WhatId = testAccts[0].Id, Subject = '→ Email: apex test', ActivityDate = date.today().addYears(-2), Status = 'Completed', OwnerID = userID );
				tasks.add(tsk3);
				insert tasks;				
                
        }catch(DMLException e){
            system.debug('retry' + e.getMessage());
        }
    }
    


	@isTest static void test_fetchDailyData() {
		// Implement test code
		AccountProductHelper helper = new AccountProductHelper();
		//helper.fetchDailyData();
		list<Account_Product__c> activeProducts = [SELECT Id, Product_Status__c, Account__c, OwnerId, 
												  Last_14_days_num_of_calls__c, Last_14_days_num_of_emails__c,Last_7_days_num_of_calls__c,Last_7_days_num_of_emails__c 
												FRoM Account_Product__c 
												WHERE Product_Status__c = 'Active' and Account__r.Active__c= true];

		System.assertEquals(activeProducts[0].Last_14_days_num_of_calls__c, 0);
		System.assertEquals(activeProducts[0].Last_14_days_num_of_emails__c, 0);
		System.assertEquals(activeProducts[0].Last_7_days_num_of_calls__c, 0);
		System.assertEquals(activeProducts[0].Last_7_days_num_of_emails__c, 0);
	}

	
}