src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_14_days_num_of_calls__c</fullName>
        <description>Last 14 days num of calls</description>
        <inlineHelpText>Last 14 days num of calls</inlineHelpText>
        <label>Last 14 days num of calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_14_days_num_of_emails__c</fullName>
        <description>Last 14 days num of emails</description>
        <inlineHelpText>Last 14 days num of emails</inlineHelpText>
        <label>Last 14 days num of emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_21_days_num_of_calls__c</fullName>
        <description>Last 21 days num of calls</description>
        <inlineHelpText>Last 21 days num of calls</inlineHelpText>
        <label>Last 21 days num of calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_21_days_num_of_emails__c</fullName>
        <description>Last 21 days num of emails</description>
        <inlineHelpText>Last 21 days num of emails</inlineHelpText>
        <label>Last 21 days num of emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_7_days_num_of_calls__c</fullName>
        <description>Last 7 days num of calls</description>
        <inlineHelpText>Last 7 days num of calls</inlineHelpText>
        <label>Last 7 days num of calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_7_days_num_of_emails__c</fullName>
        <description>Last 7 days num of emails</description>
        <inlineHelpText>Last 7 days num of emails</inlineHelpText>
        <label>Last 7 days num of emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Projects__c.object
<CustomObject>
    <description>A professional services engagement that tracks all related Resources and Project details.</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Product__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Stage__c</fullName>
        <label>Project Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Pending 1st Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Project Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Contract - Billing Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Contract - Billing Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under-going Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Closed - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract - Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - New Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Monthly Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reporting Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Google Adwords</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
                <color>#419249</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Web Design</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Web &amp; SEO</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Work Web</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Additional SEO Work</fullName>
                <color>#333399</color>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Directory Listings SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Visibility SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile &amp; Web Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admob Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+ Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConvertoPages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explainer Videos</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SEOAccountProductProcessortTest.cls
@isTest
private class SEOAccountProductProcessortTest
{
	
	@isTest static void test_pass() {
        // Create common test accounts
        List<Account> testAccts = new List<Account>();
        try{               
                Account itemAcc = new Account(Name ='TestAccount1', username__c='TestAccount1', password__c='TestAccount1', CurrencyIsoCode ='AUD', Phone='78456213',Active__c= true);
                testAccts.add(itemAcc);
                itemAcc = new Account(Name ='TestAccount2', username__c='TestAccount2', password__c='TestAccount2', CurrencyIsoCode ='AUD', Phone='78456213', Active__c= true);
                testAccts.add(itemAcc);
                insert testAccts; 
                
                // create account products
                List<Account_Product__c> testProducts = new List<Account_Product__c>();
                for(Integer i=0;i<2;i++) {            
                    Account_Product__c item = new Account_Product__c(Name ='SEO'+1, Product_Price__c=1000, CurrencyIsoCode ='AUD', Account__c =testAccts.get(0).id, Product_Status__c ='Active', Recurring_Period__c = 'Weekly');
                    testProducts.add(item);
                }


                insert testProducts; 
                
                // create project
                String userID = ''+ UserInfo.getUserId() ;
                SFDC_Projects__c project = new SFDC_Projects__c(Name ='SEO' , Project_Stage__c='Ongoing Management', Project_Type__c ='SEO' , Account_Product__c = testProducts[0].id, OwnerID = userID);

                List<Contact> contacts= new List<Contact>();
                for(Integer i =0; i< testAccts.size(); i++){
                    Account item = testAccts.get(i);
                    Contact con = new Contact (AccountId = item.id,LastName = 'test contact'); 
                    contacts.add(con);
                }
                insert contacts;

                //String userID = ''+ UserInfo.getUserId() ;
                List<Task> tasks = new List<Task>();
				Task tsk1 = new Task(WhatId = project.Id, Subject = '→ Email: apex test', ActivityDate = date.today(), Status = 'Completed' , OwnerID = userID , TaskSubtype = 'Email');
				tasks.add(tsk1);
				Task tsk2 = new Task(WhatId = project.Id, Subject = 'Outbound call: apex test', ActivityDate = date.today(), Status = 'Completed', OwnerID = userID , calltype = 'Outbound');
				tasks.add(tsk2);				
				Task tsk3 = new Task(WhatId = project.Id, Subject = '→ Email: apex test', ActivityDate = date.today().addYears(-2), Status = 'Completed', OwnerID = userID , TaskSubtype = 'Email');
				tasks.add(tsk3);
				insert tasks;				

				// Implement test code
				Test.startTest();



		        SEOAccountProductProcessor obj = new SEOAccountProductProcessor('');
		        DataBase.executeBatch(obj, 10); 
		            
		        Test.stopTest();
				list<Account_Product__c> activeProducts = [SELECT Id, Product_Status__c, Account__c, OwnerId, 
														  Last_14_days_num_of_calls__c, Last_14_days_num_of_emails__c,Last_7_days_num_of_calls__c,Last_7_days_num_of_emails__c ,
                                                          Last_21_days_num_of_calls__c,Last_21_days_num_of_emails__c 
														FRoM Account_Product__c 
														WHERE Product_Status__c = 'Active' and Account__r.Active__c= true AND Recurring_Period__c <> 'N/A'];

    //            System.assertEquals(activeProducts[0].Last_21_days_num_of_calls__c, 2);
    //            System.assertEquals(activeProducts[0].Last_21_days_num_of_emails__c, 4);
				//System.assertEquals(activeProducts[0].Last_14_days_num_of_calls__c, 2);
				//System.assertEquals(activeProducts[0].Last_14_days_num_of_emails__c, 4);
				//System.assertEquals(activeProducts[0].Last_7_days_num_of_calls__c, 2);
				//System.assertEquals(activeProducts[0].Last_7_days_num_of_emails__c, 4);
                
        }catch(DMLException e){
            system.debug('retry' + e.getMessage());
        }


	}
}