src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employee_Department__c</fullName>
        <label>Employee Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support &amp; Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SLXOpportunity__c.object
<CustomObject>
    <description>Opportunity</description>
    <fields>
        <fullName>Assign_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assign to</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BJB Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/assignOpportunity.cls
public with sharing class assignOpportunity {
	public String options {get; set;}
	public SLXOpportunity__c opp {get;set;}
	
	
	
	public assignOpportunity(ApexPages.StandardController controller){
		this.opp = (SLXOpportunity__c)controller.getRecord();
			
	
	}
	
	public List<SelectOption> getSalespersons() {
		
		List<Account> accounts = [select Id, Name from Account where Employee_Department__c = 'Sales' and Type = 'Employee' and Active__c = true];
		List<SelectOption> options = new List<SelectOption>();
		options.add(new SelectOption('','--None--'));
		for(Account account : accounts){
    	    options.add(new SelectOption(account.Id,account.Name));
   		}
    	return options;
	}
	
	public PageReference assign(){
		try{
			System.debug(this.opp);
			this.opp.Assign_to__c = this.options;
			update this.opp;
		}catch(Exception e){
			System.debug(e.getMessage());
		}
			
		PageReference curPage = ApexPages.currentPage();
		curPage.getParameters().put('success','true');
		curPage.getParameters().put('id', this.opp.Id);
		curPage.setRedirect(true);
	   	return curPage;
	}
	
	
	public static testMethod void testassignOpp() {
		Account acc = new Account();
		acc.Employee_Department__c = 'Sales';
		acc.Type = 'Employee';
		acc.Active__c = true;
		acc.username__c = 'test123456';
		acc.password__c = '123';
		acc.Name        = 'test';
		insert acc;
		SLXOpportunity__c opp = new SLXOpportunity__c();
		ApexPages.standardController controller = new ApexPages.standardController(opp);
		assignOpportunity a = new assignOpportunity(controller);
		a.getSalespersons();
		a.assign();
	
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}