src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Infusionsoft_id__c</fullName>
        <label>Infusionsoft_id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Invoice_Date__c</fullName>
        <label>Last Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Frequency__c</fullName>
        <description>The frequency of this product to be billed</description>
        <label>Recurring Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pauseat__c</fullName>
        <label>pauseat</label>
        <type>Date</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <formula>TEXT(Account.Payment_Option__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Option</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/pardotContactTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class pardotContactTestClass {

    static testMethod void myUnitTest() {
        Test.startTest();
        Account account = new Account();
		account.Name = 'Test Account';
		account.Company__c = 'SponsoredLinX';
		account.username__c = 'test@test12.com';
		account.password__c = 'test';
		insert account;
        
        pardotContactIterable pardotContactIterable = new pardotContactIterable();
        if(pardotContactIterable.hasNext()){
        	Account account1 = pardotContactIterable.next();
        }
        Test.stopTest();
    }
    
    public static testMethod void testpardotContactIterator() {
        Test.startTest();
        Account account = new Account();
		account.Name = 'Test Account';
		account.Company__c = 'SponsoredLinX';
		account.username__c = 'test@test.com';
		account.password__c = 'test';
		insert account;
        
        pardotContactIterator pardotContactIterator = new pardotContactIterator();
        Iterator<Account> aps = pardotContactIterator.Iterator();
        Test.stopTest();
  }
  
  public static testMethod void testpardotContactBatch() {
        Test.startTest();
        pardotContactBatch scriptBatch = new pardotContactBatch();
        Account account = new Account();
		account.Name = 'Test Account11';
		account.Company__c = 'SponsoredLinX';
		account.username__c = 'test11d11@test.com';
		account.password__c = 'test';
		insert account;
		
		Contact testContact = new Contact();
    	testContact.AccountId = account.Id;
    	testContact.Title = 'Marketing';
    	testContact.FirstName = 'test';
    	testContact.LastName = 'test';
    	testContact.MailingStreet = 'test';
    	insert testContact;
        
        Account_Product__c ap = new Account_Product__c();
        ap.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap.Recurring_Frequency__c = 1;
        ap.Name = 'Facebook';
        //ap.pauseat__c = Date.today();
        ap.Product_Price__c = 19.99;
        ap.Recurring_Period__c ='Weekly';
        ap.Payment_Option__c = 'Eway';
        ap.Product_Status__c = 'Paused';
        ap.Account__c = account.Id;
        insert ap;
        
        Account_Product__c fbap = new Account_Product__c();
        fbap.Last_Invoice_Date__c = Date.today().addDays(-7);
        fbap.Recurring_Frequency__c = 1;
        fbap.Name = 'Facebook';
        //ap.pauseat__c = Date.today();
        fbap.Product_Price__c = 19.99;
        fbap.Recurring_Period__c ='Weekly';
        fbap.Payment_Option__c = 'Eway';
        fbap.Product_Status__c = 'Active';
        fbap.Account__c = account.Id;
        insert fbap;
        
        
        
        Account_Product__c ap1 = new Account_Product__c();
        ap1.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap1.Recurring_Frequency__c = 1;
        ap1.Name = 'SEO';
        ap1.Product_Status__c = 'Active';
        ap1.Product_Price__c = 19.99;
        ap1.Recurring_Period__c ='Weekly';
        ap1.Payment_Option__c = 'Eway';
        ap1.Account__c = account.Id;
        insert ap1;
        
        Account_Product__c ap0 = new Account_Product__c();
        ap0.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap0.Recurring_Frequency__c = 1;
        ap0.Name = 'SEO';
        ap0.Product_Status__c = 'Cancelled';
        ap0.Product_Price__c = 19.99;
        ap0.Recurring_Period__c ='Weekly';
        ap0.Payment_Option__c = 'Eway';
        ap0.Account__c = account.Id;
        insert ap0;
        
        Account_Product__c ap10 = new Account_Product__c();
        ap10.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap10.Recurring_Frequency__c = 1;
        ap10.Name = 'Social Media';
        ap10.Product_Status__c = 'Cancelled';
        ap10.Product_Price__c = 19.99;
        ap10.Recurring_Period__c ='Weekly';
        ap10.Payment_Option__c = 'Eway';
        ap10.Account__c = account.Id;
        insert ap10;
        
        Account_Product__c ap11 = new Account_Product__c();
        ap11.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap11.Recurring_Frequency__c = 1;
        ap11.Name = 'Social Media';
        ap11.Product_Status__c = 'Active';
        ap11.Product_Price__c = 19.99;
        ap11.Recurring_Period__c ='Weekly';
        ap11.Payment_Option__c = 'Eway';
        ap11.Account__c = account.Id;
        insert ap11;
        
        Account_Product__c ap2 = new Account_Product__c();
        ap2.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap2.Recurring_Frequency__c = 1;
        ap2.Name = 'Adwords';
        ap2.Product_Status__c = 'Cancelled';
        ap2.Product_Price__c = 19.99;
        ap2.Recurring_Period__c ='Weekly';
        ap2.Payment_Option__c = 'Eway';
        ap2.Account__c = account.Id;
        insert ap2;
       
        Database.batchableContext info;
        scriptBatch.start(info);
        List<Account> scope = [select Id, Name, Owner.Name, Website, infusionsoft_Id__c FROM Account limit 5];
        scriptBatch.execute(info, scope);
        scriptBatch.finish(info);
        
        Test.stopTest();
    }
    public static testMethod void testpardotContactBatch1() {
        Test.startTest();
        pardotContactBatch scriptBatch = new pardotContactBatch();
        Account account = new Account();
		account.Name = 'Test Account11';
		account.Company__c = 'SponsoredLinX';
		account.username__c = 'test11d11@test.com';
		account.password__c = 'test';
		insert account;
		
		Contact testContact = new Contact();
    	testContact.AccountId = account.Id;
    	testContact.Title = 'Billing';
    	testContact.FirstName = 'test';
    	testContact.LastName = 'test';
    	testContact.MailingStreet = 'test';
    	insert testContact;
        
        
        
        Account_Product__c ap10 = new Account_Product__c();
        ap10.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap10.Recurring_Frequency__c = 1;
        ap10.Name = 'Adwords';
        ap10.Product_Status__c = 'Active';
        ap10.Product_Price__c = 89.99;
        ap10.Recurring_Period__c ='Weekly';
        ap10.Payment_Option__c = 'Eway';
        ap10.Account__c = account.Id;
        insert ap10;
        
        Account_Product__c ap2 = new Account_Product__c();
        ap2.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap2.Recurring_Frequency__c = 1;
        ap2.Name = 'SEO';
        ap2.Product_Status__c = 'Cancelled';
        ap2.Product_Price__c = 19.99;
        ap2.Recurring_Period__c ='Weekly';
        ap2.Payment_Option__c = 'Eway';
        ap2.Account__c = account.Id;
        insert ap2;
       
        Database.batchableContext info;
        scriptBatch.start(info);
        List<Account> scope = [select Id, Name, Owner.Name, Website, infusionsoft_Id__c FROM Account limit 5];
        scriptBatch.execute(info, scope);
        scriptBatch.finish(info);
        
        Test.stopTest();
    }
    public static testMethod void testpardotContactBatch2() {
        Test.startTest();
        pardotContactBatch scriptBatch = new pardotContactBatch();
        Account account = new Account();
		account.Name = 'Test Account11';
		account.Company__c = 'SponsoredLinX';
		account.username__c = 'test11d11@test.com';
		account.password__c = 'test';
		insert account;
		
		Contact testContact = new Contact();
    	testContact.AccountId = account.Id;
    	testContact.Title = 'Billing';
    	testContact.FirstName = 'test';
    	testContact.LastName = 'test';
    	testContact.MailingStreet = 'test';
    	insert testContact;
        
        
        
        Account_Product__c ap10 = new Account_Product__c();
        ap10.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap10.Recurring_Frequency__c = 1;
        ap10.Name = 'Adwords';
        ap10.Product_Status__c = 'Active';
        ap10.Product_Price__c = 109.99;
        ap10.Recurring_Period__c ='Weekly';
        ap10.Payment_Option__c = 'Eway';
        ap10.Account__c = account.Id;
        insert ap10;
        
        Account_Product__c ap2 = new Account_Product__c();
        ap2.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap2.Recurring_Frequency__c = 1;
        ap2.Name = 'ConvertoPages';
        ap2.Product_Status__c = 'Paused';
        ap2.Product_Price__c = 19.99;
        ap2.Recurring_Period__c ='Weekly';
        ap2.Payment_Option__c = 'Eway';
        ap2.Account__c = account.Id;
        insert ap2;
        
        Account_Product__c ap3 = new Account_Product__c();
        ap3.Last_Invoice_Date__c = Date.today().addDays(-7);
        ap3.Recurring_Frequency__c = 1;
        ap3.Name = 'ConvertoPages';
        ap3.Product_Status__c = 'Active';
        ap3.Product_Price__c = 19.99;
        ap3.Recurring_Period__c ='Weekly';
        ap3.Payment_Option__c = 'Eway';
        ap3.Account__c = account.Id;
        insert ap3;
        
        Account_Product__c fbap = new Account_Product__c();
        fbap.Last_Invoice_Date__c = Date.today().addDays(-7);
        fbap.Recurring_Frequency__c = 1;
        fbap.Name = 'Facebook';
        //ap.pauseat__c = Date.today();
        fbap.Product_Price__c = 19.99;
        fbap.Recurring_Period__c ='Weekly';
        fbap.Payment_Option__c = 'Eway';
        fbap.Product_Status__c = 'Cancelled';
        fbap.Account__c = account.Id;
        insert fbap;
       
        Database.batchableContext info;
        scriptBatch.start(info);
        List<Account> scope = [select Id, Name, Owner.Name, Website, infusionsoft_Id__c FROM Account limit 5];
        scriptBatch.execute(info, scope);
        scriptBatch.finish(info);
        
        Test.stopTest();
    }
    
    public static testMethod void pardotContactScheduleTest() {
	    Test.StartTest();
	    
	    datetime time1 = Datetime.now();
	    datetime time2 = time1.addSeconds(5);
	    String seconds = String.valueOf(time2.second());
	    String minutes = String.valueOf(time2.minute());
	    String hours = String.valueOf(time2.hour());
	    
	    String sch = seconds+' '+minutes+' '+hours+' ? * MON-SUN';  
	    System.debug('sch:'+sch);
	    System.schedule('infusionsoftScheduletest', sch, new pardotContactScheduler());
	      
	    Test.stopTest();
    }
}