src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Last_Invoice_Date__c</fullName>
        <label>Last Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Recurring_Frequency__c</fullName>
        <description>The frequency of this product to be billed</description>
        <label>Recurring Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>activeat__c</fullName>
        <label>activeat</label>
        <type>Date</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceCreateIterator.cls
global class InvoiceCreateIterator implements Iterable<Account_Product__c> {
	
	public InvoiceCreateIterator() {
		
	}

	global Iterator<Account_Product__c> Iterator() {
		return new InvoiceCreateIterable();
		
	}
	
	public static testMethod void testInvoiceCreateIterator() {
        Test.startTest();
        Account_Product__c ap = new Account_Product__c();
        ap.Last_Invoice_Date__c = Date.today();
        ap.Recurring_Frequency__c = 1;
        ap.Product_Price__c = 19.99;
        ap.activeat__c = Date.today();
        insert ap;
        
        InvoiceCreateIterator invoiceCreateIterator = new InvoiceCreateIterator();
        Iterator<Account_Product__c> aps = invoiceCreateIterator.Iterator();
        Test.stopTest();
    }
	
	
	
	
}