src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Branding_Theme_Id__c</fullName>
        <label>Branding Theme Id</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Logo_Code__c</fullName>
        <label>Logo Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Xero_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Xero Invoices</relationshipLabel>
        <relationshipName>Xero_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AmountCredited__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>AmountCredited</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AmountDue__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>AmountDue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AmountPaid__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>AmountPaid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BrandingThemeID__c</fullName>
        <label>BrandingThemeID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>DueDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InvoiceID__c</fullName>
        <externalId>true</externalId>
        <label>InvoiceID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <externalId>true</externalId>
        <label>InvoiceNumber</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LineAmountTypes__c</fullName>
        <label>LineAmountTypes</label>
        <picklist>
            <picklistValues>
                <fullName>Inclusive</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Exclusive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>DRAFT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTHORISED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBMITTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOIDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TEMPLATE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubTotal__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>SubTotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalTax__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>TotalTax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>ACCREC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACCPAY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UpdatedDateUTC__c</fullName>
        <label>UpdatedDateUTC</label>
        <type>DateTime</type>
    </fields>
    <label>Xero Invoice</label>
    <nameField>
        <label>Xero Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SingleInvoiceController.cls
public with sharing class SingleInvoiceController {

	private final Xero_Invoice__c invoice;
	private final Account account;
	private final Contact contact;
	private final Company__c company;

	public SingleInvoiceController() {
		invoice = [SELECT Id, InvoiceID__c, InvoiceNumber__c, Date__c, DueDate__c, Account__c, Reference__c, LineAmountTypes__c, AmountCredited__c, AmountDue__c, AmountPaid__c, BrandingThemeID__c, Status__c, SubTotal__c, TotalTax__c, Total__c, Type__c, UpdatedDateUTC__c FROM Xero_Invoice__c WHERE Xero_Invoice__c.Id =: ApexPages.currentPage().getParameters().get('id')];
		account = [SELECT Id, Name, Company__c FROM Account WHERE Account.Unique_Id__c =: invoice.Reference__c];
		contact = [SELECT Id, MailingStreet, MailingCity, MailingState, MailingCountry, MailingPostalCode, Phone FROM Contact WHERE AccountId =: account.Id AND Title = 'Billing'];
		company = [SELECT Id, Address__c, Branding_Theme_Id__c, Business_Name__c, Email__c, Logo_Code__c, Phone__c FROM Company__c WHERE Company__c.Branding_Theme_Id__c =: invoice.BrandingThemeID__c];
	}

	public Xero_Invoice__c getInvoice() {
		return invoice;
	}

	public Account getAccount() {
		return account;
	}

	public Contact getContact() {
		return contact;
	}

	public Company__c getCompany() {
		return company;
	}

	public PageReference save() {
		update invoice;
		return null;
	}

}