src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Account_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <description>Please provide as much info as possible</description>
        <label>Case Reason</label>
        <picklist>
            <picklistValues>
                <fullName>BTS:Act of God</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Issues re SLX or Google Fees/Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Signup not compl by Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Technical/Legal/Industry std issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>----------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Sold to other products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Client referred a client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Sold to pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Relationship Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Alter billing method</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: EOM discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Holiday Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-----------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Bad reassign from last CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Didn&apos;t see account was down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Forced Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Insufficient contact with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Pause Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Lack of ROI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Resume off pause - now cancelling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: CM error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM          - Tech issue (Scripts not running)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM - Poor Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Google billing down 2+ weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - 3+ SLX invoices unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Agreed work not completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Insufficient Contact With Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Save Strat Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>---------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client:Bad site, said no to landing page</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Daily_Budget__c</fullName>
        <description>Current AdWords Daily Budget</description>
        <label>Daily Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Internal_Comments__c</fullName>
        <label>Internal Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <color>#FF9900</color>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X2012_Action_Taken_to_Save__c</fullName>
        <defaultValue>&quot;If you have attempted to save the client, please detail your save strategy.&quot;</defaultValue>
        <description>Action Taken to Save</description>
        <inlineHelpText>If you have attempted to save the client, please detail your save strategy.</inlineHelpText>
        <label>Action Taken to Save</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SFDC_Projects__c.object
<CustomObject>
    <description>A professional services engagement that tracks all related Resources and Project details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cases__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <color>#FFCC66</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_by__c</fullName>
        <label>Sold by</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CasesForProjectController.cls
public with sharing class CasesForProjectController {
	private List<Cases__c> cs;
	private SFDC_Projects__c project {get; set;}
	
	public CasesForProjectController(ApexPages.StandardController controller) {
		this.project = (SFDC_Projects__c)controller.getRecord();
	}
	
	public List<Cases__c> getCs() {
		SFDC_Projects__c project = [select id, Account__c from SFDC_Projects__c where id = :project.id];
		if(project.Account__c == null) return null;
		cs = [select Id, Name, Status__c, Case_Reason__c, Priority__c, CreatedDate, CreatedById, Internal_Comments__c from Cases__c where account__c = :project.Account__c];
		return cs;
	}
	
	public static testMethod void coverageTest() {
		Account acc = new Account();
		acc.name = 'acc1';
		insert acc;
		
		Cases__c ca = new Cases__c();
		ca.account__c = acc.id;
		ca.daily_budget__c = 20;
		ca.X2012_Action_Taken_to_Save__c  = 'fdaskl';
		insert ca;
		
		SFDC_Projects__c p = new SFDC_Projects__c();
    	p.account__c = acc.id;
    	p.name = 'name';
    	p.Sold_by__c = 'ss';
    	p.Phone_Number__c = '123456789';
    	p.Email__c = 'fdas@jlkdfs.com';
    	insert p;
		
		ApexPages.StandardController sc = new ApexPages.StandardController(p);
		CasesForProjectController cc = new CasesForProjectController(sc);
		List<Cases__c> cases = cc.getCs();
		
	}
}