src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Days__c</fullName>
        <label>Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Adwords_Active_Days__c</fullName>
        <label>Adwords Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Adwords_Product__c</fullName>
        <label>Adwords Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancelled_Date__c</fullName>
        <label>Cancelled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Converto_Active_Days__c</fullName>
        <label>Converto Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Converto_Product__c</fullName>
        <label>Converto Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facebook_Active_Days__c</fullName>
        <label>Facebook Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Facebook_Product__c</fullName>
        <label>Facebook Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optimised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SEO_Active_Days__c</fullName>
        <label>SEO Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SEO_Product__c</fullName>
        <label>SEO Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Days__c</fullName>
        <label>Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <formula>IF(ISPICKVAL(Recurring_Period__c, &apos;Weekly&apos;), Product_Price__c*52/12, 
IF(ISPICKVAL(Recurring_Period__c, &apos;Fortnightly&apos;), Product_Price__c*26/12, 
IF(ISPICKVAL(Recurring_Period__c, &apos;Yearly&apos;), Product_Price__c/12, 
Product_Price__c)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SEO_Active_Days__c</fullName>
        <formula>cancelat__c - DATEVALUE(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SEO Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cancelat__c</fullName>
        <label>cancelat</label>
        <type>Date</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Product__c</fullName>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Client_Histories</relationshipLabel>
        <relationshipName>Client_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lasting_Days__c</fullName>
        <formula>IF(ISNULL(End_Date__c), today() -Start_Date__c+1, End_Date__c - Start_Date__c+1)</formula>
        <label>Lasting Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client_History</label>
    <nameField>
        <label>ClientHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client_Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Adwords_Product__c</fullName>
        <label>Adwords Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Converto_Product__c</fullName>
        <label>Converto Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facebook_Product__c</fullName>
        <label>Facebook Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optimised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SEO_Product__c</fullName>
        <label>SEO Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SFDC_Projects__c.object
<CustomObject>
    <description>A professional services engagement that tracks all related Resources and Project details.</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Product__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/pardotAccountBatch.cls
global class pardotAccountBatch implements Database.batchable<Account>,Database.Stateful , Database.AllowsCallouts{
    global Iterable<Account> start(Database.batchableContext info) {    
        return new pardotAccountIterator();  
    }
    

    global void calActivityAndStatusForProduct(List<Account> scope){
            String productname = '';
            List<Account_Product__c> updatedProducts = new List<Account_Product__c>();

            for(Account account : scope){
                try{
                        List<Account_Product__c> products = [SELECT Id, 
                                                                 Name,
                                                                 Product_Status__c, 
                                                                 Monthly_Price__c, 
                                                                 No_Open_Activity__c,
                                                                 No_Complete_Task_Within_4_Weeks__c,
                                                                 Owner.Name,
                                                                 From_Last_Paid_Date__c,
                                                                 Last_Paid_Date__c,
                                                                 suspendedat__c,
                                                                 Account__c,
                                                                 cancelat__c 
                                                            FROM Account_Product__c 
                                                            WHERE 
                                                                Account__c=:account.Id 
                                                                AND (Recurring_Period__c !='N/A' AND Recurring_Period__c != '')
                                                                AND (Name like '%Facebook%' or Name like '%Adwords%' or Name like '%SEO%' or Name Like 'Social%' or Name Like '%Converto%' )
                                                                AND Product_Status__c = 'Active'];

                        for(Account_Product__c ap : products) {
                                if (!ap.Name.containsIgnoreCase('SEO')){
                                    // no open activity
                                    List<Task> openTask = [SELECT id, status FROM Task WHERE IsRecurrence  = false  AND status='Not Started' AND AccountID = :ap.Account__c and Owner.Name = :ap.Owner.Name ];
                                    if (openTask == null || openTask.size()==0 ){
                                        ap.No_Open_Activity__c = true;
                                    }else{
                                        ap.No_Open_Activity__c = false;
                                    }

                                    // no completed activity within 4 weeks
                                    List<Task> completedTask = [SELECT id, status FROM Task WHERE IsRecurrence  = false AND status='Completed' AND AccountID = :ap.Account__c and Owner.Name = :ap.Owner.Name  AND LastModifiedDate = LAST_N_DAYS:28];
                                    if (completedTask == null || completedTask.size()==0 ){
                                        ap.No_Complete_Task_Within_4_Weeks__c = true;
                                    }else{
                                        ap.No_Complete_Task_Within_4_Weeks__c = false;
                                    }

                                 }
                                 else{
                                    List<SFDC_Projects__c>  projects = [SELECT id
                                                                        FROM SFDC_Projects__c
                                                                        WHERE Account_Product__c = :ap.Id
                                                                                ORDER BY CreatedDate DESC
                                                                                LIMIT 1];
                                    // open activity
                                    List<Task> openTasks = [SELECT id, status 
                                                                FROM Task 
                                                                WHERE status='Not Started' 
                                                                    AND IsRecurrence  = false
                                                                    AND WhatId  =:projects.get(0).id 
                                                                    AND  Owner.Name = :ap.Owner.Name];


                                    // no completed activity within 4 weeks
                                    List<Task> completedTasks = [SELECT id, status 
                                                                FROM Task 
                                                                WHERE status='Completed'    
                                                                    AND IsRecurrence  = false                                                               
                                                                    AND WhatId  =:projects.get(0).id 
                                                                    AND  Owner.Name = :ap.Owner.Name  
                                                                    AND LastModifiedDate = LAST_N_DAYS:28];


                                    // no open activity
                                    if(openTasks ==null || openTasks.size() ==0){
                                        ap.No_Open_Activity__c = true;                                      
                                    }else{
                                        ap.No_Open_Activity__c = false;
                                    }

                                    // no completed activity
                                    if (completedTasks == null || completedTasks.size()==0 ){
                                        ap.No_Complete_Task_Within_4_Weeks__c = true;
                                    }else{
                                        ap.No_Complete_Task_Within_4_Weeks__c = false;
                                    }

                                 }
                                 
                                //evaluate social engage product's status base on last_paid_date__c
                                if(ap.name.containsIgnoreCase('Social Engage')){
                                    if(ap.From_Last_Paid_Date__c >= 6 &&  ap.product_status__c.equalsIgnoreCase('Active')){
                                        ap.product_status__c = 'Suspended';
                                        ap.suspendedat__c = System.Date.Today();
                                        ap.Last_Paid_Date__c = null;
                                        
                                        // make a synchronous call to TigerPistol
                                        system.debug('TigerPistol suspended product.id = ' + ap.id);
                                        TigerPistolConnector.pauseCustomerSynch(ap.id);
                                    }
                                }
                                updatedProducts.add(ap);
                        }   
                }catch(Exception ex){
                    system.debug(ex.getMessage());  
                }
            }

            try{
                update updatedProducts;
            }catch (Exception e){
                system.debug(e.getMessage());
            }

    }

    global void execute(Database.batchableContext info, List<Account> scope){

        calActivityAndStatusForProduct(scope);

        for(Account account : scope){
            try {
                String productname = '';
                
                Decimal account_active_days  = 0;
                Decimal adwords_active_days  = 0;
                Decimal facebook_active_days = 0;
                Decimal seo_active_days      = 0;
                Decimal converto_active_days = 0;
                
                Boolean adsActive    = false;
                Boolean adsPaused    = false;
                Boolean adsCancelled = false;   
                                
                Boolean seoActive    = false;
                Boolean seoPaused    = false;
                Boolean seoCancelled = false;
                    
                Boolean facebookActive    = false;
                Boolean facebookPaused    = false;
                Boolean facebookCancelled = false;
                    
                Boolean convertoActive    = false;
                Boolean convertoPaused    = false;
                Boolean convertoCancelled = false;
                
                Date cancelledDate        = null;
                    
                    
                List<Date> cancelledDates = new List<Date>(); 
                    
                String package_name = '';
                
                Boolean first_record = true;
                    
                for(Account_Product__c product : [SELECT Id, 
                                                         Name,
                                                         Product_Status__c, 
                                                         Monthly_Price__c, 
                                                         No_Open_Activity__c,
                                                         No_Complete_Task_Within_4_Weeks__c,
                                                         cancelat__c 
                                                    FROM Account_Product__c 
                                                    WHERE Account__c=:account.Id 
                                                    AND (Recurring_Period__c !='N/A' AND Recurring_Period__c != '')
                                                    AND (Name like '%Facebook%' or Name like '%Adwords%' or Name like '%SEO%' or Name Like '%Social%' or Name Like '%Converto%' OR Name Like 'Social Engage%' )
                                                    ORDER BY
                                                    cancelat__c Desc]) {
                    System.debug('Product Record: '+product);
                    productname = '';
                    productname = product.Name.toLowerCase();
                    if( first_record && product.cancelat__c != null){
                        cancelledDate = product.cancelat__c;
                        first_record = false;
                    }
                    
                    Decimal product_active_days = 0;
                    
                    Client_History__c[] chs = [select 
                                                    Lasting_Days__c 
                                                from 
                                                    Client_History__c 
                                                where 
                                                    Type__c = 'Active'
                                                and 
                                                    Account_Product__c =: product.Id];
                    if(chs.size() > 0 ){
                        for(Client_History__c ch : chs){
                            product_active_days += ch.Lasting_Days__c;
                        }
                    }
                    system.debug(productname);  
                    if(productname.contains('adwords')) {
                        if(product.Product_Status__c == 'Active'){
                            adsActive = true;
                            if(product.Monthly_Price__c <= 343 ){
                                package_name = 'Standard';
                            }else if(product.Monthly_Price__c <= 386){
                                package_name = 'Optimised';
                            }else if(product.Monthly_Price__c <= 429){
                                package_name = 'Premium';
                            }
                        }else if(product.Product_Status__c == 'Paused'){
                            adsPaused = true;
                        }else if(product.Product_Status__c == 'Cancelled'){
                            adsCancelled = true;
                            cancelledDates.add(product.cancelat__c);
                        }
                        adwords_active_days += product_active_days;
                        
                    } else if(productname.contains('seo')) {
                                if(product.Product_Status__c == 'Active'){
                                    seoActive = true;
                                }else if(product.Product_Status__c == 'Paused'){
                                    seoPaused = true;
                                }else if(product.Product_Status__c == 'Cancelled'){
                                    seoCancelled = true;
                                }
                                seo_active_days += product_active_days;
                                    
                    } else if(productname.contains('facebook') || productname.contains('social media')) {
                                system.debug(product.Product_Status__c);
                                if(product.Product_Status__c == 'Active' || product.Product_Status__c == 'Pending Linking'){
                                    facebookActive = true;
                                }else if(product.Product_Status__c == 'Paused'){
                                    facebookPaused = true;
                                }else if(product.Product_Status__c == 'Cancelled'){
                                    facebookCancelled = true;
                                }
                            facebook_active_days += product_active_days;
                    }else if(productname.contains('convertopages')) {
                        System.debug('Product Name Contains ConvertoPages');
                                if(product.Product_Status__c == 'Active'){
                                    convertoActive = true;
                                }else if(product.Product_Status__c == 'Paused'){
                                    convertoPaused = true;
                                }else if(product.Product_Status__c == 'Cancelled'){
                                    convertoCancelled = true;
                                }
                                converto_active_days += product_active_days;
                    }
                    
                    product.Active_Days__c = product_active_days;


                    try{
                        update product;
                    }catch(Exception e){
                        system.debug(e.getMessage());
                    }
                }
                system.debug('finished looping products');
                if(adsActive){
                    account.Adwords_Product__c = 'Active';
                }else if(adsPaused){
                    account.Adwords_Product__c = 'Paused';
                }else if(adsCancelled){
                    account.Adwords_Product__c = 'Cancelled';
                }
                    
                account.Package_Name__c = package_name;
                if(seoActive){
                    account.SEO_Product__c = 'Active';
                }else if(seoPaused){
                    account.SEO_Product__c = 'Paused';
                }else if(seoCancelled){
                    account.SEO_Product__c = 'Cancelled';
                }
                
                if(facebookActive){
                    account.Facebook_Product__c = 'Active';
                }else if(facebookPaused){
                    account.Facebook_Product__c = 'Paused';
                }else if(facebookCancelled){
                    account.Facebook_Product__c = 'Cancelled';
                }
                    
                if(convertoActive){
                    account.Converto_Product__c = 'Active';
                }else if(convertoPaused){
                    account.Converto_Product__c = 'Paused';
                }else if(convertoCancelled){
                    account.Converto_Product__c = 'Cancelled';
                }
                    
                if(adsActive || seoActive || facebookActive || convertoActive){
                    account.Active__c = true;
                }else{
                    account.Active__c = false;
                }
                system.debug('converto'+ account.Converto_Product__c );
                system.debug('adwords'+ account.Adwords_Product__c );
                system.debug('seo'+ account.SEO_Product__c );
                system.debug('facebook'+ account.Facebook_Product__c );
                
                if((account.Converto_Product__c == null || account.Converto_Product__c == 'Cancelled')
                    &&(account.Adwords_Product__c == null || account.Adwords_Product__c == 'Cancelled')
                    &&(account.SEO_Product__c == null || account.SEO_Product__c == 'Cancelled')
                    &&(account.Facebook_Product__c == null || account.Facebook_Product__c == 'Cancelled')
                ){
                    account.cancelled_date__c = cancelledDate;
                }
                
                
                account.Adwords_Active_Days__c  = adwords_active_days;
                account.SEO_Active_Days__c      = seo_active_days;
                account.Facebook_Active_Days__c = facebook_active_days;
                account.Converto_Active_Days__c = converto_active_days;
                
                account.Active_Days__c          = adwords_active_days + facebook_active_days + seo_active_days;

                update account;
              
          } catch(Exception e) {
               System.debug('Error fetching contact record');
               System.debug('EXCEPTION: '+e.getMessage());
          }
    }
        
    }
    global void finish(Database.batchableContext info){
        
        }
}