src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Days__c</fullName>
        <label>Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProductActiveDaysIterable.cls
global class  ProductActiveDaysIterable implements Iterator<Account>{
	Integer i {get;set;}
	List<Account> accounts {get;set;}
	
	public ProductActiveDaysIterable() {
		
		this.accounts = [Select 
							   Id,
							   Name,
							   Active_Days__c,
							   Phone,
							   (select Phone from Contacts where title = 'Marketing' limit 1)
						From 
							   Account
						WHERE
							   Active__c = true
						];
      								
		this.i = 0;
		
		
	}

	global boolean hasNext() {
		if(this.i >= this.accounts.size()) 
        	return false; 
		else 
        	return true;	
	}

	global Account next() {
   		return this.accounts[this.i++];	
	}
	

}