src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the company which manages this account</description>
        <inlineHelpText>the company which manages this account</inlineHelpText>
        <label>BJB Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <formula>Account__r.BJB_Company__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BJB Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>IF(OR(CONTAINS(Name,&quot;Adwords&quot;),(CONTAINS(Name, &quot;AdWords&quot;))), &apos;AdWords Management&apos;,
IF(CONTAINS(Name,&quot;SEO&quot;),&apos;SEO&apos;,
IF(CONTAINS(Name,&quot;Facebook&quot;), &apos;Social Marketing&apos;, 
IF(CONTAINS(Name,&quot;Social&quot;), &apos;Social Marketing&apos;,
IF(CONTAINS(Name,&quot;Converto&quot;), &apos;ConvertoPages&apos;, &apos;&apos;) ))))</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Resolution__c</fullName>
        <label>Account Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved to SEO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Account_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <description>Please provide as much info as possible</description>
        <label>Case Reason</label>
        <picklist>
            <picklistValues>
                <fullName>BTS:Act of God</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Issues re SLX or Google Fees/Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Signup not compl by Decision maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS:Technical/Legal/Industry std issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>----------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Sold to other products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Client referred a client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Sold to pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Relationship Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Alter billing method</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: EOM discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales: Holiday Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-----------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Bad reassign from last CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Didn&apos;t see account was down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Forced Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Insufficient contact with client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Pause Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Lack of ROI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: Resume off pause - now cancelling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM: CM error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM          - Tech issue (Scripts not running)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM - Poor Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Google billing down 2+ weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - 3+ SLX invoices unpaid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Agreed work not completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Insufficient Contact With Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Error - Save Strat Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>---------------------------------------</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client:Bad site, said no to landing page</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Daily_Budget__c</fullName>
        <description>Current AdWords Daily Budget</description>
        <label>Daily Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>Account_Product__r.Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resolution Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X2012_Action_Taken_to_Save__c</fullName>
        <defaultValue>&quot;If you have attempted to save the client, please detail your save strategy.&quot;</defaultValue>
        <description>Action Taken to Save</description>
        <inlineHelpText>If you have attempted to save the client, please detail your save strategy.</inlineHelpText>
        <label>Action Taken to Save</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <description>Company official home page</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Default_Manager__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Default Manager</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>password__c</fullName>
        <label>Password</label>
        <length>30</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CasesProcessorTest.cls
@isTest
public class CasesProcessorTest {
    @testSetup static void setup(){
        // Create common test accounts
        List<Account> testAccts = new List<Account>();
        try{               

                Company__c company = new Company__c();
                company.Name                = 'SponsoredLinX';
                company.Business_Name__c    = 'SponsoredLinX';
                company.Website__c          = 'www.sponsoredlinx.com';
                company.CurrencyIsoCode     = 'AUD';
                insert company;
                Company__c company2 = new Company__c();
                company.Name                = 'GetMoreTraffice';
                company.Business_Name__c    = 'GetMoreTraffice';
                company.Website__c          = 'www.GetMoreTraffice.com';
                company.CurrencyIsoCode     = 'AUD';
                insert company2;


                Account itemAcc = new Account(Name ='TestAccount1', username__c='TestAccount1', password__c='TestAccount1', CurrencyIsoCode ='AUD', Phone='1300859600',BJB_Company__c = company.Id);
                testAccts.add(itemAcc);
                itemAcc = new Account(Name ='TestAccount2', username__c='TestAccount2', password__c='TestAccount2', CurrencyIsoCode ='AUD', Phone='1300859600', BJB_Company__c  = company2.Id);
                testAccts.add(itemAcc);        
                insert testAccts; 
                
                // create account products
                List<Account_Product__c> testProducts = new List<Account_Product__c>();
                for(Integer i=0;i<2;i++) {            
                    Account_Product__c item = new Account_Product__c(Name ='Social'+1, Product_Price__c=1000, CurrencyIsoCode ='AUD', Account__c =testAccts.get(0).id );
                    testProducts.add(item);
                }
                insert testProducts; 
                
                List<Contact> contacts= new List<Contact>();
                for(Integer i =0; i< testAccts.size(); i++){
                    Account item = testAccts.get(i);
                    Contact con = new Contact (AccountId = item.id,LastName = 'test contact',Phone='1300859600', Title = 'Billing'); 
                    contacts.add(con);
                }
                insert contacts;
                
                //create user with Resolution Manager Profiles
                Profile p = [select Id, name from Profile where Name = 'Resolution Manager' limit 1];        
                List<User> users = new List<User>();
                for(Integer i =0; i< testAccts.size(); i++){
                    User newUser = new User(profileId = p.id,
                                            username = 'myTestUser'+i+'@yahoo.com',
                                            email = 'testUser1@ff.com',
                                            emailencodingkey = 'UTF-8',
                                            localesidkey = 'en_US',
                                            languagelocalekey = 'en_US',
                                            timezonesidkey = 'America/Los_Angeles',
                                            alias='nuser',
                                            firstname='Ben',
                                            lastname=' Bradshaw',
                                            IsActive = true
                                            );
                    users.add(newUser);
                }
                insert users;

                users[0].ManagerId = users[1].Id;
                users[1].ManagerId = UserInfo.getUserId();
                update users;

                //create setting data
                List<Default_Manager__c> managers = new List<Default_Manager__c>();
                Default_Manager__c manager = new Default_Manager__c(Name='SLX_BTS_Manager', Value__c =users[0].Id);  
                managers.add(manager) ;             
                Default_Manager__c manager2 = new Default_Manager__c(Name='GMT_BTS_Manager', Value__c =users[0].Id);
                managers.add(manager2) ;
                insert managers;

                                
                // create cases with status=new  
                System.runAs(users[0]){
                    List<Cases__c> cases = new List<Cases__c>();
                    Cases__c obj = new Cases__c(X2012_Action_Taken_to_Save__c='check1',Account__c=testAccts[0].id, Daily_Budget__c=7000, CurrencyIsoCode='AUD', Account_Product__c = testProducts[0].id , Status__c ='New', Account_Resolution__c = 'Save', Case_Reason__c = 'BTS: Act of God');
                    cases.add(obj);
                    obj = new Cases__c(X2012_Action_Taken_to_Save__c='check2',Account__c=testAccts[0].id, Daily_Budget__c=7000, CurrencyIsoCode='AUD', Account_Product__c = testProducts[0].id , Status__c ='New', Account_Resolution__c = 'Pause');
                    cases.add(obj); 
                    insert cases;   
                }
         }catch(DMLException e){
            system.debug('retry' + e.getMessage());
        }
    }
    
    @isTest static void testEscalateCase(){                
        List<Cases__c> testCase = [SELECT Account__c,Account_Product__c, Product_Type__c, Resolution_Manager__c, Daily_Budget__c, Status__c, Case_Reason__c FROM Cases__c WHERE Status__c <> 'Escalated'  ];
        for(Cases__c item: testCase){
            item.Status__c = 'Escalated';
            
        }
        update testCase;
        Cases__c realCase = [SELECT Account__c,Account_Product__c, Resolution_Manager__r.lastname, Daily_Budget__c, Status__c FROM Cases__c WHERE Status__c = 'Escalated' AND Account_Resolution__c = 'Save' LIMIT 1];
        System.assertNotEquals(null, realCase.Resolution_Manager__c);        
        realCase = [SELECT Account__c,Account_Product__c, Resolution_Manager__r.lastname, Daily_Budget__c, Status__c FROM Cases__c WHERE  Status__c = 'Escalated' AND Account_Resolution__c <> 'Save' LIMIT 1];
        System.assertNotEquals(null, realCase.Resolution_Manager__c);        
    }
}