src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the company which manages this account</description>
        <inlineHelpText>the company which manages this account</inlineHelpText>
        <label>BJB Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <description>Company official home page</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Projects__c.object
<CustomObject>
    <description>A professional services engagement that tracks all related Resources and Project details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sold_by__c</fullName>
        <label>Sold by</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuestionnaireControllerTest.cls
@isTest
private class QuestionnaireControllerTest
{

	@testSetup	static void setup(){	
		Company__c company = new Company__c();
        company.Name                = 'SponsoredLinX';
        company.Business_Name__c    = 'SponsoredLinX';
        company.Website__c          = 'www.sponsoredlinx.com';
        company.CurrencyIsoCode     = 'AUD';
        insert company;
        Company__c company2 = new Company__c();
        company.Name                = 'GetMoreTraffice';
        company.Business_Name__c    = 'GetMoreTraffice';
        company.Website__c          = 'www.GetMoreTraffice.com';
        company.CurrencyIsoCode     = 'AUD';
        insert company2;

		Account acc = new Account();
		acc.name = 'acc1';
		acc.BJB_Company__c  = company2.Id;
		insert acc;
		
		
		SFDC_Projects__c p = new SFDC_Projects__c();
    	p.account__c = acc.id;
    	p.name = 'name';
    	p.Sold_by__c = 'ss';
    	p.Phone_Number__c = '123456789';
    	p.Email__c = 'fdas@jlkdfs.com';
    	insert p;
	}

	@isTest
	static void testSaveQuestionnaire()
	{
		QuestionnaireController ques = new QuestionnaireController();
		Account acc =[SELECT id FROM Account limit 1];
		SFDC_Projects__c p = [SELECT id FROM SFDC_Projects__c limit 1];
		ApexPages.currentPage().getParameters().put('accId', acc.id);
		ApexPages.currentPage().getParameters().put('projectId', p.id);
		ques.save();
		System.assertEquals(ques.step, '2', 'Error');

	}


}