src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PauseSmallThanActive__c</fullName>
        <formula>IF(pauseat__c &lt;= activeat__c , &apos;true&apos;, &apos;false&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PauseSmallThanActive</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>activeat__c</fullName>
        <label>activeat</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>cancelSmallThanActive__c</fullName>
        <formula>IF(cancelat__c &lt;= activeat__c , &apos;true&apos;, &apos;false&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>cancelSmallThanActive</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cancelSmallThanPause__c</fullName>
        <formula>IF(cancelat__c &lt;= pauseat__c, &apos;true&apos;, &apos;false&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>cancelSmallThanPause</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cancelat__c</fullName>
        <label>cancelat</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pauseat__c</fullName>
        <label>pauseat</label>
        <type>Date</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_History__c.object
<CustomObject>
    <fields>
        <fullName>Account_Product__c</fullName>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Client_Histories</relationshipLabel>
        <relationshipName>Client_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>null if the product status is ongoing</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client_History</label>
    <nameField>
        <label>ClientHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client_Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateClientHistoriesBatch.cls
global class CreateClientHistoriesBatch implements Database.Batchable<sObject>{

	global final String Query;
	
	global CreateClientHistoriesBatch () {
		Query = 'select id, product_status__c, recurring_period__c, createdDate, cancelsmallthanactive__c, cancelsmallthanpause__c, pausesmallthanactive__c, activeat__c, pauseat__c, cancelat__c, start_date__c, Cancellation_Date__c from account_product__c';
	}
	
	global Database.QueryLocator start (Database.BatchableContext BC)
    {
           return Database.getQueryLocator(Query);
    }
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
    	for(sObject ob : scope) {
    		account_product__c ap = (account_product__c)ob;
    		if (ap.product_status__c == 'Active' && ap.pauseat__c == null && ap.activeat__c != null && ap.Recurring_Period__c != null && ap.Recurring_Period__c != 'N/A' && ap.id != 'a0790000002OHLIAA4') {
		    	//skip a0790000002OHLIAA4
		    	createActiveWithoutBreak(ap);
    		}
    		/*
		    if (ap.product_status__c == 'Active' && ap.pauseat__c == null && (ap.Recurring_Period__c == null || ap.Recurring_Period__c == 'N/A')) {
		    	createOnceOff(ap);
		    } else if (ap.product_status__c == 'Active' && ap.pauseat__c == null && ap.activeat__c == null && ap.Recurring_Period__c != null && ap.Recurring_Period__c != 'N/A' && ap.id != 'a0790000002OHLIAA4') {
		    	//skip a0790000002OHLIAA4
		    	createActiveWithoutBreak(ap);
		    } else if (ap.product_status__c == 'Active' && ap.pauseat__c != null && ap.activeat__c == null) {
		    	createActiveWithoutBreak(ap);
		    } else if (ap.id == 'a07900000047U5RAAU') {
		    	createOnceOff(ap);
			} else if (ap.product_status__c == 'Active' && ap.pauseat__c != null && ap.activeat__c != null && ap.cancelat__c == null && (ap.Recurring_Period__c == null || ap.Recurring_Period__c == 'N/A')) {
				createActiveWithBreak(ap);
			} else if (ap.product_status__c == 'Active' && ap.pauseat__c != null && ap.activeat__c != null && ap.cancelat__c == null && ap.Recurring_Period__c != null && ap.Recurring_Period__c != 'N/A' && ap.pauseat__c <= date.today()) {
				createActiveWithBreak(ap);
			} else if (ap.product_status__c == 'Active' && ap.pauseat__c != null && ap.activeat__c != null && ap.cancelat__c == null && ap.Recurring_Period__c != null && ap.Recurring_Period__c != 'N/A' && ap.pauseat__c > date.today()) {
				createActiveWithoutBreak(ap);
			} else if (ap.product_status__c == 'Active' && ap.pauseat__c != null && ap.activeat__c != null && ap.cancelat__c != null) {
				createActiveWithBreak(ap);
			} else if (ap.product_status__c == 'Paused' && ap.pauseat__c != null && ap.activeat__c != null) {
				createOngoingPause(ap);
			} else if (ap.product_status__c == 'Cancelled' && ap.pauseat__c == null && ap.activeat__c == null && ap.cancelat__c == null) {
				if (ap.Start_Date__c != null && ap.cancellation_date__c != null) {
					createOldCancelled(ap);
				}
			} else if (ap.product_status__c == 'Cancelled' && ap.pauseat__c == null && ap.activeat__c == null && ap.cancelat__c != null) {
				createActiveCancel(ap);
			} else if (ap.product_status__c == 'Cancelled' && ap.pauseat__c == null && ap.activeat__c != null && ap.cancelat__c != null) {
				createActiveCancel(ap);
			} else if (ap.product_status__c == 'Cancelled' && ap.pauseat__c != null && ap.activeat__c != null && ap.cancelat__c != null && ap.cancelsmallthanactive__c == 'false' && ap.pausesmallthanactive__c == 'true') {
				createActivePauseActiveCancel(ap);
			} else if (ap.product_status__c == 'Cancelled' && ap.pauseat__c != null && ap.activeat__c != null && ap.cancelat__c != null && ap.cancelsmallthanpause__c == 'false' && ap.pausesmallthanactive__c == 'false') {
				createActivePauseCancel(ap);
			} else if (ap.product_status__c == 'Cancelled' && ap.pauseat__c != null && ap.activeat__c != null && ap.cancelat__c != null && ap.cancelsmallthanactive__c == 'true' && ap.pausesmallthanactive__c == 'true') {
				createActivePauseCancel(ap);
			}
			*/
      	} 
   }
   
   global void finish(Database.BatchableContext BC){
   }
   
   
   private void createActiveWithoutBreak (account_product__c ap) {
		Client_History__c ch = new Client_History__c();
        ch.account_product__c = ap.id;
        date min = Date.newinstance(ap.createdDate.year(),ap.createdDate.month(),ap.createdDate.day());
        if (ap.activeat__c != null && ap.activeat__c < min) min = ap.activeat__c;
        if (ap.start_date__c != null && ap.start_date__c < min) min = ap.start_date__c;
        ch.start_date__c = min;
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
	}
	
	/*
   //Most once-off paid product are something like 'Adwords Premium Setup' etc. The majority (99%+ I asure) of them are Active products. 
	private void createOnceOff (account_product__c ap) {
		Client_History__c ch = new Client_History__c();
        ch.account_product__c = ap.id;
        date min = Date.newinstance(ap.createdDate.year(),ap.createdDate.month(),ap.createdDate.day());
        if (ap.activeat__c != null && ap.activeat__c < min) min = ap.activeat__c;
        if (ap.start_date__c != null && ap.start_date__c < min) min = ap.start_date__c;
        ch.start_date__c = min;
        ch.end_date__c = min;
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
	}
	
	private void createActiveWithBreak (account_product__c ap) {
		Client_History__c ch = new Client_History__c();
        ch.account_product__c = ap.id;
        date min = Date.newinstance(ap.createdDate.year(),ap.createdDate.month(),ap.createdDate.day());
        if (ap.start_date__c != null && ap.start_date__c < min) min = ap.start_date__c;
        ch.start_date__c = min;
        ch.end_date__c = ap.pauseat__c.addDays(-1);
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.pauseat__c;
        ch.end_date__c = ap.activeat__c.addDays(-1);
        ch.type__c = 'Paused';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.activeat__c;
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
	}
	
	private void createOngoingPause (account_product__c ap) {
		Client_History__c ch = new Client_History__c();
        ch.account_product__c = ap.id;
        date min = Date.newinstance(ap.createdDate.year(),ap.createdDate.month(),ap.createdDate.day());
        if (ap.start_date__c != null && ap.start_date__c < min) min = ap.start_date__c;
        ch.start_date__c = min;
        ch.end_date__c = ap.pauseat__c.addDays(-1);
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.pauseat__c;
        ch.type__c = 'Paused';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
	}
	
	//old product info from old systems
	private void createOldCancelled (account_product__c ap) {
		Client_History__c ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.Start_Date__c;
        ch.end_date__c = ap.Cancellation_Date__c.addDays(-1);
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.Cancellation_Date__c;
        ch.end_date__c = ap.Cancellation_Date__c;
        ch.type__c = 'Cancelled';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
	}
	
	//active -> cancel
	private void createActiveCancel (account_product__c ap) {
		Client_History__c ch = new Client_History__c();
        ch.account_product__c = ap.id;
        date min = Date.newinstance(ap.createdDate.year(),ap.createdDate.month(),ap.createdDate.day());
        if (ap.activeat__c != null && ap.activeat__c < min) min = ap.activeat__c;
        if (ap.start_date__c != null && ap.start_date__c < min) min = ap.start_date__c;
        ch.start_date__c = min;
        ch.end_date__c = ap.cancelat__c.addDays(-1);
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.cancelat__c;
        ch.end_date__c = ap.cancelat__c;
        ch.type__c = 'Cancelled';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
	}
	
	//active -> pause -> cancel
	private void createActivePauseCancel (account_product__c ap) {
		Client_History__c ch = new Client_History__c();
        ch.account_product__c = ap.id;
        date min = Date.newinstance(ap.createdDate.year(),ap.createdDate.month(),ap.createdDate.day());
        if (ap.activeat__c != null && ap.activeat__c < min) min = ap.activeat__c;
        if (ap.start_date__c != null && ap.start_date__c < min) min = ap.start_date__c;
        ch.start_date__c = min;
        ch.end_date__c = ap.pauseat__c.addDays(-1);
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.pauseat__c;
        ch.end_date__c = ap.cancelat__c.addDays(-1);
        ch.type__c = 'Paused';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.cancelat__c;
        ch.end_date__c = ap.cancelat__c;
        ch.type__c = 'Cancelled';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
	}
	//active -> pause -> active -> cancel
	private void createActivePauseActiveCancel (account_product__c ap) {
		Client_History__c ch = new Client_History__c();
        ch.account_product__c = ap.id;
        date min = Date.newinstance(ap.createdDate.year(),ap.createdDate.month(),ap.createdDate.day());
        if (ap.start_date__c != null && ap.start_date__c < min) min = ap.start_date__c;
        ch.start_date__c = min;
        ch.end_date__c = ap.pauseat__c.addDays(-1);
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.pauseat__c; 
        ch.end_date__c = ap.activeat__c.addDays(-1);
        ch.type__c = 'Paused';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.activeat__c;
        ch.end_date__c = ap.cancelat__c.addDays(-1);
        ch.type__c = 'Active';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
        
        ch = new Client_History__c();
        ch.account_product__c = ap.id;
        ch.start_date__c = ap.cancelat__c;
        ch.end_date__c = ap.cancelat__c;
        ch.type__c = 'Cancelled';
        ch.name = ch.type__c + ' at ' + ch.start_date__c.format();
        upsert(ch);
	}
	*/
	
	public static testMethod void testBatch () {
		Account acc = new Account();
		acc.name = 'testAcc';
		insert acc;
		
		Account_Product__c active = new Account_Product__c();
		active.Account__c = acc.id;
        active.Product_Price__c = 19.99;
        active.product_status__c = 'Active';
        active.Recurring_Period__c ='Weekly';
        active.Payment_Option__c = 'Eway';
        active.start_date__c = date.newinstance(2012, 1, 1);
        active.activeat__c = date.newinstance(2012, 7, 1);
        insert active;
		
		/*
		Account_Product__c active = new Account_Product__c();
		active.Account__c = acc.id;
        active.Product_Price__c = 19.99;
        active.product_status__c = 'Active';
        active.Recurring_Period__c ='Weekly';
        active.Payment_Option__c = 'Eway';
        active.start_date__c = date.newinstance(2012, 1, 1);
        insert active;
        
        Account_Product__c onceoff = new Account_Product__c();
		onceoff.Account__c = acc.id;
        onceoff.Product_Price__c = 199.99;
        onceoff.product_status__c = 'Active';
        onceoff.Payment_Option__c = 'Eway';
        onceoff.start_date__c = date.newinstance(2012, 1, 1);
        insert onceoff;
        
        Account_Product__c activePause = new Account_Product__c();
		activePause.Account__c = acc.id;
        activePause.Product_Price__c = 199.99;
        activePause.product_status__c = 'Paused';
        activePause.Payment_Option__c = 'Eway';
        activePause.start_date__c = date.newinstance(2012, 1, 1);
        activePause.Pauseat__c = date.newinstance(2012, 3, 1);
        activePause.Activeat__c = date.newinstance(2013, 3, 1);
        insert activePause;
        
        Account_Product__c activePauseActive = new Account_Product__c();
		activePauseActive.Account__c = acc.id;
        activePauseActive.Product_Price__c = 199.99;
        activePauseActive.product_status__c = 'Active';
        activePauseActive.Payment_Option__c = 'Eway';
        activePauseActive.start_date__c = date.newinstance(2012, 1, 1);
        activePauseActive.Pauseat__c = date.newinstance(2012, 3, 1);
        activePauseActive.Activeat__c = date.newinstance(2012, 5, 1);
        insert activePauseActive;
        
        Account_Product__c cancel = new Account_Product__c();
		cancel.Account__c = acc.id;
        cancel.Product_Price__c = 199.99;
        cancel.product_status__c = 'Cancelled';
        cancel.Payment_Option__c = 'Eway';
        cancel.start_date__c = date.newinstance(2010, 1, 1);
        cancel.Cancellation_Date__c = date.newinstance(2011, 1, 1);
        insert cancel;

		Account_Product__c activeCancel = new Account_Product__c();
		activeCancel.Account__c = acc.id;
        activeCancel.Product_Price__c = 199.99;
        activeCancel.product_status__c = 'Cancelled';
        activeCancel.Payment_Option__c = 'Eway';
        activeCancel.start_date__c = date.newinstance(2012, 1, 1);
        activeCancel.Cancelat__c = date.newinstance(2012, 5, 1);
        insert activeCancel;
        
        Account_Product__c activePauseCancel = new Account_Product__c();
		activePauseCancel.Account__c = acc.id;
        activePauseCancel.Product_Price__c = 199.99;
        activePauseCancel.product_status__c = 'Cancelled';
        activePauseCancel.Payment_Option__c = 'Eway';
        activePauseCancel.start_date__c = date.newinstance(2012, 1, 1);
        activePauseCancel.Pauseat__c = date.newinstance(2012, 3, 1);
        activePauseCancel.Cancelat__c = date.newinstance(2012, 5, 1);
        activePauseCancel.Activeat__c = date.newinstance(2012, 5, 1);
        insert activePauseCancel;
        
        Account_Product__c activePauseActiveCancel = new Account_Product__c();
		activePauseActiveCancel.Account__c = acc.id;
        activePauseActiveCancel.Product_Price__c = 199.99;
        activePauseActiveCancel.product_status__c = 'Cancelled';
        activePauseActiveCancel.Payment_Option__c = 'Eway';
        activePauseActiveCancel.start_date__c = date.newinstance(2012, 1, 1);
        activePauseActiveCancel.Pauseat__c = date.newinstance(2012, 3, 1);
        activePauseActiveCancel.Activeat__c = date.newinstance(2012, 4, 1);
        activePauseActiveCancel.Cancelat__c = date.newinstance(2012, 5, 1);
        insert activePauseActiveCancel;
        */
		Test.startTest();
		CreateClientHistoriesBatch b = new CreateClientHistoriesBatch();
		ID batchprocessid = Database.executeBatch(b, 50);
		Test.stopTest();
	}
}