src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Website__c</fullName>
        <description>Company official home page</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Sign_Up__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sign Up</label>
        <referenceTo>Sign_Up__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daily_Budget__c</fullName>
        <label>Daily Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>AdWords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admob Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConvertoPages</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SLXOpportunity__c.object
<CustomObject>
    <description>Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_Daily_Budget__c</fullName>
        <label>Adwords Daily Budget</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_Number__c</fullName>
        <label>Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adwords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+ Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Upgrade</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Send_to_Salesperson__c</fullName>
        <label>Send to Salesperson (no longer used)</label>
        <picklist>
            <picklistValues>
                <fullName>Gretel Phillips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daniel Andreotti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tate Wotton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simon Golding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meg Arreza</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joshua Beatty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Teamleader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abigail Harrison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ngawai Mason</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>BJB Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>password__c</fullName>
        <label>Password</label>
        <length>30</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EditOpportunity.cls
public with sharing class EditOpportunity {
	public SLXOpportunity__c opp {get; set;}
	public ApexPages.standardController sc = null;
	public list<SelectOption> salespersonOptions {get; set;}

	public EditOpportunity (ApexPages.StandardController controller) {
		this.opp = (SLXOpportunity__c)controller.getRecord();
		
		salespersonOptions = new list<SelectOption>{new SelectOption('','--None--')};
        for (User u : [SELECT Id, Name FROM User WHERE isActive = true AND UserRole.name IN ('Sales Manager Assistant Digital Strategy', 'Digital Strategy Sales', 'Digital Strategy Manager', 'Sales Manager Assistant SLX', 'Sales Manager Assistant GMT', 'SLX Sales') ]) {
            salespersonOptions.add( new SelectOption(u.Id, u.Name));
        }
	}
	
	public PageReference loadContactInfo() {
		if (opp.account__c != null) {
			Account acc = [select Id, Name, Website from Account where id =: opp.Account__c limit 1];
			opp.Website__c = acc.Website;
			
			try{
	            Contact c = [select Name, Phone, Email from Contact where Title = 'Marketing' and Account.Name =: acc.Name limit 1];
	   			opp.Contact_Name__c = c.Name;
	   			opp.Contact_Phone_Number__c = c.Phone;
	   			opp.Contact_Email__c = c.Email;
	        } catch (Exception e) {
	            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Unable to load contact details');
	            ApexPages.addMessage(myMsg);
	        }
	        
	        try{
	   			Sign_Up__c signup = [select id, Daily_Budget__c from Sign_Up__c where Account__c =: acc.Id limit 1];
	   			opp.Adwords_Daily_Budget__c = signup.Daily_Budget__c;
	        } catch (Exception e) {
	            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Unable to load sign up details');
	            ApexPages.addMessage(myMsg);
	        }
		}
        	   			
        return null;
	}
	
	public PageReference save () {
		try{
			Account acc = [SELECT Id, Name FROM Account WHERE id =: opp.Account__c LIMIT 1];
			User salesperson = [SELECT Name FROM User WHERE Id=:opp.OwnerId LIMIT 1];
			opp.Name = acc.Name;
			opp.Send_to_Salesperson__c = salesperson.Name;
			upsert(opp);
		}
		catch (Exception e){
			ApexPages.addMessages(e);
			return null;
		}
		string s = '/' + ('' + opp.get('Id')).subString(0, 3);
		return new Pagereference(s);
	}
	
	public PageReference save_new () {
		try{
			Account acc = [SELECT Id, Name FROM Account WHERE id =: opp.Account__c LIMIT 1];
			User salesperson = [SELECT Name FROM User WHERE Id=:opp.OwnerId LIMIT 1];
			opp.Name = acc.Name;
			opp.Send_to_Salesperson__c = salesperson.Name;
			upsert(opp);
		}
		catch (Exception e){
			ApexPages.addMessages(e);
			return null;
		}
		string s = '/' + ('' + opp.get('Id')).subString(0, 3) + '/e?';
		return new Pagereference(s);
	}

	
	public static testMethod void test1(){
		Account acc = new Account();
		acc.Name = 'Test Account111';
		acc.Company__c = 'SponsoredLinX';
		acc.username__c = 'test11d11@test.com';
		acc.password__c = 'test';
		insert acc;
		
		Contact contact = new Contact();
		contact.AccountId = acc.Id;
		contact.title = 'Marketing';
		contact.FirstName = 'bob';
		contact.LastName = 'down';
		contact.Email = 'down@bob.com';
		contact.MailingStreet='sdfasfsf\r\nsdfsdfdsf\r\nsdfsdfsf\r\ndsdfsdf';
		contact.MailingCity='brisbane';
		contact.MailingPostalCode='4500';
		contact.MailingState='Queensland';
		contact.MailingCountry='Australia';
		insert contact;

		Test.startTest();
		SLXOpportunity__c o = new SLXOpportunity__c();
		ApexPages.standardController controller = new ApexPages.standardController(o);
		EditOpportunity oppCon = new EditOpportunity(controller);
		o.Account__c = acc.id;
		o.Product_Type__c = 'Adwords Management';
		o.Send_to_Salesperson__c = 'Gretel Phillips';
		o.website__c = 'www.test.com';
		oppCon.loadContactInfo();
		controller.save();
		Test.stopTest();
	}
	
	public static testMethod void test2(){
		Account acc = new Account();
		acc.Name = 'Test Account111';
		acc.Company__c = 'SponsoredLinX';
		acc.username__c = 'test11d11@test.com';
		acc.password__c = 'test';
		insert acc;

		Test.startTest();
		SLXOpportunity__c o = new SLXOpportunity__c();
		ApexPages.standardController controller = new ApexPages.standardController(o);
		EditOpportunity oppCon = new EditOpportunity(controller);
		o.Account__c = acc.id;
		o.Product_Type__c = 'Adwords Management';
		o.Send_to_Salesperson__c = 'Gretel Phillips';
		o.website__c = 'www.test.com';
		oppCon.loadContactInfo();
		oppCon.save_new();
		Test.stopTest();
	}
}