src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Adwords_Product__c</fullName>
        <label>Adwords Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Converto_Product__c</fullName>
        <label>Converto Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facebook_Product__c</fullName>
        <label>Facebook Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optimised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SEO_Product__c</fullName>
        <label>SEO Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Price__c</fullName>
        <formula>IF(ISPICKVAL(Recurring_Period__c, &apos;Weekly&apos;), Product_Price__c*52/12, 
IF(ISPICKVAL(Recurring_Period__c, &apos;Fortnightly&apos;), Product_Price__c*26/12, 
IF(ISPICKVAL(Recurring_Period__c, &apos;Yearly&apos;), Product_Price__c/12, 
Product_Price__c)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>cancelat__c</fullName>
        <label>cancelat</label>
        <type>Date</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Adwords_Product__c</fullName>
        <label>Adwords Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Converto_Product__c</fullName>
        <label>Converto Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Facebook_Product__c</fullName>
        <label>Facebook Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optimised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SEO_Product__c</fullName>
        <label>SEO Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Social_Media_Product__c</fullName>
        <label>Social Media Product</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/pardotContactBatch.cls
global class pardotContactBatch implements Database.batchable<Account> {
	global Iterable<Account> start(Database.batchableContext info) {    
    	return new pardotContactIterator();  
  	}
  	
  	global void execute(Database.batchableContext info, List<Account> scope){
  		for(Account account : scope){
  			try {
  				Contact contact = new Contact();
  				Contact contacttest = new Contact();
		        try{
		        	contact = [SELECT Id, Adwords_Product__c, Facebook_Product__c, SEO_Product__c, Converto_Product__c, Social_Media_Product__c, Title, FirstName, LastName, Email, Birthdate, Phone, Fax, MobilePhone,MailingStreet,MailingCity,MailingState,MailingCountry  FROM Contact WHERE AccountId =: account.Id AND Title = 'Marketing' limit 1];
		        }
		        catch(Exception e){
		        	system.debug(e);
		        }
		        
		        System.debug('Contact Record: '+contact); 
		        
		        Boolean applyCancelledTag = false;
		        Map<String, String> infusionMap = new Map<String, String>();
		        
		        String company_name = account.Name;

				String specialChars = '&|^|@';   // in this string, write all the special chars you want to get ride of, pipe separated
				for(integer i=0; i<specialChars.split('|').size(); i++){
				   company_name = company_name.replace(specialChars.split('|')[i], '');
				}
				System.debug('Company Name is >>>>>>>>>>>>>>>>>>>>>>>>>>>>> ' + company_name);
		        
		        try {
					String productname = '';
					Boolean adsActive    = false;
					Boolean adsPaused    = false;
					Boolean adsCancelled = false;
					
					Boolean seoActive    = false;
					Boolean seoPaused    = false;
					Boolean seoCancelled = false;
					
					Boolean facebookActive    = false;
					Boolean facebookPaused    = false;
					Boolean facebookCancelled = false;
					
					Boolean convertoActive    = false;
					Boolean convertoPaused    = false;
					Boolean convertoCancelled = false;
					
					Boolean socialActive    = false;
					Boolean socialPaused    = false;
					Boolean socialCancelled = false;
					
					List<Date> cancelledDates = new List<Date>(); 
					
					String package_name = '';
					
					for(Account_Product__c product : [SELECT Id,Name,Product_Status__c, Monthly_Price__c, cancelat__c FROM Account_Product__c WHERE Account__c=:account.Id AND (Recurring_Period__c !='N/A' AND Recurring_Period__c != '')]) {
						System.debug('Product Record: '+product);
						productname = '';
						productname = product.Name.toLowerCase();
						if(productname.contains('adwords')) {
							if(product.Product_Status__c == 'Active'){
								adsActive = true;
								if(product.Monthly_Price__c <= 343 ){
									package_name = 'Standard';
								}else if(product.Monthly_Price__c <= 386){
									package_name = 'Optimised';
								}else if(product.Monthly_Price__c <= 429){
									package_name = 'Premium';
								}
							}else if(product.Product_Status__c == 'Paused'){
								adsPaused = true;
							}else if(product.Product_Status__c == 'Cancelled'){
								adsCancelled = true;
								cancelledDates.add(product.cancelat__c);
							}
							
						} else if(productname.contains('seo')) {
									if(product.Product_Status__c == 'Active'){
										seoActive = true;
									}else if(product.Product_Status__c == 'Paused'){
										seoPaused = true;
									}else if(product.Product_Status__c == 'Cancelled'){
										seoCancelled = true;
									}
									
								}
						else if(productname.contains('facebook')) {
									if(product.Product_Status__c == 'Active'){
										facebookActive = true;
									}else if(product.Product_Status__c == 'Paused'){
										facebookPaused = true;
									}else if(product.Product_Status__c == 'Cancelled'){
										facebookCancelled = true;
									}
							
						}else if(productname.contains('convertopages')) {
							System.debug('Product Name Contains ConvertoPages');
									if(product.Product_Status__c == 'Active'){
										convertoActive = true;
									}else if(product.Product_Status__c == 'Paused'){
										convertoPaused = true;
									}else if(product.Product_Status__c == 'Cancelled'){
										convertoCancelled = true;
									}
						}
						else if(productname.contains('social media')) {
							System.debug('Product Name Contains Social Media');
									if(product.Product_Status__c == 'Active'){
										socialActive = true;
									}else if(product.Product_Status__c == 'Paused'){
										socialPaused = true;
									}else if(product.Product_Status__c == 'Cancelled'){
										socialCancelled = true;
									}
						}
							
					}	
					if(adsActive){
						contact.Adwords_Product__c = 'Active';
					}else if(adsPaused){
						contact.Adwords_Product__c = 'Paused';
					}else if(adsCancelled){
						contact.Adwords_Product__c = 'Cancelled';
					}
					
					contact.Package_Name__c = package_name;
					if(seoActive){
						contact.SEO_Product__c = 'Active';
					}else if(seoPaused){
						contact.SEO_Product__c = 'Paused';
					}else if(seoCancelled){
						contact.SEO_Product__c = 'Cancelled';
					}
					
					if(facebookActive){
						contact.Facebook_Product__c = 'Active';
					}else if(facebookPaused){
						contact.Facebook_Product__c = 'Paused';
					}else if(facebookCancelled){
						contact.Facebook_Product__c = 'Cancelled';
					}
					
					if(convertoActive){
						contact.Converto_Product__c = 'Active';
					}else if(convertoPaused){
						contact.Converto_Product__c = 'Paused';
					}else if(convertoCancelled){
						contact.Converto_Product__c = 'Cancelled';
					}
					
					if(socialActive){
						contact.Social_Media_Product__c = 'Active';
					}else if(socialPaused){
						contact.Social_Media_Product__c = 'Paused';
					}else if(socialCancelled){
						contact.Social_Media_Product__c = 'Cancelled';
					}
					
					if(adsActive || seoActive || facebookActive || convertoActive || socialActive){
						account.Active__c = true;
					}else{
						account.Active__c = false;
					}
					
				} catch(Exception e) {
					System.debug('Error fetching product record');
					System.debug('EXCEPTION: '+e.getMessage());
				}
				

			  update account;
			  update contact;
		      
		      } catch(Exception e) {
			        System.debug('Error fetching contact record');
			        System.debug('EXCEPTION: '+e.getMessage());
		      }
		}
		
	}
	global void finish(Database.batchableContext info){
		
   		}
}