src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Infusionsoft_id__c</fullName>
        <label>Infusionsoft_id</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Psycho__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Do not send any email to this client once marked as Do Not Contact</description>
        <inlineHelpText>Do not send any email to this client once marked as Do Not Contact</inlineHelpText>
        <label>Do Not Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/pardotContactIterable.cls
global class pardotContactIterable implements Iterator<Account>{
	List<Account> accounts = new List<Account>();
	Integer i {get;set;}
	
	public pardotContactIterable(){
		this.i = 0;
		try{
		
			this.accounts = [select Id, Name, Owner.Name, Payment_Option__c, Website, infusionsoft_Id__c, Active__c, Psycho__c FROM Account where Type != 'Employee'];
			
			}catch(Exception e){
				System.debug(e.getMessage());
			}
	}
	global boolean hasNext() {
	    if(this.i >= this.accounts.size()) 
	        return false; 
	    else 
	        return true;  
    }
    
	global Account next() {
		
		return this.accounts[this.i++];  
	}
}