src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Web_Questionnaire__c</fullName>
        <label>Web Questionnaire</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reminded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Projects__c.object
<CustomObject>
    <description>A professional services engagement that tracks all related Resources and Project details.</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Product__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Google Adwords</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
                <color>#419249</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Web Design</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Web &amp; SEO</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Work Web</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Additional SEO Work</fullName>
                <color>#333399</color>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Directory Listings SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Visibility SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile &amp; Web Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admob Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+ Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConvertoPages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explainer Videos</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sign_Up__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sign Up</label>
        <referenceTo>Sign_Up__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_by__c</fullName>
        <label>Sold by</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Web_Content__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Web Contents</relationshipLabel>
        <relationshipName>Web_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Questionnaire Email</description>
        <inlineHelpText>Email Address</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_Projects__c</referenceTo>
        <relationshipLabel>Web Contents</relationshipLabel>
        <relationshipName>Web_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Web Content</label>
    <nameField>
        <displayFormat>WC-{00000}</displayFormat>
        <label>Web Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuestionnaireController.cls
public with sharing class QuestionnaireController {

	public Web_Content__c obj{get;set;}
    public String step{get;set;}
    public boolean isTest{get;set;}
    public final String MSG_ACCOUN_IS_BLANK = 'Client/Project ID is required';
    public final String MSG_INPUT_VALUES_IS_INVALID = 'Input value is invalid';

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public QuestionnaireController() {
        System.debug('dsdsdsadasdas 0');
        this.obj = new Web_Content__c();
        step = '1';
        System.debug('dsdsdsadasdas 00');
    }

    public PageReference save() {
        String msg ='';

        try{
            String accountId =ApexPages.currentPage().getParameters().get('accId');
            String signupId =ApexPages.currentPage().getParameters().get('projectId'); // signup
            System.debug('accountId' + accountId);
            System.debug('signupId' + signupId);
            //validate params
            
            if(accountId== null){                
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,MSG_ACCOUN_IS_BLANK));
                return null;
            }

            //validate input values            
            //if(isInputInvalid()){
            //    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,MSG_INPUT_VALUES_IS_INVALID));
            //    return null;                
            //}


            // update Project questionnaire status
            String projectId ='';
            Sign_Up__c signup = [SELECT Id, Web_Questionnaire__c , Email__c, Account__c,Account__r.Name,Account__r.Email__c, (SELECT Id FROM Projects__r) 
                     FROM Sign_Up__c 
                     WHERE Id =:signupId];
            
            /*
            // get project ID, if not exist (for any SEO Content Pack signup created before 30/8/2018), then create the project base on sign up information
            if (signup.Projects__r!=null){
                for (SFDC_Projects__c item: signup.Projects__r){
                    if((item.Name!= null) && (item.Name.containsIgnoreCase('Content Pack'))){
                        projectId = ''+ item.id;
                    }
                }
                system.debug('QuestionnaireController: 1 : ' + projectId);

            } 

            if((projectId == null) || (projectId == '')){
                system.debug('QuestionnaireController: 2 : ' + projectId);
                SFDC_Projects__c newProject = new SFDC_Projects__c();
                newProject.name = signup.Account__r.Name + ' Content Pack';
                newProject.Account__c = signup.Account__c;                    
                newProject.Project_Type__c ='SEO Content Pack';
                newProject.Sign_Up__c = signup.Id;
                newProject.Sold_by__c = 'unknown';
                newProject.Email__c = signup.Account__r.Email__c; 
                insert newProject;  
                projectId = newProject.id;             
                system.debug('QuestionnaireController: 2 : ' + projectId);
            }

            */
            signup.Web_Questionnaire__c = 'Completed';
            update signup;
            system.debug('QuestionnaireController: 3 : ' + signup.Id);         


            // create new Questionnaire            
            this.obj.Sign_Up__c = signupId;            
           // this.obj.Project__c = projectId;
            this.obj.Email__c   = signup.Email__c;
            //this.obj.Account__c = signup.Account__c;
            //this.obj.Account_Product__c = productId;            
            insert this.obj;
            system.debug('QuestionnaireController: 4 : ');         

            //move to confirm page
            step = '2';
            System.debug('insert');

            return null;
        }catch(Exception ex) {
            system.debug('QuestionnaireController: ' + ex.getMessage() );
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
            return null;
        }        
    }


    public boolean isInputInvalid(){
        return false;
    }

}