src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the company which manages this account</description>
        <inlineHelpText>the company which manages this account</inlineHelpText>
        <label>BJB Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_CVN__c</fullName>
        <label>Card CVN</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Month_Expiry__c</fullName>
        <label>Card Month Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Number_Masked__c</fullName>
        <label>Card Number Masked</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Token__c</fullName>
        <label>Card Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Year_Expiry__c</fullName>
        <label>Card Year Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GST__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees__c</fullName>
        <label>Number of Employees</label>
        <picklist>
            <picklistValues>
                <fullName>0 - 10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 - 20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 - 50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50 - 100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SystemVars__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Miscellaneous system variables</description>
    <fields>
        <fullName>salt__c</fullName>
        <label>salt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>System Vars</label>
</CustomObject>

src/classes/ClientPanelAccountBilling.cls
public with sharing class ClientPanelAccountBilling {

	public Account acc {get; set;}
    public String paymentType {get; set;}
    public CardDetails cardDetails {get; set;} {cardDetails = new CardDetails();}

    private Id accId;

    // Constructor
    public ClientPanelAccountBilling() {
        this.acc = new Account();

        // Set defaults
        this.paymentType = 'Credit Card';

        // Load details from existing account if the accountid and uid were passed in the URL or cookies
        try{
            this.loadAccount();
        } catch (Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
    }

    // Load account from cookies
    private void loadAccount(){

        // Load the salt from system vars. This should match the salt used to generate the signature in clientpanel.
        String salt = SystemVars__c.getValues('main').salt__c;

        Id reqAccountId = ApexPages.currentPage().getParameters().get('accountid');
        String reqSig = ApexPages.currentPage().getParameters().get('sig');

        if ( reqAccountId == null ){
            throw new customException('No account specified');
        }

        Account[] existingAccounts = [
        SELECT Id, Name, username__c, Unique_Id__c, Industry, Number_of_Employees__c, Name_On_Card__c, Card_Number__c, Card_Number_Masked__c, Card_Month_Expiry__c, Card_Year_Expiry__c, Card_CVN__c, Card_Token__c, Company__c, Website, BillingStreet, BillingCity, BillingPostalCode, BillingState, Phone, GST__c, BJB_Company__c 
        FROM Account 
        WHERE id = :reqAccountId 
        LIMIT 1];

        if (existingAccounts.size() == 0) {
            throw new customException('Could not find account');
        }

        Account checkAccount = existingAccounts[0];

        // Generate the signature for this account and compare it to the one passed in the request
        String sigData = checkAccount.Id + checkAccount.username__c + salt;
        String accountSig = EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueof(sigData)));

        system.debug('accountSig: ' + accountSig);

        if (reqSig == accountSig){
            this.acc = checkAccount;

            // Pad the card month with leading zero if it doesn't already have it.
            if (this.acc.Card_Month_Expiry__c != null){
                this.acc.Card_Month_Expiry__c = this.acc.Card_Month_Expiry__c.leftPad(2).replaceAll(' ', '0');
            }

            // Populate the card number field with the previous masked value from the account
            this.cardDetails.Card_Number = this.acc.Card_Number_Masked__c;

            // Important: We cannot have an Id on the account when the VF page is displayed because Guest user licenses don't have edit
            // access to accounts, so the whole record becomes readonly on the VF page. VF uses the Id field to determine whether it's an existing record.
            // We'll store the Id in a private variable so we can add it back to the object before saving it.
            this.accId = this.acc.Id;
            this.acc.Id = null;
        } else {
            throw new customException('Could not verify this account');
        }
    }

    // Get the address that this checkout should use for the wrapper around the iframe
    public String getSiteWrapperURL(){
        // Use crankit even for live site, prior to launch.
        if (utility.runningInASandbox()){
            return 'https://clientpanel.staging.sponsoredlinx.com.au';
        } else {
            return 'https://clientpanel.sponsoredlinx.com.au';
        }
    }

    // Get options for month dropdown
    public List<SelectOption> getMonthOptions() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','month'));

        for( Schema.PicklistEntry pickListVal : Account.Card_Month_Expiry__c.getDescribe().getPicklistValues()){
            options.add(new SelectOption(pickListVal.getValue(), pickListVal.getLabel()));
        }

        return options;
    }

    // Get options for credit card year dropdown
    public List<SelectOption> getCardYearOptions() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','year'));

        for( Schema.PicklistEntry pickListVal : Account.Card_Year_Expiry__c.getDescribe().getPicklistValues()){
            options.add(new SelectOption(pickListVal.getValue(), pickListVal.getLabel()));
        }

        return options;
    }

    // =============================================================
    // Actions
    // =============================================================

    // Index page
    public PageReference index() {
        return null;
    }

    // Submit "update billing details" page.
    public PageReference submitUpdateBilling() {
        try {
            // Generate a token (this also masks the card number so it won't display on the page)
            paymentGateway pay = new paymentGateway();
            pay.updateAccountToken(this.acc, this.cardDetails.Card_Number, this.cardDetails.Card_CVN);

            // Update the account
            // Important: We cannot have an Id on the account when the VF page is displayed because Guest user licenses don't have edit
            // access to accounts, so the whole record becomes readonly on the VF page. VF uses the Id field to determine whether it's an existing record.
            acc.Id = this.accId;
            update this.acc;
            acc.Id = null;

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Thank you. Your card details have been updated'));
        } catch (Exception e) {
            // Notify sysadmin
            string submitError = 'Error: ' + e.getMessage() + '. On ' + e.getStackTraceString();
            system.debug(submitError);
            Utility.notifySysadmin('Error in submitUpdateBilling', submitError);
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Sorry, an error occurred while updating your payment details. ' + e.getMessage() ));
        }

        return null;
    }
}