src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sign_Up_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sign Up</label>
        <referenceTo>Sign_Up__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Projects__c.object
<CustomObject>
    <description>A professional services engagement that tracks all related Resources and Project details.</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account_Product__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sign_Up__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sign Up</label>
        <referenceTo>Sign_Up__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Test__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Test</label>
        <type>Checkbox</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/signup.cls
global class signup {
    WebService static void changeSignupOwner(Id signupID, Id userID) {
        Sign_Up__c signupRec = [SELECT Id,Account__c FROM Sign_Up__c WHERE Id =:signupID];
        Account signupAcc = [SELECT Id FROM Account WHERE Id=:signupRec.Account__c];
        signupRec.OwnerId = userID;
        signupAcc.OwnerId = userID;
        update signupRec;
        update signupAcc;   
        List<Account_Product__c> accountproducts = [SELECT Id FROM Account_Product__c WHERE Sign_Up_del__c =: signupID];
        for (Account_Product__c accprod : accountproducts) {
            accprod.OwnerId = userID;                   
        }
        update accountproducts;
    }

    WebService static void changeSEOSignupOwner(Id signupID, Id userID) {
        Sign_Up__c signupRec = [SELECT Id, Account__c FROM Sign_Up__c WHERE Id =:signupID];
        Account signupAcc = [SELECT Id, OwnerID FROM Account WHERE Id=:signupRec.Account__c];
        signupRec.OwnerId = userID;
        
        update signupRec;
         
        List<Account_Product__c> accountproducts = [SELECT Id FROM Account_Product__c WHERE Sign_Up_del__c =: signupID];
        for (Account_Product__c accprod : accountproducts) {
            accprod.OwnerId = userID;                   
        }
        List<Account_Product__c> aps = [SELECT Id FROM Account_Product__c WHERE Account__c =: signupAcc.Id];
        if (aps.size() <=2){
          signupAcc.OwnerId = userID;
          update signupAcc;  
        } else {
            if(signupAcc.OwnerID != userID){
                AccountShare share = new AccountShare();
                share.userorgroupid = userID;
                share.accountid = signupAcc.Id;
                share.accountaccesslevel = 'Read';
                share.OpportunityAccessLevel = 'None';
                share.CaseAccessLevel = 'None';
                upsert share;
            }
        }
        update accountproducts;
        
        // SEO Project
        List<SFDC_Projects__c> seoprojects = [SELECT Id FROM SFDC_Projects__c WHERE Sign_Up__c =: signupID];
        for (SFDC_Projects__c seoproject : seoprojects) {
            seoproject.OwnerId = userID;                   
        }
        update seoprojects;
    }


    public static testMethod void signupTest() {
        Test.startTest();
        
        Account newAcc = new Account(name='yogi bear acc');
        insert newAcc;
        
        Sign_Up__c signupacc = new Sign_Up__c(name='yogi bear');
        signupacc.Account__c = newAcc.Id;
        signupacc.Is_Test__c = true;
        insert signupacc;
        
        Account_Product__c accprod = new Account_Product__c();
        accprod.Name = 'Test Product';
        accprod.Account__c = newAcc.Id;
        accprod.Sign_Up_del__c = signupacc.Id;
        accprod.Product_Price__c = 33.45;
        accprod.Description__c = 'test decription';
        
        User useracc = [SELECT Id FROM User WHERE Name='Ben Bradshaw' AND IsActive = true][0];
        
        signup.changeSignupOwner(signupacc.id,useracc.id);
        Test.stopTest();
    }
}