src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Card_CVN__c</fullName>
        <label>Card CVN</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Month_Expiry__c</fullName>
        <label>Card Month Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Year_Expiry__c</fullName>
        <label>Card Year Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Card_CVN__c</fullName>
        <label>Card CVN</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Month_Expiry__c</fullName>
        <label>Card Month Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Card_Year_Expiry__c</fullName>
        <label>Card Year Expiry</label>
        <picklist>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLX_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SLX Product</label>
        <referenceTo>SLX_Product__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Invoice</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkout_Site__c</fullName>
        <label>Checkout Site</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Gateway__c</fullName>
        <globalPicklist>Payment_Gateways</globalPicklist>
        <label>Payment Gateway</label>
        <type>Picklist</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <formula>TEXT(Account.Payment_Option__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Option</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <displayFormat>CN{0000000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PaymentGateway__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Payment Gateway</description>
    <fields>
        <fullName>Access_Code__c</fullName>
        <label>Access Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MerchantURL__c</fullName>
        <label>MerchantURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation_ID__c</fullName>
        <description>Operation ID</description>
        <inlineHelpText>Operation ID</inlineHelpText>
        <label>Operation ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Gateway</label>
</CustomObject>

src/classes/batchPaymentsProcessTest.cls
@isTest
private class batchPaymentsProcessTest {
	
	@istest
    public static void testbatchPaymentsProcess() {

        // Load payment gateway config
        // Eway2
        insert new PaymentGateway__c(
            Name                = 'Eway Rapid SLX AU',
            MerchantURL__c      = 'https://example.com',
            Access_Code__c      = 'exampleaccesscode',
            Password__c         = 'examplepassword'
        );

        // Commweb 1
        insert new PaymentGateway__c(
            Name                = 'Sponsoredlinx NZ',
            MerchantURL__c      = 'https://example.com',
            Access_Code__c      = 'exampleaccesscode',
            Operation_ID__c     = 'exampleopid',
            Password__c         = 'examplepassword'
        );

        insert new PaymentGateway__c(
            Name                = 'Sponsoredlinx NZ Test',
            MerchantURL__c      = 'https://example.com',
            Access_Code__c      = 'exampleaccesscode',
            Operation_ID__c     = 'exampleopid',
            Password__c         = 'examplepassword'
        );

        // Commweb2
        insert new PaymentGateway__c(
            Name                = 'Commweb GMT NZ',
            MerchantURL__c      = 'https://example.com',
            Access_Code__c      = 'exampleaccesscode',
            Operation_ID__c     = 'exampleopid',
            Password__c         = 'examplepassword'
        );

        // Setup companies
        Company__c company = new Company__c(
            Name = 'Get More Traffic New Zealand',
            Business_Name__c = 'GMT New Zealand',
            Checkout_Site__c = 'checkout_GMT',
            Payment_Gateway__c = 'Commweb2',
            CurrencyIsoCode  = 'NZD'
        );
        insert company;

		Account a = new Account();
	    a.Name = 'TestAccount';
	    a.username__c           = 'username';
	    a.password__c           = 'psw';
	    a.Payment_Option__c     = 'Other';
	    a.Card_Year_Expiry__c   = '2014';
	    a.Card_Number__c        = '123456789';
	    a.Card_Month_Expiry__c  = '01';
	    a.Card_CVN__c 			= '123';
	    a.Name_On_Card__c       = 'Test';
		a.Send_Invoice__c       = true;
		a.CurrencyIsoCode 		='NZD';
		insert a;

        List<Contact> newContacts = new List<Contact>();
        for (String contact_type : new List<String> {'Billing','Reports','Marketing'}){
            newContacts.add( 
                new Contact(
                    FirstName         = 'Steve',
                    LastName          = 'Existingclient',
                    AccountId         = a.Id,
                    Phone             = '0407040404',
                    Email             = 'test@example.com',
                    Title             = contact_type
                )
            );
        }
        insert newContacts;

		SLX_Product__c p = new SLX_Product__c();
	    p.company_name__c = 'Get More Traffic New Zealand';
	    p.name = 'gmt';
	    p.product_price__c = 100;
	    p.CurrencyIsoCode = 'NZD';
	    insert p;
	    
	    Account_Product__c ap = new Account_Product__c();
	    ap.Recurring_Frequency__c = 1;
	    ap.Product_Price__c = 20;
	    ap.Last_Invoice_Date__c = Date.today().addMonths(-1);
	    ap.Recurring_Period__c ='Weekly';
	    ap.Payment_Option__c = 'CommWeb';
	    ap.Account__c = a.Id;
	    ap.SLX_Product__c = p.id;
	    ap.CurrencyIsoCode ='NZD';
	    insert ap;
	    
	    Credit__c credit = new Credit__c();
	    credit.Account_Product__c = ap.Id;
	    credit.Amount__c = 50;
	    credit.Credit_Used__c = 0;
	    insert credit;
	    
	    Map<String, Integer> dueDays = new Map<String, Integer>();
	    dueDays.put('Today', 0);
	    dueDays.put('3 Day', -3);
	    dueDays.put('5 Day', -5);
	    dueDays.put('9 Day', -9);
	    dueDays.put('13 Day', -13);
	    
	    Invoice__c[] insertInvoices = new List<Invoice__c>();
	    for(String period : dueDays.keyset()) {
	    	Invoice_Batch__c batch = new Invoice_Batch__c();
		    batch.Name = 'GMT NZ ' + DateTime.now().format('EEEE yyyy-MM-dd') + ' ' + period + ' Invoice Batch';
		    batch.Batch_Date__c = Date.today();
		    batch.Batch_Type__c = 'Invoices';
		    batch.Status__c = 'Batch Approved';
		    batch.Batch_Processed__c = 'No';
		    batch.Batch_Period__c = period;
		    insert batch;
		    
		    Invoice__c invoice = new Invoice__c();
	        invoice.Account__c = a.Id;
	        invoice.Account_Product__c = ap.Id;
	        invoice.Amount_Due__c =20;
	        invoice.CurrencyIsoCode ='NZD';
	        invoice.Amount_Paid__c = 0;
	        invoice.Due_Date__c  = Date.today().addDays(dueDays.get(period));
	        invoice.Issue_Date__c  = invoice.Due_Date__c;
	        invoice.Reference__c = String.valueof(dueDays.get(period));
	        invoice.Invoice_Number__c = invoice.Reference__c;
	        invoice.Payment_Option__c = 'Commweb';
	        invoice.Status__c = 'AUTHORISED';
	        invoice.Invoice_Batch__c = batch.Id;
	        insertInvoices.add(invoice);
	    }
	    insert insertInvoices;
	    
	    Test.startTest();
	    // Set to test mode so it doesn't do webservice callouts
	    batchPaymentsProcess.isTest = true;
		for(string period : dueDays.keyset()) {
			batchPaymentsProcess batch = new batchPaymentsProcess(period, 'Get More Traffic New Zealand');
			ID batchId = Database.executeBatch(batch,10);
		}
	    Test.stopTest();
    }
	
}