src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_Email__c</fullName>
        <label>Adwords Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Adwords_ID__c</fullName>
        <label>Adwords ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Category</label>
        <referenceTo>Product_Category__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Frequency__c</fullName>
        <description>The frequency of this product to be billed</description>
        <label>Recurring Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLX_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SLX Product</label>
        <referenceTo>SLX_Product__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sign_Up_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sign Up</label>
        <referenceTo>Sign_Up__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Sign_Up__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sign Up</label>
        <referenceTo>Sign_Up__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_Category__c.object
<CustomObject>
    <label>Product Category</label>
    <nameField>
        <label>Product Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_Email__c</fullName>
        <description>Email address belongs to Adwords account linked to this signup</description>
        <label>Adwords Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Adwords_ID__c</fullName>
        <description>The ID of Adwords account linked with this signup.
ID format: xxx-xxx-xxxx</description>
        <label>Adwords ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SLX_Product__c.object
<CustomObject>
    <fields>
        <fullName>product_price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>recurring_period__c</fullName>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BJB Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/completeSignup.cls
public with sharing class completeSignup {

	public class SaveAdwordsDetailsResult {
		Boolean status;
		Account_Product__c result;
		String message;
	}

	/*
	*	Save Adwords id and email into the correct recurring product
	*	@param Id signup_id
	*	@param String google_id
	*	@param String google_email
	*	@return SaveAdwordsDetailsResult
	*/
	public SaveAdwordsDetailsResult saveAdwordsDetails(Id signup_id, String adwords_id, String adwords_email) {
		SaveAdwordsDetailsResult return_result = new SaveAdwordsDetailsResult();
		List<Account_Product__c> account_products = [SELECT Name, Description__c, Adwords_ID__c, Adwords_Email__c, Account__c, Recurring_Period__c, Recurring_Frequency__c, Product_Status__c, Product_Category__c, SLX_Product__c, Product_Category__r.Name, SLX_Product__r.Name FROM Account_Product__c WHERE Sign_Up_del__c =: signup_id];

		if(account_products.size() > 0) {
			System.debug('Found some account products');
			// loop for each account products related to current signup
			for (Account_Product__c account_product : account_products) {
				System.debug('Account product: ' + account_product);
				// check if current product is a recurring and adwords related
				if(account_product.Recurring_Frequency__c > 0) {
					System.debug('This account product is Recurring');
					Boolean valid = false;
					List<Product_Category__c> categories = [SELECT Id, Name FROM Product_Category__c WHERE Id =: account_product.Product_Category__c];
					Product_Category__c category;
					List<SLX_Product__c> products = [SELECT Id, Name FROM SLX_Product__c WHERE Id =: account_product.SLX_Product__c];
					SLX_Product__c product;

					// first check category of this product
					if(categories.size() > 0) {
						category = categories[0];
						if(category.Name == 'Adwords Management') {
							valid = true;
							System.debug('This account product is in Adwords category');
						}
					}
					// or second check if current product has correct slxproduct
					else if(products.size() > 0) {
						product = products[0];
						if(product.Name == 'Adwords Standard Management' || product.Name == 'Adwords Optimised Management' || product.Name == 'Adwords Premium Management') {
							valid = true;
							System.debug('This account product has a link to Adwords in SLXProduct');
						}
					}

					if(valid) {
						System.debug('Account product SLX Product name: ' + account_product);
						// now we know if this account products is for recurring adwords
						// we check if it's active. then save the adwords details, before
						// setting the return object.
						if(account_product.Product_Status__c == 'Active') {
							System.debug('Found active adwords account product: ' + account_product.Name);
							try {
								account_product.Adwords_ID__c = adwords_id;
								account_product.Adwords_Email__c = adwords_email;
								update account_product;
								System.debug('Account Product UPDATED');
								return_result.status = true;
								return_result.result = account_product;
								return_result.message = 'Found adwords-related account product and Adwords details have been saved';
								return return_result;
							}
							catch (Exception e) {
								return_result.status = false;
								return_result.result = null;
								return_result.message = 'Failed updating account product: ' + e;
								System.debug('Exception: ' + e);
								return return_result;
							}
						}
					}
					else {
						System.debug('This product is not related to Adwords: ' + product);
					}
				}
			}
		}

		// if there is no correct account product we set the error message
		return_result.status = false;
		return_result.result = null;
		return_result.message = 'Can not find a correct account product to this signup';
		System.debug('Can not find a suitable account product');

		return return_result;
	}
	public static testMethod void completeSignupTest() {
		Test.StartTest();
		
		Account acc = new Account(name='test',company__c='test',username__c='test',password__c='test');
		insert acc;
		
		Contact con = new Contact(FirstName='test',LastName='test',Title='Billing',AccountId=acc.id);
		con.MailingStreet='sdfsadfsa\r\ndfsafa\r\nsfsdfsdfs\r\ndfsdfs\r\ndfsdf';
		con.MailingCity='Brisbane';
		con.MailingState='queensland';
		con.MailingPostalCode='4444';
		con.MailingCountry='Australia';
		insert con;
		
		SLX_Product__c product = new SLX_Product__c(Name='Adwords Standard Management', Product_Price__c = 79.00);
		insert product;
		
		Product_Category__c category1 = new Product_Category__c(Name='Adwords Management');
		insert category1;
		
		Sign_Up__c signup = new Sign_Up__c(Account__c = acc.Id, Name = 'test Signup');
		insert signup;
		
		Account_Product__c ap1 = new Account_Product__c(Account__c = acc.Id, Name = 'Adwords Optimised Management',Recurring_Frequency__c=2, SLX_Product__c = product.Id, Product_Category__c = category1.Id, Recurring_Period__c='Weekly', Product_Status__c='Active', Product_Price__c = 76.00, Sign_Up_del__c = signup.Id);
		insert ap1;
		
		completeSignup cs = new completeSignup();
		System.debug(cs.saveAdwordsDetails(signup.Id, '345345', 'test@test.com'));
			
		Test.stopTest();
	}
	
	public static testMethod void completeSignupTest1() {
		Test.StartTest();
		
		Account acc = new Account(name='test',company__c='test',username__c='test',password__c='test');
		insert acc;
		
		Contact con = new Contact(FirstName='test',LastName='test',Title='Billing',AccountId=acc.id);
		con.MailingStreet='sdfsadfsa\r\ndfsafa\r\nsfsdfsdfs\r\ndfsdfs\r\ndfsdf';
		con.MailingCity='Brisbane';
		con.MailingState='queensland';
		con.MailingPostalCode='4444';
		con.MailingCountry='Australia';
		insert con;
		
		Sign_Up__c signup = new Sign_Up__c(Account__c = acc.Id, Name = 'test Signup');
		insert signup;
		
				
		completeSignup cs = new completeSignup();
		System.debug(cs.saveAdwordsDetails(signup.Id, '345345', 'test@test.com'));
			
		Test.stopTest();
	}
}