src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Invoice_Date__c</fullName>
        <label>Last Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <displayFormat>P{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sold_to_Pause__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sold to Pause</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>activeat__c</fullName>
        <label>activeat</label>
        <type>Date</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/activateProductStatusIterable.cls
global class activateProductStatusIterable implements Iterator<Account_Product__c> {
    
    List<Account_Product__c> activateProducts {get;set;} 
    Integer i {get;set;}
    
    public activateProductStatusIterable() {
        this.activateProducts = [SELECT Id,Name,Account__c,Product_Number__c,Product_Status__c, activeat__c, Sold_to_Pause__c, last_invoice_date__c , Last_Paid_Date__c , From_Last_Paid_Date__c, TP_Record_Id__c
                                FROM Account_Product__c 
                                WHERE activeat__c=today and Product_Status__c != 'Active'];
        this.i = 0;
    }
    global boolean hasNext() {
        if(this.i >= this.activateProducts.size()) 
            return false; 
        else 
            return true;    
    }
    global Account_Product__c next() {
        return this.activateProducts[this.i++]; 
    }
    
    public static TestMethod void test() {
        Account_Product__c ap1 = new Account_Product__c();
	 	ap1.Product_Status__c = 'Paused';
	 	ap1.name = 'ap1';
	 	ap1.activeat__c = Date.today();
	 	ap1.Product_Price__c = 55.0;
	 	insert ap1;
	 		 	
	 	Account_Product__c ap2 = new Account_Product__c();
	 	ap2.Product_Status__c = 'Paused';
	 	ap2.activeat__c = Date.today();
	 	ap2.Product_Price__c = 55.0;
	 	insert ap2;
	 	
	 	Account_Product__c ap3 = new Account_Product__c();
	 	ap3.Product_Status__c = 'Paused';
	 	ap3.activeat__c = Date.today();
	 	ap3.Product_Price__c = 55.0;
	 	insert ap3;
        
        Test.startTest();
        
        activateProductStatusIterable iter = new activateProductStatusIterable();
        iter.i = 2;
        List<Account_Product__c> aps = new List<Account_Product__c>();
        if (iter.hasNext()) {
			aps.add(iter.next());        	
        }

        Test.stopTest();
    }
    
     public static TestMethod void test1() {
        Test.startTest();
        
        activateProductStatusIterable iter = new activateProductStatusIterable();
        iter.i = 5;
        List<Account_Product__c> aps = new List<Account_Product__c>();
        if (iter.hasNext()) {
			aps.add(iter.next());        	
        }

        Test.stopTest();
    }
}