src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Package</label>
        <referenceTo>Product_Package__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLX_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SLX Product</label>
        <referenceTo>SLX_Product__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sign_Up_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sign Up</label>
        <referenceTo>Sign_Up__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <formula>ISPICKVAL(Product_Status__c, &apos;Active&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>BJB Company Name</description>
    <label>Company Name</label>
</CustomObject>

src/objects/Product_Package__c.object
<CustomObject>
    <label>Product Package</label>
    <nameField>
        <label>Product Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Package__c</fullName>
        <label>Product Package</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SLX_Product__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <picklist>
            <picklistValues>
                <fullName>AdWords</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdMob</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optimise Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instagram</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Package__c</fullName>
        <label>Product Package</label>
        <picklist>
            <picklistValues>
                <fullName>No Package</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optimised Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate BRONZE Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate SILVER Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate GOLD Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate DIAMOND Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate PLATINUM Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>350MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>450MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>600MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Starter Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Business Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Article Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Article Writing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Brand Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Platinum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local &amp; National Campaign Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local Campaign Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local Campaign + Analytics Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO National Campaign Package</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>company_name__c</fullName>
        <label>Company Name</label>
        <picklist>
            <picklistValues>
                <fullName>SponsoredLinx</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Get More Traffic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crank IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iiConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJB Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SponsoredLinX New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Get More Traffic New Zealand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>product_description__c</fullName>
        <label>Product Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>product_max_usage__c</fullName>
        <label>Product Max Usage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product_price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>product_recurring__c</fullName>
        <label>Product Recurring</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hourly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>recurring_period__c</fullName>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BJB Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/createProductList.cls
public class createProductList {
	public String product{get; set;}
	public SLX_Product__c prodobject = new SLX_Product__c();
	public Account account;
	public Sign_Up__c signup;
	public Boolean buttonIsDisabled;

	public void init() {
		this.buttonIsDisabled = true;
		Account[] accounts = [select Id, name from Account where id =:ApexPages.currentPage().getParameters().get('accid')];
		if(accounts.size() > 0) {
			this.account = accounts[0];
		}
		Sign_Up__c[] signups = [select Id FROM Sign_Up__c where Account__c =:ApexPages.currentPage().getParameters().get('accid')];
		if(signups.size() > 0) {
			this.signup	= signups[0];
		}
	}

	public List<SelectOption> getproductnames()	{
		List<SelectOption> options = new List<SelectOption>();
		List<SLX_Product__c> productlist = new List<SLX_Product__c>();
		productlist = [Select Id, Name FROM SLX_Product__c ];
		options.add(new SelectOption('--None--','--None--'));
		for (Integer j=0;j<productlist.size();j++) {
		    options.add(new SelectOption(productlist[j].Id,productlist[j].Name));
		}
		return options;
	}
	
	public void populate() {
		this.buttonIsDisabled = true;
		if (this.product != '--None--') {
			this.buttonIsDisabled = false;
			SLX_Product__c[] prodObj = [SELECT Id,Name,IsActive__c,Company_Name__c,ProductCode__c,product_description__c,Product_Family__c,product_max_usage__c,Product_Package__c,product_price__c,product_recurring__c,recurring_period__c FROM SLX_Product__c WHERE Id =:this.product];
			if(prodObj.size() > 0) {
				setprodobject(prodObj[0]);
			}
		}	
	}
	
	public Boolean getbuttonIsDisabled() {
		return this.buttonIsDisabled;
	}
	
	public Account getAccount() {
        return this.account;
    }
	
	public SLX_Product__c getprodobject() {
		return this.prodobject;	
	}	
	
	public void setprodobject(SLX_Product__c pObj) {
		this.prodobject = pObj;
	}
	
	public void addproduct() {
		this.buttonIsDisabled = true;
		try {
			Account_Product__c accprod = new Account_Product__c();
			accprod.Name 				= this.prodobject.Name;
			accprod.Account__c 			= this.account.Id;
			accprod.Sign_Up_del__c 		= this.signup.Id;
			accprod.SLX_Product__c 		= this.prodobject.Id;
			accprod.Product_Price__c 	= this.prodobject.product_price__c;	
			insert accprod;
		}
		catch (NullPointerException e) {}
		catch (Exception e) {}		
	}

    public static testMethod void createAnotherProductListTest() {
		createProductList testList = new createProductList();
		List<SelectOption> options = new List<SelectOption>();

		testList.init();
		options = testList.getproductnames();
		testList.product = 'a1B90000000PD4o';
		testList.getbuttonIsDisabled();
		testList.getAccount(); 
		testList.getprodobject();

		testList.populate(); 
		testList.addproduct();
    }
}