src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amex__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amex</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amex__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amex</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Invoice_Number__c</fullName>
        <label>Last Invoice Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Category</label>
        <referenceTo>Product_Category__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <displayFormat>P{000000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Product_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Package</label>
        <referenceTo>Product_Package__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Frequency__c</fullName>
        <description>The frequency of this product to be billed</description>
        <label>Recurring Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLX_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SLX Product</label>
        <referenceTo>SLX_Product__c</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_End_Date__c</fullName>
        <label>Trial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>activeat__c</fullName>
        <label>activeat</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>cancelat__c</fullName>
        <label>cancelat</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>pauseat__c</fullName>
        <label>pauseat</label>
        <type>Date</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SLX_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product_Package__c</fullName>
        <label>Product Package</label>
        <picklist>
            <picklistValues>
                <fullName>No Package</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optimised Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate BRONZE Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate SILVER Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate GOLD Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate DIAMOND Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate PLATINUM Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>350MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>450MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>600MB Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Starter Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Business Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Article Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Article Writing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Brand Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Platinum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local &amp; National Campaign Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local Campaign Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Local Campaign + Analytics Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO National Campaign Package</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>product_price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>product_recurring__c</fullName>
        <label>Product Recurring</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hourly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>recurring_period__c</fullName>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BJB Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceCreateIterable.cls
global class  InvoiceCreateIterable implements Iterator<Account_Product__c>{
	Integer i {get;set;}
	List<Account_Product__c> accountproducts {get;set;}
	
	
	public InvoiceCreateIterable() {
		
		this.accountproducts = [Select 
									   a.pauseat__c,
									   a.cancelat__c, 
									   a.activeat__c,
									   a.Trial_End_Date__c,
									   a.Start_Date__c,
									   a.End_Date__c, 
									   a.SLX_Product__r.product_recurring__c,
									   a.Send_Invoice__c, 
									   a.SLX_Product__c, 
									   a.Recurring_Period__c, 
									   a.Account__r.ID, 
									   a.Account__r.Payment_Option__c,
									   a.Account__r.Unique_Id__c,
									   a.Account__r.Name,
									   a.Recurring_Frequency__c, 
									   a.Product_Status__c, 
									   a.Product_Price__c,
									   a.Product_Package__c, 
									   a.Product_Number__c,
									   a.Product_Category__c, 
									   a.OwnerId,
									   a.Name_On_Card__c, 
									   a.Name, 
									   a.Account__r.Amex__c,
									   a.Last_Invoice_Number__c, 
									   a.Last_Invoice_Date__c,
									   a.LastModifiedDate, 
									   a.Id, 
									   a.CurrencyIsoCode,
									   a.Description__c,
									   a.Create_Invoice__c,
									   a.Company__c, 
									   a.Account__c, 
									   a.Payment_Option__c, 
									   a.No_Charge__c,
									   a.Account__r.website

								From 
									   Account_Product__c a
								Where 
									   a.Product_Status__c = 'Active' 
								and 
									   a.Account__c!=null 
      							and 
      								   (a.Recurring_Period__c != null and a.Recurring_Period__c!='N/A')
      							// Added on 19/04/2017, STOP $0 Converto Invoice Being Raised
      							and
      									(NOT ((Name Like '%ConvertoPages%' or Name Like 'GO%') and Product_Price__c = 0))];
      								

	
		this.i = 0;
	}

	global boolean hasNext() {
		if(this.i >= this.accountproducts.size()) 
        	return false; 
		else 
        	return true;	
	}

	global Account_Product__c next() {
   		return this.accountproducts[this.i++];	
	}
	
	
	
	public static testMethod void testInvoiceCreateIterable() {
        Test.startTest();
        Account_Product__c ap = new Account_Product__c();
        ap.Last_Invoice_Date__c = Date.today();
        ap.Recurring_Frequency__c = 1;
        ap.Product_Price__c = 19.99;
        ap.activeat__c = Date.today();
        insert ap;
        
        InvoiceCreateIterable testIteratble = new InvoiceCreateIterable();
        if(testIteratble.hasNext()){
        	Account_Product__c accountproduct = testIteratble.next();
        }
        Test.stopTest();
    }
}