src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Account_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Daily_Budget__c</fullName>
        <description>Current AdWords Daily Budget</description>
        <label>Daily Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Success_Call__c</fullName>
        <description>The timestamp of the first outbound call which duration longer than 30s in related to the case</description>
        <inlineHelpText>The timestamp of the first outbound call which duration longer than 30s in related to the case</inlineHelpText>
        <label>First Success Call</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X2012_Action_Taken_to_Save__c</fullName>
        <defaultValue>&quot;If you have attempted to save the client, please detail your save strategy.&quot;</defaultValue>
        <description>Action Taken to Save</description>
        <inlineHelpText>If you have attempted to save the client, please detail your save strategy.</inlineHelpText>
        <label>Action Taken to Save</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>password__c</fullName>
        <label>Password</label>
        <length>30</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CasesResponseTimeProcessorTest.cls
@isTest
public class CasesResponseTimeProcessorTest {

    @testSetup static void setup() {
        // Create common test accounts
        List<Account> testAccts = new List<Account>();
        try {
            //create account
            Account itemAcc = new Account(Name = 'TestAccount1', username__c = 'TestAccount1', password__c = 'TestAccount1', CurrencyIsoCode = 'AUD');
            testAccts.add(itemAcc);
            itemAcc = new Account(Name = 'TestAccount2', username__c = 'TestAccount2', password__c = 'TestAccount2', CurrencyIsoCode = 'USD');
            testAccts.add(itemAcc);
            insert testAccts;

            // create account products
            List<Account_Product__c> testProducts = new List<Account_Product__c>();
            for (Integer i = 0; i < 2; i++) {
                Account_Product__c item = new Account_Product__c(Name = 'Social' + 1, Product_Price__c = 1000, CurrencyIsoCode = 'AUD', Account__c = testAccts.get(0).id);
                testProducts.add(item);
            }
            insert testProducts;

            List<Contact> contacts = new List<Contact>();
            for (Integer i = 0; i < testAccts.size(); i++) {
                Account item = testAccts.get(i);
                Contact con = new Contact(AccountId = item.id, LastName = 'test contact');
                contacts.add(con);
            }
            insert contacts;


            //create user with Resolution Manager Profiles
            Profile p = [select Id, name from Profile where Name = 'Resolution Manager' limit 1];
            List<User> users = new List<User>();
            for (Integer i = 0; i < testAccts.size(); i++) {
                User newUser = new User(profileId = p.id,
                        username = 'myTestUser' + i + '@yahoo.com',
                        email = 'testUser1@ff.com',
                        emailencodingkey = 'UTF-8',
                        localesidkey = 'en_US',
                        languagelocalekey = 'en_US',
                        timezonesidkey = 'America/Los_Angeles',
                        alias = 'nuser',
                        lastname = 'testuser_lastname' + i,
                        IsActive = true
                );
                users.add(newUser);
            }
            insert users;

            // create cases
            List<Cases__c> cases = new List<Cases__c>();
            Cases__c obj = new Cases__c(X2012_Action_Taken_to_Save__c = 'check1', Account__c = testAccts[0].id, Daily_Budget__c = 7000, CurrencyIsoCode = 'AUD', Account_Product__c = testProducts[0].id, Status__c ='New');
            cases.add(obj);
            obj = new Cases__c(X2012_Action_Taken_to_Save__c = 'check2', Account__c = testAccts[0].id, Daily_Budget__c = 7000, CurrencyIsoCode = 'AUD', Account_Product__c = testProducts[1].id, Status__c ='New');
            cases.add(obj);
            insert cases;

            //create tasks
            List<Task> tasks = new List<Task>();
            Task newTask1 = new Task(Subject = 'Test Task 1 ', CurrencyIsoCode = 'AUD', Status = 'Completed', Priority = 'Normal', WhatId = cases[0].id, CallDurationInSeconds = 58, CallType = 'Outbound', NVMContactWorld__CW_Call_End_Time__c = system.now(), NVMContactWorld__CW_Call_Start_Time__c = system.now());
            tasks.add(newTask1);
            Task newTask2 = new Task(Subject = 'Test Task 2 ', CurrencyIsoCode = 'AUD', Status = 'Completed', Priority = 'Normal', WhatId = cases[1].id, CallDurationInSeconds = 58, CallType = 'Outbound', NVMContactWorld__CW_Call_End_Time__c = system.now(), NVMContactWorld__CW_Call_Start_Time__c = system.now());
            tasks.add(newTask2);
            insert tasks;

        } catch (DMLException e) {
            system.debug('retry, exception : ' + e.getMessage());
            system.debug('Exception type caught: ' + e.getTypeName());
            system.debug('Message: ' + e.getMessage());
            system.debug('Cause: ' + e.getCause());    // returns null
            system.debug('Line number: ' + e.getLineNumber());
            system.debug('Stack trace: ' + e.getStackTraceString());
        }
    }

    @isTest static void testScheduledJob() {

        // Dummy CRON expression: midnight on March 15.
        // Because this is a test, job executes
        // immediately after Test.stopTest().
        String CRON_EXP = '0 0 * * * ?';

        Test.startTest();
        //update cases status
        List<Cases__c> newcases = [SELECT Id, First_Success_Call__c, Status__c FROM Cases__c WHERE Status__c = 'New'];
        for (Cases__c item : newcases) {
            item.status__c = 'Escalated';
        }
        update newcases;


        // Schedule the test job
        String jobId = System.schedule('CaseResponseTimeProcessorTest', CRON_EXP, new CasesResponseTimeProcessor());

        // Stopping the test will run the job synchronously
        Test.stopTest();

        // Now that the scheduled job has executed,
        // check that our case call time did record to the case
        List<Cases__c> cases = [SELECT Id, First_Success_Call__c, Status__c FROM Cases__c WHERE Status__c = 'Escalated' AND First_Success_Call__c != null];
        system.debug(' result : ' + cases);

        //System.assertEquals(2, cases.size(), 'Call time did not record to case record');

    }

}