src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Card_Number_Masked__c</fullName>
        <label>Card Number Masked</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <label>Credit</label>
        <summarizedField>Payment__c.Payment_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Payment_Type__c</field>
            <operation>equals</operation>
            <value>Credit</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Refund</label>
        <summarizedField>Payment__c.Payment_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Payment__c.Payment_Type__c</field>
            <operation>equals</operation>
            <value>Refund</value>
        </summaryFilterItems>
        <summaryForeignKey>Payment__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <displayFormat>CN{0000000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount Due</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Invoice Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Issue_Date__c</fullName>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AUTHORISED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REFUNDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO CHARGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CREDITED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY CREDITED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY REFUNDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAD DEBT/WRITTEN OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGEBACK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Eway payment records</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit</label>
        <referenceTo>Credit__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Payment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chargeback</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <label>Credit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due__c</fullName>
        <label>Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <label>Refund</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Statement.cls
global class Statement {
	public Account acc {get;set;}
	public Invoice__c invoice1 {get; set;}
	public Invoice__c invoice2 {get; set;}
	public List<TransactionWrapper> transactions {get; set;} 
	public Decimal due {get;set;}
	public Decimal total_amount {get; set;}
	public Decimal total_paid {get; set;}
	public Decimal total_credit {get; set;}
	public Decimal total_paid_by_client {get; set;}
	public Decimal total_refund {get; set;}
	
	public Statement(ApexPages.StandardController controller){
		Account a = (Account)controller.getRecord();
		this.acc = [select Id, Name, Unique_Id__c from Account where Id=:a.Id];
		invoice1 = new Invoice__c();
		invoice2 = new Invoice__c();
	}
	
	public void showResult(){
		transactions = new List<TransactionWrapper>();
		total_amount = 0;
		total_paid = 0;
		due = 0;
		total_credit = 0;
		total_paid_by_client = 0;
		total_refund = 0;
		
		List<Invoice__c> invoices = new List<Invoice__c>();
		Date invoice_from = this.invoice1.Issue_Date__c;
		
		Transaction__c opening = new Transaction__c();
		opening.Activity__c          = 'Opening Balance';
		opening.Due__c               = 0;
		try{
			if(this.invoice1.Issue_Date__c==null) invoice_from = date.newinstance(2012, 7, 1);
			invoices = [Select 
							Id, 
							Amount_Due__c 
						from 
							Invoice__c 
						where 
							Account__c =:acc.Id 
						and 
							(Status__c = 'AUTHORISED' or Status__c = 'PARTIALLY PAID' or Status__c = 'PARTIALLY CREDITED') 
						and 
							Issue_Date__c <: invoice_from
						];
			for(Invoice__c invoice : invoices){
				opening.Due__c += invoice.Amount_Due__c;			
			}
		}catch(Exception e){
			System.debug(e.getMessage());
		}
		opening.Total__c = opening.Due__c;
		TransactionWrapper open = new TransactionWrapper(opening);
		this.transactions.add(open);
		set<String> invList = new set<String>();
		
		try{
			List<Invoice__c> invs = [select 
										Id, 
										CreatedDate, 
										Issue_Date__c, 
										Invoice_Number__c, 
										Reference__c, 
										Due_Date__c,
										Invoice_Total__c 
									from 
										Invoice__c 
									where 
										Account__c =: acc.Id 
									and 
										Issue_Date__c >=: this.invoice1.Issue_Date__c 
									and 
										Issue_Date__c <=: this.invoice2.Issue_Date__c 
									and 
										Status__c != null 
									and 
										Status__c != 'VOID'
									and
										Status__c != 'NO CHARGE'
									];	
			List<Payment__c> payments = [select Id,Payment_Date__c,Payment_Type__c, Invoice_Number__c, Payment_Amount__c, CreatedDate from Payment__c where Account__c =: acc.Id and Payment_Date__c  >=: this.invoice1.Issue_Date__c and Payment_Date__c <=: this.invoice2.Issue_Date__c];
			
			for(Invoice__c inv : invs){
				total_amount += inv.Invoice_Total__c;
				invList.add(inv.Invoice_Number__c+'');
				
				Transaction__c trans = new Transaction__c();
				trans.Link__c        = inv.Id;
				trans.Date__c        = inv.Issue_Date__c;
				trans.Activity__c    = 'Invoice #'+inv.Invoice_Number__c;
				trans.Reference__c   = inv.Reference__c;
				trans.Due_Date__c    = inv.Due_Date__c;
				trans.Total__c       = inv.Invoice_Total__c;
				trans.Due__c         = 0;
				TransactionWrapper transwrapper = new TransactionWrapper(trans);
				this.transactions.add(transwrapper);
			}
			
			for(Payment__c payment : payments){
				Transaction__c trans = new Transaction__c();
				trans.Link__c        = payment.Id;
				trans.Date__c        = payment.Payment_Date__c;
				trans.Due__c         = 0;
				
				if(payment.Payment_Type__c == 'Credit'){
					trans.Activity__c    	= 'Credit Note on Invoice #'+payment.Invoice_Number__c;
					trans.Credit__c 		= payment.Payment_Amount__c;
					total_credit 			+= payment.Payment_Amount__c;
					total_paid 				+= payment.Payment_Amount__c;
				}else if(payment.Payment_Type__c == 'Refund'){
					trans.Activity__c    	= 'Refund on Invoice #'+payment.Invoice_Number__c;
					trans.Refund__c     	= payment.Payment_Amount__c;
					total_refund 			+= payment.Payment_Amount__c;
				}else{
					trans.Activity__c    	= 'Payment on Invoice #'+payment.Invoice_Number__c;
					trans.Payment__c 		= payment.Payment_Amount__c;
					total_paid_by_client 	+=  payment.Payment_Amount__c;
					total_paid 				+= payment.Payment_Amount__c;
				}
				if(!(invList.contains(payment.Invoice_Number__c))){
					opening.Due__c += payment.Payment_Amount__c;
					opening.Total__c += payment.Payment_Amount__c;
					total_amount += payment.Payment_Amount__c;
				}
				TransactionWrapper transwrapper = new TransactionWrapper(trans);
				this.transactions.add(transwrapper);
			}
			
			transactions.sort();
			
			// calcuate balance due after sorting transactions by date desc
			for(TransactionWrapper transwrapper: transactions){
				if(transwrapper.trans.Activity__c == 'Opening Balance'){
					this.due = transwrapper.trans.Due__c;
				} else if(transwrapper.trans.Total__c == null){ //payments
					//if transaction is payment or credit, deduct the amount from due. If it is refund, do nothing.
					if (transwrapper.trans.Activity__c.contains('Credit')) {
						this.due -= transwrapper.trans.Credit__c;
					} else if (transwrapper.trans.Activity__c.contains('Payment')) {
						this.due -= transwrapper.trans.Payment__c;
					}
					transwrapper.trans.Due__c = due;
				} else { //invoices
					this.due += transwrapper.trans.Total__c;
					transwrapper.trans.Due__c = due;
				}
			}
		}catch(Exception e){
			System.debug(e.getMessage());
		}
	}
	
	public PageReference sendEmail(){
		PageReference sendStatement = new pageReference('/apex/SendStatement');
		sendStatement.getParameters().put('acc_id',this.acc.Id);	
 		sendStatement.getParameters().put('acc_name',this.acc.Name);
 		sendStatement.getParameters().put('acc_number',this.acc.Unique_Id__c);
 		sendStatement.getParameters().put('statement_from',String.valueOf(this.invoice1.Issue_Date__c));
 		sendStatement.getParameters().put('statement_to',String.valueOf(this.invoice2.Issue_Date__c));
 		sendStatement.setRedirect(false);
        return sendStatement; 
	}
	
	public PageReference printPDF(){
		PageReference statement = new PageReference('/apex/StatementPDF');
		statement.getParameters().put('acc_id',this.acc.Id);	
 		statement.getParameters().put('acc_name',this.acc.Name);
 		statement.getParameters().put('acc_number',this.acc.Unique_Id__c);
 		statement.getParameters().put('statement_from',String.valueOf(this.invoice1.Issue_Date__c));
 		statement.getParameters().put('statement_to',String.valueOf(this.invoice2.Issue_Date__c));
 		statement.setRedirect(false);
        return statement; 
	}
		
	public static testMethod void testPayment(){
		
		Test.startTest();
		
	    Account acc = new Account(Name ='TestAccount1', username__c='TestAccount1', password__c='TestAccount1', CurrencyIsoCode ='AUD', Phone='78456213',Active__c= true , card_number__c ='3413551010014590', Card_Number_Masked__c ='34XX-XXXX-XXXX-4590' );
	    insert acc;

	    List<Account_Product__c> testProducts = new List<Account_Product__c>();
	    for(Integer i=0;i<1;i++) {                              
	        Account_Product__c item = new Account_Product__c(Name ='Social Engage '+1, Product_Status__c ='Active', Product_Price__c=1000, CurrencyIsoCode ='AUD', Account__c = acc.id , 
	                      recordTypeId =Schema.SObjectType.Account_Product__c.getRecordTypeInfosByName().get('Traditional Products').getRecordTypeId());
	        testProducts.add(item);
	    }
	    insert testProducts; 

		Contact con = new Contact(FirstName='test',LastName='test',Title='Billing',AccountId=acc.id);
		con.MailingStreet='sdfsadfsa\r\ndfsafa\r\nsfsdfsdfs\r\ndfsdfs\r\ndfsdf';
		con.MailingCity='Brisbane';
		con.MailingState='queensland';
		con.MailingPostalCode='4444';
		con.MailingCountry='Australia';
		insert con;
		
		Invoice__c invoice1 = new Invoice__c( Account__c = acc.Id, Account_Product__c = testProducts.get(0).Id, Issue_Date__c = Date.today(), Invoice_Total__c = 10);
		insert invoice1;
		
		Invoice__c invoice2 = new Invoice__c( Account__c = acc.Id, Account_Product__c = testProducts.get(0).Id, Issue_Date__c = Date.today(),Invoice_Total__c = 10);
		insert invoice2;
		
		Invoice__c invoice3 = new Invoice__c( Account__c = acc.Id, Account_Product__c = testProducts.get(0).Id, Issue_Date__c = Date.today().addDays(-2),Invoice_Total__c = 10, Status__c = 'AUTHORISED');
		insert invoice3;
		
		
		Payment__c testpayment1 = new Payment__c( Account__c = acc.Id, Payment_Option__c = 'Eway', Payment_Date__c = Date.today(), Payment_Amount__c = 2.0);
		insert testpayment1;
		
		Payment__c testpayment2 = new Payment__c( Account__c = acc.Id, Payment_Option__c = 'Eway', Payment_Date__c = Date.today().addDays(100), Payment_Amount__c = 2.0);
		insert testpayment2;
		
		
		ApexPages.standardController controller = new ApexPages.standardController(acc);
		Statement statement = new Statement(controller);
		statement.showResult();
		statement.printPDF();
		statement.sendEmail();
		Test.stopTest();
		
	}
}