src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Account_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Daily_Budget__c</fullName>
        <description>Current AdWords Daily Budget</description>
        <label>Daily Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X2012_Action_Taken_to_Save__c</fullName>
        <defaultValue>&quot;If you have attempted to save the client, please detail your save strategy.&quot;</defaultValue>
        <description>Action Taken to Save</description>
        <inlineHelpText>If you have attempted to save the client, please detail your save strategy.</inlineHelpText>
        <label>Action Taken to Save</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactListForCase.cls
public with sharing class ContactListForCase {
	private List<Contact> cs;
	private Cases__c ca {get; set;}
	
	public ContactListForCase(ApexPages.StandardController controller) {
		this.ca = (Cases__c)controller.getRecord();
	}
	
	public List<Contact> getCs() {
		ca = [select id, Account__c from Cases__c where id = :ca.id];
		if(ca.Account__c == null) return null;
		cs = [select Name, Department, Phone, MobilePhone, Email, Title from Contact where AccountId = :ca.Account__c];
		return cs;
	}
	
	public static testMethod void coverageTest () {
		Account account = new Account();
		account.Name = 'Test Account11';
		account.Company__c = 'SponsoredLinX';
		account.username__c = 'test11d11@test.com';
		account.password__c = 'test';
		insert account;
		
		Contact testContact = new Contact();
    	testContact.AccountId = account.Id;
    	testContact.Title = 'Billing';
    	testContact.FirstName = 'test';
    	testContact.LastName = 'test';
    	insert testContact;
    	
    	Cases__c ca = new Cases__c();
    	ca.account__c = account.id;
    	ca.Daily_Budget__c = 10;
    	ca.status__c = 'New';
    	ca.X2012_Action_Taken_to_Save__c = 'NA';
    	insert ca;
    	
    	ApexPages.standardController sc = new ApexPages.standardController(ca);
    	ContactListForCase con = new ContactListForCase(sc);
    	List<Contact> cs = con.getCs(); 
	} 
}