src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the company which manages this account</description>
        <inlineHelpText>the company which manages this account</inlineHelpText>
        <label>BJB Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Department__c</fullName>
        <label>Employee Department</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support &amp; Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>extension__c</fullName>
        <label>Extension</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>35</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>Business_Name__c</fullName>
        <label>Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <description>Company official home page</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Promocode__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promocodes</relationshipLabel>
        <relationshipName>Promocodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promocode</label>
    <nameField>
        <label>Promocode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promocodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountEmployeeTriggerTest.cls
@isTest(seeAllData=true)
private class AccountEmployeeTriggerTest {
	
	// Test account creation trigger
	@isTest static void testInsertSLX() {
		
		Test.startTest();

		// Create company
		Company__c company = new Company__c();
		company.Name 				= 'SponsoredLinX';
		company.Business_Name__c 	= 'SponsoredLinX';
		company.Website__c			= 'www.sponsoredlinx.com';
		company.CurrencyIsoCode		= 'AUD';
		insert company;

		// Create account
		Account account = new Account();
		account.Name					= 'Xavier Xylophone';
		account.username__c				= 'xavier.Xylophone';
		account.password__c				= 'pass1234';
		account.Type					= 'Employee';
		account.Employee_Department__c	= 'Sales';
		account.Phone					= '1300859600';
		account.extension__c			= 123;
		account.email__c				= 'xavier.xylophone@sponsoredlinx.com';
		account.Active__c				= true;
		account.BJB_Company__c 			= company.Id;
		insert account;

		// Assert that account was created
		System.assertNotEquals(null, account.Id, 'Account creation failed');

		// Assert that sales promocodes were created
		List<Promocode__c> promocodes = [SELECT id FROM Promocode__c WHERE Account__c = :account.id];
		System.assert(promocodes.size() >= 1, 'Promocode creation failed');

		Test.stopTest();
	}
	

	// Test account creation trigger
	@isTest static void testInsertGMT() {
		
		Test.startTest();

		// Create company
		Company__c company = new Company__c();
		company.Name 				= 'Get More Traffic';
		company.Business_Name__c 	= 'Get More Traffic';
		company.Website__c			= 'www.getMoretraffic.com.au';
		company.CurrencyIsoCode		= 'AUD';
		insert company;

		// Create account
		Account account = new Account();
		account.Name					= 'Xavier Xylophone';
		account.username__c				= 'xavier.Xylophone';
		account.password__c				= 'pass1234';
		account.Type					= 'Employee';
		account.Employee_Department__c	= 'Sales';
		account.Phone					= '1300859600';
		account.extension__c			= 123;
		account.email__c				= 'xavier.xylophone@sponsoredlinx.com';
		account.Active__c				= true;
		account.BJB_Company__c 			= company.Id;
		insert account;

		// Assert that account was created
		System.assertNotEquals(null, account.Id, 'Account creation failed');

		// Assert that sales promocodes were created
		List<Promocode__c> promocodes = [SELECT id FROM Promocode__c WHERE Account__c = :account.id];
		System.assert(promocodes.size() >= 1, 'Promocode creation failed');

		Test.stopTest();
	}
}