src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <formula>Account__r.BJB_Company__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BJB Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>IF(OR(CONTAINS(Name,&quot;Adwords&quot;),(CONTAINS(Name, &quot;AdWords&quot;))), &apos;AdWords Management&apos;,
IF(CONTAINS(Name,&quot;SEO&quot;),&apos;SEO&apos;,
IF(CONTAINS(Name,&quot;Facebook&quot;), &apos;Social Marketing&apos;, 
IF(CONTAINS(Name,&quot;Social&quot;), &apos;Social Marketing&apos;,
IF(CONTAINS(Name,&quot;Converto&quot;), &apos;ConvertoPages&apos;, &apos;&apos;) ))))</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>Account_Product__r.Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <label>BJB Company</label>
        <picklist>
            <picklistValues>
                <fullName>SponsoredLinX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SponsoredLinX NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GetMoreTraffic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GetMoreTraffic NZ</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>From_Source__c</fullName>
        <description>Used to track where the lead source came from</description>
        <label>From Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Eway payment records</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Payment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chargeback</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>BJB_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the company which manages this account</description>
        <inlineHelpText>the company which manages this account</inlineHelpText>
        <label>BJB Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Source__c</fullName>
        <label>From Source</label>
        <picklist>
            <picklistValues>
                <fullName>Inbound call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Referred A Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex-Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospects List Immediate HC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospects List HC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winback Campaign</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>AdWords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admob Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConvertoPages</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CascadeConnector.cls
public class CascadeConnector {

	//Define the method signature to be implemented in classes that implements the interface
	//Example method
	public static String endpoint_prod {get;set;}
    public static String action {get;set;}
    public static String method {get;set;}
    public static String requestBody{get;set;}
    public static String token{get;set;}
    public static String isTest{get;set;}

    
    public CascadeConnector(String isTestMode){
        endpoint_prod = 'https://disruptdigital.executestrategy.net/api/v2';       
        token = 'Bearer oNXnNVDqFEctKs6y9vzzxI3CdmEuSmHuMcG0Y4VW';        
        requestBody ='';
        isTest = isTestMode;
    }


    public class Metric{
    	String fieldName {get;set;}
    	Decimal fieldValue {get;set;}
    	String createdDate {get;set;}

    	public Metric(){
    	}
    }

	public class GoalHistory{
        String field_name {get;set;}
        String goal_id {get;set;}
        String new_value {get;set;}
        String created_at {get;set;}

    	public GoalHistory(){
    	}
    }


    public static String initGoalHistory(GoalHistory itemProgress){
        return JSON.serialize(itemProgress);    
    }

	public static List<Metric> buildMetrics(){
        List<Metric> metrics = new List<Metric>();
        String sqlString = '';
        String metricItem = '';
        Metric item = new Metric();
        Decimal val = 0.00;
        val.setScale(2); 

        
        

        //Active Clients - SLX - Adwords - daily
        sqlString = 'Select count() from Account_Product__c where Product_Status__c = \'Active\' and Product_Type__c = \'Adwords Management\' and Recurring__c = true and BJB_Company__c like \'SponsoredLinX\'';
        //AggregateResult[] groupedResults  = Database.query(sqlString);        
        val= Database.countQuery(sqlString);     
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        
        item.fieldName = '13';
        item.fieldValue = val;
        metrics.add(item);
        Integer activeClientSLXAdwords = val.intValue();
    

        //Active Clients - GMT - Adwords - daily
        sqlString = 'Select count() from Account_Product__c where Product_Status__c = \'Active\' and Product_Type__c = \'Adwords Management\' and Recurring__c = true and BJB_Company__c like \'Get More Traffic\'';
        val= Database.countQuery(sqlString);   
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '5';
        item.fieldValue = val;
        metrics.add(item);
        Integer activeClientGMTAdwords = val.intValue();
  
        

        //Active Clients - SLX - SEO - daily
        sqlString = 'Select count() from Account_Product__c where Product_Status__c = \'Active\' and Product_Type__c = \'SEO\' and Recurring__c = true';
        val= Database.countQuery(sqlString);      
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}

        item = new Metric();
        item.fieldName = '19';
        item.fieldValue = val;
        metrics.add(item);
  	    Integer activeClientSEO = val.intValue();
  
        //Active Clients - SLX - Social - daily
        sqlString = 'Select count() from Account_Product__c where Product_Status__c = \'Active\' and Product_Type__c = \'Social Marketing\' and Recurring__c = true and BJB_Company__c like \'SponsoredLinX\'';
        val= Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}

        item = new Metric();
        item.fieldName = '105';
        item.fieldValue = val;
        metrics.add(item);
        Integer activeClientSLXSocial = val.intValue();
  
        //Active Clients - GMT - Social - daily
        //metricItem = 'Select count() from Account_Product__c where Product_Status__c = \'Active\' and Product_Type__c = \'Social Marketing\' and Recurring__c = true and BJB_Company__c like \'Get More Traffic\'';
        //metrics.put('105',metricItem );


        //Churn rate - SLX - Adwords - daily
        sqlString = 'Select count() FROM Cases__c Where Cancellation_Date__c = THIS_MONTH and Product_Type__c = \'Adwords Management\' and BJB_Company__c like \'SponsoredLinX\'';
        val= Database.countQuery(sqlString);
        val = (activeClientSLXAdwords == 0)?0:(val*100).divide(activeClientSLXAdwords,2);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '18';
        item.fieldValue = val;
        metrics.add(item);
        

        //Churn rate - GMT - Adwords - daily
        sqlString = 'Select count() FROM Cases__c Where Cancellation_Date__c = THIS_MONTH and Product_Type__c = \'Adwords Management\' and BJB_Company__c like \'Get More Traffic\'';
        val= Database.countQuery(sqlString);        
        val = (activeClientGMTAdwords == 0)?0:(val*100).divide(activeClientGMTAdwords,2);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '30';
        item.fieldValue = val;
        metrics.add(item);


        //Churn rate - SLX - SEO - daily
        sqlString = 'Select count() FROM Cases__c Where Cancellation_Date__c = THIS_MONTH and Product_Type__c = \'SEO\' and BJB_Company__c like \'SponsoredLinX\'';
        val= Database.countQuery(sqlString);
        val = (activeClientSEO == 0)?0:(val*100).divide(activeClientSEO,2);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '103';
        item.fieldValue = val;
        metrics.add(item);


        //Churn rate - SLX - Social - daily
        sqlString = 'Select count() FROM Cases__c Where Cancellation_Date__c = THIS_MONTH and Product_Type__c = \'Social Marketing\' and BJB_Company__c like \'SponsoredLinX\'';
        val= Database.countQuery(sqlString);
        val = (activeClientSLXSocial == 0)?0:(val*100).divide(activeClientSLXSocial,2);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}

        item = new Metric();
        item.fieldName = '33';
        item.fieldValue = val;
        metrics.add(item);

		////Churn rate - GMT - Social - daily
        //metricItem = 'Select count() FROM Cases__c Where Cancellation_Date__c = THIS_MONTH and Product_Type__c = \'Social Marketing\' and BJB_Company__c like \'SponsoredLinX\'';
        //metrics.put('33',metricItem);

        // BTS - SLX - Adwords - daily - % back to sales cases processed by Total sales made
        // BTS: select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c = 'Adwords Management' and BJB_Company__c like 'SponsoredLinX%' 
        sqlString = 'select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c = \'Adwords Management\' and BJB_Company__c like \'SponsoredLinX%\'';
        Integer valBTS = Database.countQuery(sqlString);        
		//Total Sales: Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c = 'Adwords Management' and Bjb_Company__r.Name like 'SponsoredLinX%'
        sqlString = 'Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c = \'Adwords Management\' and Bjb_Company__r.Name like \'SponsoredLinX%\'';
        Integer valTotalSales = Database.countQuery(sqlString);
        val = (valTotalSales == 0)?0:(Decimal.valueOf(valBTS*100)).divide(valTotalSales,2);
        val.setScale(2);        
	    if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}

        item = new Metric();
        item.fieldName = '25';
        item.fieldValue = val;
        metrics.add(item);


        // BTS - GMT - Adwords - daily - % back to sales cases processed by Total sales made
  		//BTS: select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c = 'Adwords Management' and BJB_Company__c like 'Get More Traffic%' 		
        sqlString = 'select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c = \'Adwords Management\' and BJB_Company__c like \'Get More Traffic%\' ';
        valBTS = Database.countQuery(sqlString);        

		//Total Sales: Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c = 'Adwords Management' and Bjb_Company__r.Name like 'Get More Traffic%'
        sqlString = 'Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c = \'Adwords Management\' and Bjb_Company__r.Name like \'Get More Traffic%\'';
        valTotalSales = Database.countQuery(sqlString);
        val = (valTotalSales == 0)?0:(Decimal.valueOf(valBTS*100)).divide(valTotalSales,2);
        val.setScale(2);        
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '24';
        item.fieldValue = val;
        metrics.add(item);


        // BTS - SLX - SEO - daily - % back to sales cases processed by Total sales made
  		//BTS: select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c = 'SEO' and BJB_Company__c like 'SponsoredLinX%' 
        sqlString = 'select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c = \'SEO\' and BJB_Company__c like \'SponsoredLinX%\'';
        valBTS = Database.countQuery(sqlString);        

		//Total Sales: Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c = 'SEO' and Bjb_Company__r.Name like 'SponsoredLinX%'
        sqlString = 'Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c = \'SEO\' and Bjb_Company__r.Name like \'SponsoredLinX%\'';
        valTotalSales = Database.countQuery(sqlString);
        val = (valTotalSales == 0)?0:(Decimal.valueOf(valBTS*100)).divide(valTotalSales,2);
        val.setScale(2);        
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '27';
        item.fieldValue = val;
        metrics.add(item);


		// BTS - SLX - Social - daily - % back to sales cases processed by Total sales made
  		//BTS: select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c like 'Social%' and BJB_Company__c like 'SponsoredLinX%' 		
        sqlString = 'select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c like \'Social%\' and BJB_Company__c like \'SponsoredLinX%\'';
        valBTS = Database.countQuery(sqlString);        

		//Total Sales: Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c like 'Social%' and Bjb_Company__r.Name like 'SponsoredLinX%'
        sqlString = 'Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c like \'Social%\' and Bjb_Company__r.Name like \'SponsoredLinX%\'';
        valTotalSales = Database.countQuery(sqlString);
        val = (valTotalSales == 0)?0:(Decimal.valueOf(valBTS*100)).divide(valTotalSales,2);
        val.setScale(2);        
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '37';
        item.fieldValue = val;
        metrics.add(item);

        /*
		// BTS - GMT - Social - daily - % back to sales cases processed by Total sales made
  		//BTS: select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c like 'Social%' and BJB_Company__c like 'SponsoredLinX%' 		
        sqlString = 'select count() from cases__c where bts__c = true and createdDate = this_Month and product_type__c like \'Social%\' and BJB_Company__c like \'SponsoredLinX%\'';
        valBTS = Database.countQuery(sqlString);        

		//Total Sales: Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c like 'Social%' and Bjb_Company__r.Name like 'SponsoredLinX%'
        sqlString = 'Select count() from Sign_Up__c where CreatedDate = THIS_MONTH and Product_Type__c like \'Social%\' and Bjb_Company__r.Name like \'SponsoredLinX%\'';
        valTotalSales = Database.countQuery(sqlString);
        val = (valTotalSales == 0)?0:valBTS/valTotalSales;
        val.setScale(2);        
        metrics.put('37',val);
        */

        // Group Revenue
        sqlString = 'select sum(Payment_Amount__c) from Payment__c where payment_Date__c = THIS_MONTH and Payment_Type__c != \'Credit\'';
        AggregateResult[] groupedResults  = Database.query(sqlString);
        val = (groupedResults[0].get('expr0') != null)?Decimal.valueOf(''+groupedResults[0].get('expr0')):0.00 ;
        system.debug('val = ' + val) ;
        item = new Metric();
        item.fieldName = '48';
        item.fieldValue = val;
        metrics.add(item);

        // Leads - SLX NZ - Adwords -daily
        sqlString = 'select count() from lead where createdDate = THIS_MONTH and From_Source__c like \'%nz%\' and Status != \'Spam\'';        
        val = Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}

        item = new Metric();
        item.fieldName = '70';
        item.fieldValue = val;
        metrics.add(item);

        // Leads	SLX AU	Online Chat	daily
        sqlString = 'Select count() from lead where status!= \'Spam\' and from_source__c like \'%online chat%\' and createddate = this_month and BJB_Company__c like \'SponsoredLinX%\'';        
        val = Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '87';
        item.fieldValue = val;
        metrics.add(item);

        // Leads	GMT	Online Chat	daily	88
        sqlString = 'select count() from lead where status!= \'Spam\' and from_source__c like \'%online chat%\' and createddate = this_month and BJB_Company__c like \'Get More Traffic%\'';        
        val = Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '88';
        item.fieldValue = val;
        metrics.add(item);

        //Sales	SLX	Adwords	daily	23
        sqlString = 'Select count() from Sign_Up__c where CreatedDate = This_year and Product_Type__c = \'Adwords Management\' and Bjb_Company__r.Name like \'SponsoredLinX%\''  ;     
        val = Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '23';
        item.fieldValue = val;
        metrics.add(item);

        //Sales	GMT	Adwords	daily	22        
        sqlString = 'Select count() from Sign_Up__c where CreatedDate = This_year and Product_Type__c = \'Adwords Management\' and Bjb_Company__r.Name like \'Get More Traffic%\'';
        val = Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '22';
        item.fieldValue = val;
        metrics.add(item);

        //Sales	SLX	SEO	daily	26
		sqlString = 'Select count() from Sign_Up__c where CreatedDate = This_year and Product_Type__c = \'SEO\' and Bjb_Company__r.Name like \'SponsoredLinX%\'';        
        val = Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '26';
        item.fieldValue = val;
        metrics.add(item);
        
        //Sales	SLX	Social	daily	35
		sqlString = 'Select count() from Sign_Up__c where CreatedDate = This_year and Product_Type__c like \'social%\' and Bjb_Company__r.Name like \'SponsoredLinX%\'';        
        val = Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '35';
        item.fieldValue = val;
        metrics.add(item);

        //Sales	GMT	Social	daily	34        
		sqlString = 'Select count() from Sign_Up__c where CreatedDate = This_year and Product_Type__c like \'social%\' and Bjb_Company__r.Name like \'Get More Traffic%\'';
        val = Database.countQuery(sqlString);
        if(isTest == 'true') {
			system.debug('val = ' + val) ;
		}
        item = new Metric();
        item.fieldName = '34';
        item.fieldValue = val;
        metrics.add(item);

        return metrics;

    }


    @future(callout=true)
    public static void updateProgress(){
    	List<Metric> metrics = buildMetrics();
    	for(Metric item:metrics){
    		if(isTest == 'true') {
    			system.debug('name = ' + item.fieldName + ' ; value = ' + item.fieldValue);
    		}
    		addGoalHistory(item.fieldName, item.fieldValue);  
    	}
    }
    

    
    public static void addGoalHistory(String goalID , Decimal newValue)
    { 
        action ='/goal_histories';    
        method ='POST';
        
        //String sqlString= 'Select count() res from Account_Product__c where Product_Status__c = \'Active\' and Product_Type__c = \'Adwords Management\' and Recurring__c = true and BJB_Company__c like \'SponsoredLinX\'';
        //AggregateResult[] groupedResults  = Database.query(sqlString);
        //Integer val = Integer.valueOf(groupedResults[0].get('res').toString().trim());
        Integer val = 1080;
        
        // build the request base on query result and metric parameter
        // build input object
        // GoalHistory itemProgress = new GoalHistory();
        // itemProgress.goal_id ='104';
        // itemProgress.field_name ='progress';
        // itemProgress.new_value = ''+val;
        // itemProgress.created_at = String.valueofGMT(System.DateTime.now()-1);
        if(isTest == 'true') {
        	system.debug('addGoalHistory :: name = ' + goalID + ' ; value = ' + newValue);
    	}
        GoalHistory itemProgress = new GoalHistory();
        itemProgress.goal_id =goalID ;
        itemProgress.field_name ='progress';
        itemProgress.new_value = ''+newValue;
        itemProgress.created_at = String.valueofGMT(System.DateTime.now()-1);


        system.debug('call 1');

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeFieldName('goal_history');
        gen.writeObject(itemProgress);
        gen.writeEndObject();
        requestBody = gen.getAsString();


        //requestBody = initGoalHistory(itemProgress);
        
        // build request
        try{
	        HttpRequest req = new HttpRequest();
	        Http h = new Http();
	        if(!Test.isRunningTest()){
	            endpoint_prod = 'https://disruptdigital.executestrategy.net/api/v2';       
	            token  = 'Bearer oNXnNVDqFEctKs6y9vzzxI3CdmEuSmHuMcG0Y4VW';     
	            action = 'goal_histories';
	            method = 'POST';  
	            
	            req.setEndpoint(endpoint_prod + '/' + action );
	            req.setMethod(method);
	            req.setBody(requestBody); 
	            system.debug('requestBody = ' + requestBody);
	            req.setTimeout(60000);

	            // header.
	            req.setHeader('Authorization', token);
	            req.setHeader('Accept', 'application/json');            
	            req.setHeader('Content-Type', 'application/json');
	            system.debug(req);

	            // send request
	            HTTPResponse res = h.send(req);
	            //system.debug('Response: ' + EncodingUtil.urlDecode(res.getBody(), 'UTF-8'));
	            //res.getBody();
	            
	            // extract the response
	            Map<String, Object> response = (Map<String, Object> )JSON.deserializeUntyped(res.getBody());
	        } 
        }catch(System.CalloutException ex){
			System.debug('Cascade Callout Error: '+ ex);
			System.debug(ex.getMessage());			
			System.debug('addGoalHistory :: name = ' + goalID + ' ; value = ' + newValue);
		}
    }

}