src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Batch</label>
        <referenceTo>Invoice_Batch__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Batch</label>
        <referenceTo>Invoice_Batch__c</referenceTo>
        <relationshipLabel>Invoices (Payment Batch)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Message__c</fullName>
        <label>Payment Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Response__c</fullName>
        <label>Payment Response</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Message__c</fullName>
        <label>Process Message</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AUTHORISED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REFUNDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO CHARGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CREDITED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY CREDITED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY REFUNDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAD DEBT/WRITTEN OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGEBACK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>Batch Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Batch_Period__c</fullName>
        <label>Batch Period</label>
        <picklist>
            <picklistValues>
                <fullName>Today</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>3 Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9 Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13 Day</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Batch_Processed__c</fullName>
        <label>Batch Processed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <label>Batch Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoices</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Batch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Batch Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Batch</label>
    <nameField>
        <label>Invoice Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Signup_Payments__c.object
<CustomObject>
    <label>Signup Payment</label>
    <nameField>
        <label>Signup Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signup Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GMTInvoiceBatch.cls
// No longer used. Use batchInvoiceCreateBatch.
global class GMTInvoiceBatch implements Database.batchable<Invoice__c>,Database.AllowsCallouts {
  
	private String period = 'Today';
	private String companyName = 'Get More Traffic';
	private String batch_name = '';
	private Boolean batch_exist = false;
	private ID todays_batch_id;
	private Date batch_date = Date.today();

	global GMTInvoiceBatch(String period, String companyName) {
		this.period = period;
		this.companyName = companyName;
		System.debug('Period: ' + period); 

		String companyAbbr = companyName.replace('Get More Traffic', 'GMT').replace('SponsoredLinX', 'SLX').replace('New Zealand', 'NZ');

		this.batch_name = companyAbbr + ' ' + DateTime.now().format('EEEE yyyy-MM-dd') + ' ' + this.period + ' Invoice Batch';
		System.debug('Batch Name: ' + this.batch_name);

		try {
			List<Invoice_Batch__c> todaysbatch = [SELECT Id FROM Invoice_Batch__c WHERE name =: this.batch_name AND Batch_Date__c =: this.batch_date];
			System.debug('Todays Batch:' + todaysbatch);
			if (todaysbatch.size() == 0) {
				System.debug('Creating New Invoice Batch');
				Invoice_Batch__c batch = new Invoice_Batch__c();
				batch.name = this.batch_name;
				batch.Batch_Date__c = Date.today();
				batch.Batch_Period__c = this.period;
				System.debug('New Invoice Batch:' + batch);
				insert batch;

				this.todays_batch_id = batch.Id;
			} else {
				this.todays_batch_id = todaysbatch[0].Id;
			}
 
			this.batch_exist = true;
		} catch(Exception e) {
			System.debug('Failed creating a new invoice batch:' + e);
			this.batch_exist = false;
		}
	}

	global Iterable<Invoice__c> start(Database.batchableContext info) {
		return new batchInvoiceCreateIterator(this.period, this.companyName);
	}

	global void execute(Database.batchableContext info, List<Invoice__c> scope) {
		System.debug('Scope: ' + scope);
		System.debug('Batch Exist: ' + this.batch_exist);

		if(this.batch_exist == true) {
			List<Invoice__c> newBatchInvoices = new List<Invoice__c>();
			for(Invoice__c inv : scope){
				List<Signup_Payments__c> payments = [SELECT Id FROM Signup_Payments__c WHERE Name =: inv.Invoice_Number__c];
				if(payments.size() == 0) {
					if (inv.Invoice_Number__c != null) { //strip out repeating templates
						String paymentOption		= '';
						String paymentMethod		= '';
						inv.Invoice_Batch__c = this.todays_batch_id;
						try {
							
							Account_Product__c accountproduct = [SELECT Payment_Option__c, Id FROM Account_Product__c WHERE Id =: inv.Account_Product__c][0];
							paymentOption = accountproduct.Payment_Option__c;
							
							inv.Payment_Batch__c = null;
							inv.Processed__c = false;
							paymentMethod = 'Ready For Payment';
							inv.Payment_Response__c = '';
							inv.Payment_Message__c = '';
							
							
						} catch(Exception e) {
							paymentOption = 'Unknown';
							paymentMethod = 'Unable to attach Payment Option';
						}
						inv.Payment_Option__c	= paymentOption;
						inv.Process_Message__c 	= paymentMethod;
						newBatchInvoices.add(inv);
					}
				}
			}
			System.debug('Inserting batch of invoices');
			update newBatchInvoices;
		}
	}

	global void finish(Database.batchableContext info){
		Invoice_Batch__c todaysBatch;
		List<Invoice_Batch__c> todaysBatches = [SELECT Id,Name,Batch_Date__c,Batch_Number__c,Batch_Processed__c,status__c,Batch_Type__c FROM Invoice_Batch__c WHERE Batch_Type__c = 'Invoices' and Batch_Date__c =: Date.today() and Name =: this.batch_name];
		if(todaysBatches.size() > 0) {
			todaysBatch = todaysBatches[0];
			todaysBatch.status__c = 'Batch Approved';
			update todaysBatch;
		}
	}
}