src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Xero_Sync_ID__c</fullName>
        <label>Xero Sync ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <formula>TEXT(Account.Payment_Option__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Option</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Amount_Credited__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Amount Credited</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Due__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount Due</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Amount Paid</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exclude_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Batch</label>
        <referenceTo>Invoice_Batch__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Invoice Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Issue_Date__c</fullName>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Message__c</fullName>
        <label>Process Message</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Account Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>AUTHORISED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REFUNDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO CHARGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CREDITED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY CREDITED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTIALLY REFUNDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAD DEBT/WRITTEN OFF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGEBACK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Xero_Contact_Id__c</fullName>
        <label>Xero Contact Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Id__c</fullName>
        <label>Xero Invoice Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>Batch Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Batch_Processed__c</fullName>
        <label>Batch Processed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Batch_Records__c</fullName>
        <label>Batch Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <label>Batch Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoices</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Batch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Batch Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Batch</label>
    <nameField>
        <label>Invoice Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Exclude__c.object
<CustomObject>
    <description>List of invoices that we don&apos;t want to send to client via email</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices Exclude</relationshipLabel>
        <relationshipName>Invoices_Exclude</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <externalId>true</externalId>
        <label>Invoice Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Invoice Exclude</label>
    <nameField>
        <label>Invoice Exclude Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Exclude</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Signup_Payments__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Signup Payments</relationshipLabel>
        <relationshipName>Signup_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Signup Payment</label>
    <nameField>
        <label>Signup Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signup Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/getAllXeroInvoices.cls
global class getAllXeroInvoices implements Database.batchable<sfxero.XeroInvoice>,Database.AllowsCallouts {
	public static boolean isTest = false;
	global final Boolean batchCreated;
	global final Integer TotalBatchRecords;
	global final ID TodaysBatchID;
	global final Integer scriptLimit = 50;
	getNextXeroInvoice invoicecls = new getNextXeroInvoice();
	
	global getAllXeroInvoices(){
		
		Invoice_Batch__c batch = new Invoice_Batch__c();
    	batch.name = DateTime.now().format('EEEE') + ' Invoice Batch';
    	batch.Batch_Date__c = Date.today();
	 	if(this.invoicecls.records()>0) {
			batch.status__c = 'New Batch';
    	} else {
    		System.debug('Xero API returned no invoices');
    		batch.status__c = 'Empty Batch';
    	}
    	batch.Batch_Records__c = this.invoicecls.records();
    	insert batch;
    	this.batchCreated = true;
    	this.TodaysBatchID = batch.id;
    	this.TotalBatchRecords = this.invoicecls.records();
	 }

	 global Iterable<sfxero.XeroInvoice> start(Database.batchableContext BC){	 	
		return new xeroInvoiceIterator();
	 }
	 
	 global void execute(Database.BatchableContext BC, List<sfxero.XeroInvoice> scope){
	 	System.debug('Scope:'+scope);
	 	System.debug('batchCreated:'+this.batchCreated);
	 	System.debug('TodaysBatchID:'+TodaysBatchID);
	 	
		if(this.batchCreated==true) {
			//sfxero.XeroInvoice inv;			
			List<Invoice__c> newBatchInvoices = new List<Invoice__c>();
			//for(Integer i = 0; i < this.scriptLimit; i++) {
			for(sfxero.XeroInvoice inv : scope){
	 			//inv = scope[0];
	 			List<Signup_Payments__c> payments = [SELECT Id FROM Signup_Payments__c WHERE Name=:inv.InvoiceNumber];
	 			if(payments.size() == 0) {
		        	if (inv.InvoiceNumber!=null) { //strip out repeating templates
			        	System.debug('XERO Invoice: '+inv);
			        	Invoice__c newinv = new Invoice__c(); 
			        	newinv.Invoice_Batch__c     = this.TodaysBatchID;
			        	newinv.Xero_Contact_Id__c	= inv.Contact.ContactID;
			        	newinv.Xero_Invoice_Id__c	= inv.InvoiceID; 	
			        	newinv.Name				 	= inv.Contact.OrgName;
			        	newinv.Invoice_Number__c 	= inv.InvoiceNumber;        	
			        	newinv.Reference__c			= inv.Reference;
			        	newinv.Issue_Date__c		= inv.issuedDate;
			        	newinv.Due_Date__c			= inv.dueDate;
			        	newinv.Amount_Credited__c	= inv.AmountCredited;
			        	newinv.Amount_Due__c		= inv.AmountDue;
			        	newinv.Amount_Paid__c		= inv.AmountPaid;
			        	newinv.Invoice_Total__c		= inv.Total;
			        	String paymentOption = '';
			        	String paymentMethod = '';
	
						//List<Invoice_Exclude__c> invoices_exclude;
						//invoices_exclude = [SELECT Id, Invoice_Number__c FROM Invoice_Exclude__c WHERE Invoice_Number__c =: inv.InvoiceNumber];
						//if(invoices_exclude.size() > 0) {
						//	newinv.Exclude_Invoice__c = true;
						//}
	
			        	try {
			        		Account account = [SELECT Payment_Option__c FROM Account WHERE Xero_Sync_ID__c=:inv.Contact.ContactID][0]; 
			        		newinv.Account__c = account.Id;
			        		paymentOption = account.Payment_Option__c;	
			        		paymentMethod = 'Ready For Payment';
			        	}catch(Exception e) {
			        		paymentOption = 'Unknown';
			        		paymentMethod = 'Unable to attach Payment Option';
			        	}
			        	newinv.Payment_Option__c	= paymentOption;
			        	newinv.Process_Message__c 	= paymentMethod;
			        	System.debug('SF New Invoice: '+newinv);
			        	//insert newinv;
			        	newBatchInvoices.add(newinv);
		        	}
	 			}		
	        }
	        System.debug('Inserting batch of invoices');
	        insert newBatchInvoices;
		}
	 }
	 
	 global void finish(Database.BatchableContext BC){
	 	String batchName = DateTime.now().format('EEEE') + ' Invoice Batch';
		Invoice_Batch__c todaysBatch;
		List<Invoice_Batch__c> todaysBatches = [SELECT Id,Name,Batch_Date__c,Batch_Number__c,Batch_Processed__c,status__c,Batch_Type__c FROM Invoice_Batch__c WHERE Batch_Type__c = 'Invoices' and Batch_Date__c =: Date.today() and Name=:batchName];
		if(todaysBatches.size() > 0) {
			todaysBatch = todaysBatches[0];
		 	todaysBatch.status__c = 'Pending Approval';
		    update todaysBatch;
		}
	 }
	 global class xeroInvoiceIterator implements Iterable<sfxero.XeroInvoice> {
	   global Iterator<sfxero.XeroInvoice> iterator(){
	      return new getNextXeroInvoice();
	   }
	}
	 public static testMethod void testBatch() {
	 	Test.startTest();
	 	getAllXeroInvoices.isTest = true;
	 	getNextXeroInvoice.isTest = true;
		getAllXeroInvoices scriptBatch = new getAllXeroInvoices();
		ID batchprocessid = Database.executeBatch(scriptBatch);
		Test.stopTest();
	 }	
}