src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Invoice_Date__c</fullName>
        <label>Last Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Option__c</fullName>
        <label>Payment Option</label>
        <picklist>
            <picklistValues>
                <fullName>Eway</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Buddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commweb</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>cancelat__c</fullName>
        <label>cancelat</label>
        <type>Date</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>Account_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Product</label>
        <referenceTo>Account_Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Account_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>Other Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosting Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reassign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday Discount</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>X2012_Action_Taken_to_Save__c</fullName>
        <defaultValue>&quot;If you have attempted to save the client, please detail your save strategy.&quot;</defaultValue>
        <description>Action Taken to Save</description>
        <inlineHelpText>If you have attempted to save the client, please detail your save strategy.</inlineHelpText>
        <label>Action Taken to Save</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CancellationRevenue.cls
/*
	Caculate the total lost revenue of cancelled products for each client manager in last month
*/

public with sharing class CancellationRevenue {
	//Key is CM's name, value is his/her lost revenue.
	public Map<String, Decimal> teamAMap  {get; set;}
	public Map<String, Decimal> teamBMap  {get; set;}
	
	public CancellationRevenue () {
		User[] teamA = [select name from user where userRole.name like '%Client Manager Team A%'];
		User[] teamB = [select name from user where userRole.name like '%Client Manager Team B%'];
						
		teamAMap  = new Map<String, Decimal>();
		teamBMap  = new Map<String, Decimal>();
		//Initial lost map, in case some client manager has no cancelled product in last month. Should display them in table as well
		for (user u : teamA) {
			teamAMap.put(u.name, 0);
		}
		for (user u : teamB) {
			teamBMap.put(u.name, 0);
		}
		
		Set<String> cmAs = teamAMap.keyset();
		Set<String> cmBs = teamBMap.keyset();
		
		//Get the cancelled account list from cancellation cases. Avoid counting in the downgrade/upgrade cancellation product
		Set<Id> cancelAccs = new Set<Id>();
		Cases__c[] cas = [select
							account__c
						from
							cases__c
						where
							CaseType__c = 'Cancellation'
						and
							cancellation_date__c = last_month
						];
		for(Cases__c ca : cas) {
			cancelAccs.add(ca.account__c);
		}
		
		Account_product__c[] aps = [select
									product_price__c, 
									last_invoice_date__c, 
									cancelat__c, 
									Recurring_Period__c,
									owner.name
								from
									Account_Product__c
								Where
									Product_Status__c = 'Cancelled'
								And
									Recurring_Period__c != null
								And
									Recurring_Period__c != 'N/A'
								And
									Name Like '%Adwords%'
								And
									cancelat__c = Last_month
								And
									(Owner.name in :cmAs or Owner.name in :cmBs)
								And
									account__c in :cancelAccs	
								];
		if (aps.size() > 0) {
			for(Account_product__c ap : aps) {
				Decimal singleProductLost = caculateLost(ap.Recurring_Period__c, ap.Product_Price__c, ap.cancelat__c, ap.Last_Invoice_Date__c);
	    		Decimal tmp;
	    		if (cmAs.contains(ap.owner.Name)) {
	    			tmp = teamAMap.get(ap.owner.Name);
	    			tmp += singleProductLost;
	    			teamAMap.put(ap.owner.Name, tmp);
	    		} else if(cmBs.contains(ap.owner.Name)) {
	    			tmp = teamBMap.get(ap.owner.Name);
	    			tmp += singleProductLost;
	    			teamBMap.put(ap.owner.Name, tmp);
	    		}
			}
		}
		teamAMap.put('#Total', sumup('Team A'));
		teamBMap.put('#Total', sumup('Team B'));
	}
	
	private Decimal caculateLost(String recurPeriod, Decimal price, Date cancelDate, Date lastInvoiceDate ) {
		Decimal sum = 0;
		
		Date firstDayOfMonth = cancelDate.toStartOfMonth();
		Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1); 
		
		integer days = lastInvoiceDate.daysBetween(lastDayOfMonth);
		
		integer cycle = 0;
		if (recurPeriod == 'Weekly') {
			cycle = days/7;
		} else if (recurPeriod == 'Monthly') {
			if (lastInvoiceDate.month() != cancelDate.month()) {
				cycle = 1;
			}
		}
		sum = cycle * price;
		
		return sum;
	}
	
	public Decimal sumup (String teamName) {
		Decimal total = 0;
		List<Decimal> revenues;
		if (teamName.equals('Team A')) {
			revenues = teamAMap.values();
		} else if (teamName.equals('Team B')) {
			revenues = teamBMap.values();
		}
		for (Decimal d : revenues) {
			total += d;
		}
		return total;
	}
	
	
	@isTest(SeeAllData=true)
	static void coverageTest () {
		Test.startTest();
		Account acc = new Account();
		acc.name = 'My Test Account';
		insert acc;
		
        User u = [SELECT id FROM user WHERE IsActive = true LIMIT 1];
        
        Cases__c ca = new Cases__c();
        ca.account__c = acc.id;
        ca.CaseType__c = 'Cancellation';
        ca.cancellation_date__c = Date.today().toStartOfMonth().addDays(-15);
        ca.X2012_Action_Taken_to_Save__c = 'blah blah';
        insert ca;
		
		Account_product__c ap = new Account_product__c();
		ap.Account__c = acc.id;
		ap.Ownerid = u.id;
		ap.name = 'Adwords Management';
        ap.Product_Price__c = 69.0;
        ap.Recurring_Period__c ='Weekly';
        ap.Payment_Option__c = 'Eway';
        ap.product_status__c = 'Cancelled';
        ap.cancelat__c = Date.today().toStartOfMonth().addDays(-15);
        ap.Last_Invoice_Date__c = Date.today().toStartOfMonth().addDays(-17);
		insert ap;
		
		Account_product__c ap1 = new Account_product__c();
		ap1.Account__c = acc.id;
		ap1.Ownerid = u.id;
		ap1.name = 'Adwords Management';
        ap1.Product_Price__c = 69.0;
        ap1.Last_Invoice_Date__c = Date.today().addMonths(-1);
        ap1.Recurring_Period__c ='Monthly';
        ap1.Payment_Option__c = 'Eway';
        ap1.product_status__c = 'Cancelled';
        ap1.cancelat__c = Date.today().toStartOfMonth().addDays(-15);
        ap1.Last_Invoice_Date__c = Date.today().toStartOfMonth().addDays(-20);
		insert ap1;
		
		CancellationRevenue cr = new CancellationRevenue();
		
		Test.stopTest();
	}

}