src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Products</relationshipLabel>
        <relationshipName>Account_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_14_days_num_of_calls__c</fullName>
        <description>Last 14 days num of calls</description>
        <inlineHelpText>Last 14 days num of calls</inlineHelpText>
        <label>Last 14 days num of calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_14_days_num_of_emails__c</fullName>
        <description>Last 14 days num of emails</description>
        <inlineHelpText>Last 14 days num of emails</inlineHelpText>
        <label>Last 14 days num of emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_21_days_num_of_calls__c</fullName>
        <description>Last 21 days num of calls</description>
        <inlineHelpText>Last 21 days num of calls</inlineHelpText>
        <label>Last 21 days num of calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_21_days_num_of_emails__c</fullName>
        <description>Last 21 days num of emails</description>
        <inlineHelpText>Last 21 days num of emails</inlineHelpText>
        <label>Last 21 days num of emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_7_days_num_of_calls__c</fullName>
        <description>Last 7 days num of calls</description>
        <inlineHelpText>Last 7 days num of calls</inlineHelpText>
        <label>Last 7 days num of calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_7_days_num_of_emails__c</fullName>
        <description>Last 7 days num of emails</description>
        <inlineHelpText>Last 7 days num of emails</inlineHelpText>
        <label>Last 7 days num of emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Linking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurring_Period__c</fullName>
        <description>The unit of recurring frequency</description>
        <label>Recurring Period</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <label>Account Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountProductProcessor.cls
global class AccountProductProcessor implements Database.Batchable<sObject>, Database.Stateful {
//	global class AccountProductProcessor implements Database.Batchable<Account_Product__c> {
	
	global String query;
	global list<Account_Product__c> activeProducts;
	global Map<String, Integer> com7emails;	
	global Map<String, Integer> com7calls;
	global Map<String, Integer> com14emails;
	global Map<String, Integer> com14calls;
	global Map<String, Integer> com21emails;
	global Map<String, Integer> com21calls;
	
	global List<String> accList;

	global List<String> ownerList;
	global DateTime days7 ;
	global DateTime days14 ;
	global String subCondition;
	global Long processingTime;

	
	
	global AccountProductProcessor(String numOfRecords) {

		//init calculation params
		com7emails = new Map<String, Integer>();
		com7calls = new Map<String, Integer>();	
		com14calls = new Map<String, Integer>();	
		com14emails = new Map<String, Integer>();	
		com21calls = new Map<String, Integer>();	
		com21emails = new Map<String, Integer>();	

		//init days7 datetime
		Datetime currentDate = system.today();
		Integer d = currentDate.day();
		Integer mo = currentDate.month();
		Integer yr = currentDate.year();
		Datetime currentDatetime = DateTime.newInstance(yr, mo, d);
		days7 = currentDatetime.addDays(-7);
		days14 = currentDatetime.addDays(-14);

		System.debug('Last 7 days = ' + days7.format());

		//set limit num of records
		if (numOfRecords<>null && numOfRecords.length()>0){
			this.subCondition =  numOfRecords;
		}else this.subCondition ='';
		processingTime = 0;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
        query = ' SELECT Id, Product_Status__c, Account__c, OwnerId, Last_14_days_num_of_calls__c, Last_14_days_num_of_emails__c,Last_7_days_num_of_calls__c,Last_7_days_num_of_emails__c '
         		+ ' FRoM  Account_Product__c '
         		+ ' WHERE Product_Status__c = \'Active\' AND Account__r.Active__c= true '
         		+ ' AND Recurring_Period__c <> \'N/A\' '
         		+ ' AND (NAME like \'%Adword%\' OR NAME like \'%Facebook%\' ) '
         		+  this.subCondition;
        // tracking processing time
        processingTime = DateTime.now().getTime();

		//fetching data
		return Database.getQueryLocator(query);
	}


	//global Iterable<Account_Product__c>  start(Database.BatchableContext BC) {        
	//	return new CustomActivityHistoryIterable();
	//}

   	global void execute(Database.BatchableContext BC, List<Account_Product__c> scope) {
   			Integer calls, emails , calls21, emails21;
			accList = new List<String>();
			ownerList = new List<String>();
			String accounts = '';
			String owners = '';

			for(Account_Product__c itemproduct:scope){
				// build SQL string
				List<Task> processingTasks = [ SELECT id, AccountId, OwnerId , Subject , LastModifiedDate , TaskSubtype FROM Task
												WHERE IsClosed = true
												AND ( (TaskSubtype = 'Email') OR (calltype = 'Outbound') )
												AND LastModifiedDate= LAST_N_DAYS:21 
												AND AccountId = :itemproduct.Account__c
												AND OwnerId = :itemproduct.OwnerId ];
				system.debug('processingTasks = ' +processingTasks.size())  ;
	   			for(Task item: processingTasks){
	   				String key = item.AccountId  + ':' + item.OwnerId;
					emails = 0;
					calls =0;
					emails21 = 0;
					calls21= 0;

					if (item.TaskSubtype =='Email'){
						//within 7days
						if(item.LastModifiedDate>= days7){
							if(com7emails.get(key) == null){
								emails = 1;					
							}else{
								emails =  com7emails.get(key);
								system.debug('result.Last_7_days_num_of_emails = ' + emails);
								emails += 1;
							}					
							com7emails.put(key, emails);
						}
						if(item.LastModifiedDate>= days14){
							if(com14emails.get(key) == null){
								emails = 1;					
							}else{
								emails =  com14emails.get(key);
								system.debug('result.Last_14_days_num_of_emails = ' + emails);
								emails += 1;
							}					
							com14emails.put(key, emails);
						}


						if(com21emails.get(key) == null){
							emails21 = 1;					
						}else{
							emails21 =  com21emails.get(key);
							system.debug('result.Last_21_days_num_of_emails = ' + emails);
							emails21 += 1;
						}					
						com21emails.put(key, emails21);
					
					} else{
						// for outbound calls
						//within 7days
						if(item.LastModifiedDate>= days7){
							if(com7calls.get(key) == null){
								calls = 1;					
							}else{
								calls =  com7calls.get(key);
								system.debug('result.Last_7_days_num_of_calls = ' + calls);
								calls += 1;
							}					
							com7calls.put(key, calls);
							system.debug('com7calls = ' + calls);
						}

						if(item.LastModifiedDate>= days14){
							if(com14calls.get(key) == null){
								calls = 1;					
							}else{
								calls =  com14calls.get(key);
								system.debug('result.Last_14_days_num_of_calls = ' + calls);
								calls += 1;
							}					
							com14calls.put(key, calls);
							system.debug('com7calls = ' + calls);
						}

						if(com21calls.get(key) == null){
							calls21 = 1;					
						}else{
							calls21 =  com21calls.get(key);
							system.debug('result.Last_21_days_num_of_calls = ' + calls);
							calls21 += 1;
						}					
						com21calls.put(key, calls21);
						system.debug('com21calls = ' + calls21);
						
					}
	   			}	
   			}
			
			List<Account_Product__c> updateProducts = new List<Account_Product__c>();
			for(Account_Product__c item: scope){
				String key= item.Account__c + ':' + item.OwnerId;
				
				item.Last_7_days_num_of_emails__c = (com7emails.get(key) == null)? 0:com7emails.get(key);
				item.Last_7_days_num_of_calls__c = (com7calls.get(key)== null)? 0:com7calls.get(key);
				item.Last_14_days_num_of_emails__c = (com14emails.get(key)== null)? 0:com14emails.get(key);
				item.Last_14_days_num_of_calls__c = (com14calls.get(key)== null)? 0:com14calls.get(key);
				item.Last_21_days_num_of_emails__c = (com21emails.get(key)== null)? 0:com21emails.get(key);
				item.Last_21_days_num_of_calls__c = (com21calls.get(key)== null)? 0:com21calls.get(key);

				updateProducts.add(item);
			}
			update updateProducts;	
	}
	
	global void finish(Database.BatchableContext BC) {
		system.debug('finish');
		processingTime = DateTime.now().getTime() - processingTime;
        
		AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
					      FROM AsyncApexJob WHERE Id = :BC.getJobId()];

	   // Send an email to the Apex job's submitter notifying of job completion.
	   Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	   String[] toAddresses = new String[] {'salesforce@sponsoredlinx.com'};
	   mail.setToAddresses(toAddresses);
	   mail.setSubject('Communication Calculation is : ' + a.Status);
	   mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems +   ' batches with '+ a.NumberOfErrors + ' failures.' +' and JobItemsProcessed = ' + a.JobItemsProcessed + ' With processing time in milisecond is ' + processingTime);
	   Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
	}
	
}