src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active_Days__c</fullName>
        <label>Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines if this account is active</description>
        <inlineHelpText>This field determines if this account is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HasSEOProject__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Decide whether the account has a seo project, if yes, then share the account with SEO Account Manager</description>
        <label>HasSEOProject</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outstanding_Amount__c</fullName>
        <label>Outstanding Amount</label>
        <summarizedField>Invoice__c.Amount_Due__c</summarizedField>
        <summaryFilterItems>
            <field>Invoice__c.Status__c</field>
            <operation>contains</operation>
            <value>AUTHORISED, PARTIALLY PAID, PARTIALLY CREDITED, PARTIALLY REFUNDED</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Days__c</fullName>
        <formula>Account__r.Active_Days__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assign_To_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assign To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Daily_Budget__c</fullName>
        <label>Daily Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>AdWords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admob Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConvertoPages</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending 1st Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending CM Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold to Pause</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SLXOpportunity__c.object
<CustomObject>
    <description>Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Adwords_Daily_Budget__c</fullName>
        <label>Adwords Daily Budget</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_Number__c</fullName>
        <label>Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Importance__c</fullName>
        <label>Importance</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adwords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+ Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Upgrade</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Reason_For_Opportunity__c</fullName>
        <label>Reason For Opportunity</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Send_to_Salesperson__c</fullName>
        <label>Send to Salesperson (no longer used)</label>
        <picklist>
            <picklistValues>
                <fullName>Gretel Phillips</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daniel Andreotti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tate Wotton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simon Golding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meg Arreza</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joshua Beatty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Teamleader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abigail Harrison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ngawai Mason</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit Ran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Competitors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>BJB Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BJB Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GenerateWeeklyOpportunity.cls
public with sharing class GenerateWeeklyOpportunity {
	public GenerateWeeklyOpportunity() {	
		Account[] accs = [select 
								id,
								website,
								name,
								(select id from Opportunities__r where createdDate = LAST_N_DAYS:180),
								(select Name, Phone, Email from Contacts where Title = 'Marketing' limit 1),
								(select Daily_Budget__c from Sign_Ups__r where Product_Type__c = 'AdWords Management' and Daily_Budget__c >= 10 order by CreatedDate desc limit 1)
							from 
								Account
							where
								HasSEOProject__c = false
							and
								Active_Days__c > 90
							and
								Active__c = true
							and
								Outstanding_Amount__c < 100
							]; 
		List<Account> accounts = new List<Account>();					
		for(Account acc : accs) {
			if(acc.Opportunities__r.isEmpty()) {
				accounts.add(acc);
			}
		}
		
		List<SLXOpportunity__c> opps = new List<SLXOpportunity__c>();
		
		List<User> team = [
		SELECT Id, name, email 
		FROM user 
		WHERE isActive = true AND (UserRole.name = 'Digital Strategy Sales' OR UserRole.name = 'Sales Manager Assistant Digital Strategy' OR UserRole.name = 'Digital Strategy Manager')
		];

		for(User u : team) {
			integer counter = 0;
			while(counter < 10 && !accounts.isEmpty()) {
				SLXOpportunity__c opp = new SLXOpportunity__c();
				integer index = getRandomIndex(accounts.size());
				Account acc = accounts.remove(index);
				opp.Account__c = acc.Id;
				opp.name = acc.name;
				opp.Product_Type__c = 'SEO Management';
				opp.OwnerId = u.Id;
				opp.Send_to_Salesperson__c = u.Name;
				opp.website__c = acc.website == null ? 'Cannot find in Account. Please update manually' : acc.website;
				opp.status__c = 'New';
				opp.importance__c = 'Medium';
				opp.Contact_Name__c = acc.Contacts.isEmpty() ? '' : acc.Contacts.get(0).Name;
				opp.Contact_Email__c = acc.Contacts.isEmpty() ? '' : acc.Contacts.get(0).Email;
				opp.Contact_Phone_Number__c = acc.Contacts.isEmpty() ? '' : acc.Contacts.get(0).Phone;
				opp.Adwords_Daily_budget__c = !acc.Sign_Ups__r.isEmpty() && acc.Sign_Ups__r.get(0).Daily_Budget__c >= 10 ? acc.Sign_Ups__r.get(0).Daily_Budget__c : 20;
				opp.Reason_For_Opportunity__c = 'System generated weekly opportunities';
				opps.add(opp);
				counter++;
			}
		}
		
		insert(opps);
	}
	
	public Integer getRandomIndex(Integer arraySize){
        return (integer) Math.floor(Math.random() * arraySize);
    }
	
}