src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>Account_Resolution__c</fullName>
        <label>Account Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Save</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alter Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved to SEO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Signup_Date__c</fullName>
        <label>Signup Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending 1st Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending CM Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold to Pause</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/livestats.cls
public with sharing class livestats {
	
	private Integer time_to_check = 5;
	
	public String getPlaySoundForNewSignup() {
		Datetime d = System.now();
		Datetime myDT = DateTime.newInstance(d.year(),d.month(),d.day(),d.hour(),d.minute()-time_to_check,d.second());		
		List<Sign_Up__c> last5minsignups = [SELECT id,name,Signup_Date__c,Status__c,CreatedDate  FROM Sign_Up__c WHERE CreatedDate >=:myDT];
		
		String rtndata = '';
		
		if(last5minsignups.size()>=1) {
			rtndata += 'http://livesignups.bjbglobal.com.au/woohoo.wav';
		}
		return rtndata;
	}
	
	public String getPlaySoundForNewCancellation() {		
		Datetime d = System.now();
		Datetime myDT = DateTime.newInstance(d.year(),d.month(),d.day(),d.hour(),d.minute()-time_to_check,d.second());		
		List<Cases__c> last5mincancellations = [SELECT Id,Name,Account_Resolution__c FROM Cases__c WHERE Account_Resolution__c='Cancellation' and Status__c IN ('Closed','Unresolved') and Cancellation_Date__c >= TODAY and LastModifiedDate >= :myDT];
		
		String rtndata = '';
		
		if(last5mincancellations.size()>=1) {
			rtndata += 'http://livesignups.bjbglobal.com.au/doh.wav';
		}
		return rtndata;
	}

	public Integer getNumberOfSignupsToday() {
		List<Sign_Up__c> todayssignups = [SELECT id,name,Signup_Date__c,Status__c,CreatedDate  FROM Sign_Up__c WHERE CreatedDate >= TODAY];
		return todayssignups.size();
	}  
	
	public Integer getNumberOfCancellationsToday() {
		List<Cases__c> todayscancellations = [SELECT Id,Name,Account_Resolution__c FROM Cases__c WHERE Account_Resolution__c='Cancellation' and Status__c IN ('Closed','Unresolved') and Cancellation_Date__c >= TODAY];
		return todayscancellations.size();
	}

}