src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>Other Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosting Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reassign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday Discount</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Client_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Success_Call__c</fullName>
        <description>The timestamp of the first outbound call which duration longer than 30s in related to the case</description>
        <inlineHelpText>The timestamp of the first outbound call which duration longer than 30s in related to the case</inlineHelpText>
        <label>First Success Call</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>Account_Product__r.Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Voicemail__c.object
<CustomObject>
    <fields>
        <fullName>Client_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Voicemails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response_Time__c</fullName>
        <description>Response Time</description>
        <inlineHelpText>Response Time</inlineHelpText>
        <label>Response Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Voicemail</label>
    <nameField>
        <displayFormat>VM-{00000}</displayFormat>
        <label>Voicemail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voicemails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NewVoiceMediaCallHelper.cls
global class NewVoiceMediaCallHelper {
	
	global void getResponseTimeForVoiceMail(){
		system.debug('NewVoiceMediaCallHelper:getResponseTimeForVoiceMail');
		try{
			// get all current miss calles
	   		List<VoiceMail__c> scope = [SELECT id,  Status__c, Client_Manager__c, Response_Time__c FROM VoiceMail__c WHERE Status__c= 'New'];
	   		Map<Id, VoiceMail__c > missCalles = new Map<Id, VoiceMail__c>();   		
	   		for(VoiceMail__c s : scope){
	   			missCalles.put(s.id, s);
			}     
	   		
	   		// get all related calles 
	   		// with call type = outbound and duration is greater than 30
	   		system.debug('NewVoiceMediaCallHelper:scope size = '+ scope.size());
	   		Set<Id> listIDs = missCalles.keyset();
	   		if(scope.size()>0){
				List<Task> calles = [SELECT id, CallType, CallObject, CallDurationInSeconds , NVMContactWorld__CW_Call_Start_Time__c, NVMContactWorld__CW_Call_End_Time__c , WhatId, NVMContactWorld__Was_Call_Recorded__c
									 FROM Task
									 WHERE  Status = 'Completed'   										
											AND CallType = 'Outbound'
											AND WhatId IN :listIDs];
				if (calles.size() > 0) {
					system.debug('NewVoiceMediaCallHelper:getResponseTimeForVoiceMail: query result = ' + calles.size());
					// checking and process
					Map<Id, VoiceMail__c > updateCalles = new Map<Id, VoiceMail__c>();  
					for (Task item : calles) {
						if (item.CallDurationInSeconds >= 30) {
							VoiceMail__c voicemail = (VoiceMail__c)missCalles.get(item.WhatId);
							voicemail.Response_Time__c = item.NVMContactWorld__CW_Call_Start_Time__c ;
							voicemail.Status__c = 'Closed';
							updateCalles.put(voicemail.id,voicemail);
							SYstem.debug('getResponseTimeForVoiceMail :: ' + voicemail.id + 'updated');
						}
					}
					update updateCalles.values();
				} else {
					system.debug('NewVoiceMediaCallHelper: getResponseTimeForVoiceMail: there is not query result' );
				}
			}
		}catch (Exception ex){
			system.debug('NewVoiceMediaCallHelper:getResponseTimeForVoiceMail: Exception occured :' + ex.getMessage() );
		}
	}
    
    

	public void getResponseTimeForCases(){
		try{
			// get all current escalated cases
	   		List<Cases__c> scope = [SELECT id,  Status__c, First_Success_Call__c FROM Cases__c 
	   								WHERE Status__c= 'Escalated'
	   										AND (Product_Type__c = 'Social Marketing' OR Product_Type__c = 'AdWords Management')
											AND CaseType__c = 'Cancellation'];
	   		Map<Id, Cases__c > escalatedCases = new Map<Id, Cases__c>();   		
	   		for(Cases__c s : scope){
	   			escalatedCases.put(s.id, s);
			}     
	   		
	   		if(scope.size()>0){
		   		Set<id> listIds =escalatedCases.keyset();
		   		List<Task> calles = [SELECT id, CallType, CallObject, CallDurationInSeconds , NVMContactWorld__CW_Call_Start_Time__c, NVMContactWorld__CW_Call_End_Time__c , WhatId, NVMContactWorld__Was_Call_Recorded__c 
		   							 FROM Task 
		   							 WHERE Status = 'Completed'
		   							 AND CallType = 'Outbound'
		   							 AND WhatId IN :listIds];
				
				if(calles.size()>0){	
					// checking and process
					scope.clear();
					for(Task item : calles){
						if (item.CallDurationInSeconds  >= 30){
							Cases__c casesItem = (Cases__c)escalatedCases.get(item.WhatId);
							casesItem.First_Success_Call__c = item.NVMContactWorld__CW_Call_Start_Time__c ;				
							scope.add(casesItem);				
						}			
					}		
					update scope;
				}
			}
		}catch (Exception ex){
			system.debug('NewVoiceMediaCallHelper:getResponseTimeForCases: Exception occured :' + ex.getMessage() );
		}
					
	}

}