src/objects/Cases__c.object
<CustomObject>
    <description>Customer Service Cases</description>
    <fields>
        <fullName>CaseType__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>Other Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosting Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reassign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christmas Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday Discount</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>Account_Product__r.Product_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resolution Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
                <color>#CC0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unresolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cases</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TriggerUtilities.cls
public class TriggerUtilities {
    /*
 	public static Integer getNumberOfResolutionManager(){
         System.debug('TriggerUtilities::getNumberOfResolutionManager');
         List<User> managers = [SELECT id, username, profile.name, isActive 
                               FROM User 
                               WHERE isActive=true 
                               		 AND profile.name = 'Resolution Manager' ORDER BY username DESC];
         return managers.size();
    }

    public static User getAvailableResultionManager(Integer escalatedNo){
		System.debug('TriggerUtilities::getAvailableResultionManager');
        List<User> managers = [SELECT id, username, profile.name, isActive 
                               FROM User 
                               WHERE isActive=true 
                               		 AND profile.name = 'Resolution Manager' ORDER BY username DESC];
        if(managers.size() < escalatedNo){
            return managers.get(managers.size()-1);
        }else{
            return managers.get(escalatedNo-1);
        }
    }
    
	public static User getAvailableResultionManagerByNo(Integer escalatedNo){
		System.debug('TriggerUtilities::getAvailableResultionManagerByNo');
        List<User> managers = [SELECT id, username, profile.name, isActive 
                               FROM User 
                               WHERE isActive=true 
                               		 AND profile.name = 'Resolution Manager' ORDER BY username DESC];
        if(managers.size() < escalatedNo){
            return managers.get(managers.size()-1);
        }else{
            return managers.get(escalatedNo-1);
        }
    }
	*/
    public static User getAvailableResolutionManagerByCap(){
        try {
            System.debug('TriggerUtilities::getAvailableResultionManagerByCap');

            List<User> managers = [
                    SELECT id, username, profile.name, isActive
                    FROM User
                    WHERE isActive = true
                    AND profile.name = 'Resolution Manager'
                    ORDER BY username
            ];

            AggregateResult[] caseNums = [
                    SELECT Resolution_Manager__c, count(Id) sum
                    FROM Cases__c
                    WHERE Status__c = 'Escalated'
                    AND (Product_Type__c = 'Social Marketing' OR Product_Type__c = 'AdWords Management' OR Product_Type__c = 'Social')
                    AND CaseType__c = 'Cancellation'
                    AND Resolution_Manager__c IN :managers
                    GROUP BY Resolution_Manager__c
                    ORDER BY count(Id) ASC
            ];
            String userId = '' + caseNums[0].get('Resolution_Manager__c');
            User mag = [
                    SELECT id, username, isActive
                    FROM User
                    WHERE isActive = true
                    AND Id = :userId
            ];
            return mag;
        } catch (Exception ex ){
            // init time
            return [SELECT id, username,isActive FROM User WHERE isActive = true AND Profile.Name= 'Resolution Manager' LIMIT 1];
        }

    }
        
   
}