src/objects/Competitor_Website__c.object
<CustomObject>
    <fields>
        <fullName>SEO_Website__c</fullName>
        <label>SEO Website</label>
        <referenceTo>seoWebsite__c</referenceTo>
        <relationshipLabel>Competitor Websites</relationshipLabel>
        <relationshipName>Competitor_Websites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Competitor Website</label>
    <nameField>
        <label>Competitor Website Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Websites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/seoThemeKeywords__c.object
<CustomObject>
    <fields>
        <fullName>Geolocation__c</fullName>
        <inlineHelpText>Override the SEO website&apos;s default geolocation to use a specific geolocation for this keyword only. Leave blank to use the SEO website&apos;s default setting.</inlineHelpText>
        <label>Geolocation</label>
        <picklist>
            <picklistValues>
                <fullName>Adelaide,South Australia,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Springs,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auckland,Auckland,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballarat,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast,Northern Ireland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brisbane,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundaberg,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caboolture,Caboolture,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cairns,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridge,Waikato,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canberra,Australian Capital Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chermside,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago,Illinois,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christchurch,Canterbury,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darwin,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubbo,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geelong,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow,Scotland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Coast,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gympie,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hervey Bay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hobart,Tasmania,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Houston,Texas,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lismore,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles,California,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mackay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maroochydore,Queensland,Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Google_Current__c</fullName>
        <label>Current</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Google_Volume__c</fullName>
        <label>Search Volume</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>seoWebsites__c</fullName>
        <label>seoWebsites</label>
        <referenceTo>seoWebsite__c</referenceTo>
        <relationshipLabel>SEO Keywords</relationshipLabel>
        <relationshipName>seoThemeKeywords</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SEO Keyword</label>
    <nameField>
        <label>Keyword</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/seoWebsite__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Geolocation__c</fullName>
        <globalPicklist>geolocations</globalPicklist>
        <inlineHelpText>The geolocation that keyword ranking refers to.</inlineHelpText>
        <label>Geolocation</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Crawl_Completed_Date__c</fullName>
        <label>Last Crawl Completed Date</label>
        <summarizedField>seoThemeKeywords__c.Last_Crawl_Date__c</summarizedField>
        <summaryFilterItems>
            <field>seoThemeKeywords__c.Last_Crawl_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>seoThemeKeywords__c.seoWebsites__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Prospect_Keywords__c</fullName>
        <label>Prospect Keywords</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Searching_From__c</fullName>
        <label>Search filter</label>
        <picklist>
            <picklistValues>
                <fullName>The Web</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pages from Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>website_url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>SEO Website</label>
    <nameField>
        <label>SEO Website</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Websites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SeoCompetitorController.cls
public with sharing class SeoCompetitorController {

	public seoWebsite__c seoWebsite {get;set;}
    public List<Competitor_Website__c> competitorList {get;set;}
    public Competitor_Website__c newCompetitor {get;set;}
    public List<seoThemeKeywords__c> seoKeywords {get;set;}

    private Map<String, Object> responseObj;

    public SeoCompetitorController(ApexPages.StandardController controller){
        if (!Test.isRunningTest()) controller.addFields(new String[]{'Id', 'Name', 'Prospect_Keywords__c', 'RecordType.Name', 'website_url__c', 'Geolocation__c', 'Searching_From__c', 'Last_Crawl_Completed_Date__c'});
        this.seoWebsite = (seoWebsite__c)controller.getRecord();

        this.competitorList = [SELECT Name FROM Competitor_Website__c WHERE SEO_Website__c = :seoWebsite.Id];

        // Add the keywordids that we want the data for
        this.seoKeywords = [
            SELECT Id, Name, Google_Current__c, Google_Volume__c, Google_Title__c, Google_Snippet__c, Google_Pos_1_URL__c, Google_Pos_1_Title__c, Google_Pos_1_Snippet__c, Geolocation_Effective__c
            FROM seoThemeKeywords__c 
            WHERE seoWebsites__c = :seoWebsite.Id
            ORDER BY Google_Current__c ASC];

        newCompetitor = new Competitor_Website__c();

		// Load the data from the console
        this.loadExternalData();
	}
    
    // Add a competitor
    public PageReference addRow(){

    	this.competitorList.add(newCompetitor);

		// Reload the data from the console
        this.loadExternalData();

        // Insert the record (must come after the callout)
    	newCompetitor.SEO_Website__c = seoWebsite.Id;
        insert newCompetitor;

		// Reset so another new record can be added
        newCompetitor = new Competitor_Website__c();

        return null;
    }
    
    // Delete a competitor for this website
    public PageReference delRow(){
        String competitorId = apexpages.currentpage().getparameters().get('competitorId');

        if (competitorId != null){
			for(Integer i = competitorList.size() - 1; i >= 0; i--) {
	        	if (competitorList[i].Id == competitorId){
	        		this.competitorList.remove(i);
	        	}
	        }

			// Reload the data from the console
	        this.loadExternalData();

			// Delete the record (must come after the callout)
			delete [SELECT Id, Name FROM Competitor_Website__c WHERE Id = :competitorId AND SEO_Website__c = :seoWebsite.Id];
		}

		return null;
    }

    // Load the data from the console
    private void loadExternalData(){
        // Build the URL for the console
        String consolePath = getDataURL();
        
        system.debug('consolePath: ' + consolePath);

        if (consolePath != null) {
            String responseJson = slxConsole.getConsolePage(consolePath);

            system.debug('responseJson: ' + responseJson);

	        this.responseObj = (Map<String, Object>) JSON.deserializeUntyped(responseJson);

	        system.debug('responseObj: ' + responseObj);
	    }
	}

    public String getDataURL() {
        String geolocation = '';

        if (seoWebsite.geolocation__c != null) {
            geolocation = seoWebsite.geolocation__c;
        }

        String consolePath = '/seo/keywordCompetitors' 
        + '?searchFilter='+EncodingUtil.urlEncode(seoWebsite.Searching_From__c, 'UTF-8')
        + '&geolocation='+EncodingUtil.urlEncode(geolocation, 'UTF-8')
        + '&websiteid=' + EncodingUtil.urlEncode(seoWebsite.Id, 'UTF-8')
        + '&domain=' + EncodingUtil.urlEncode(seoWebsite.website_url__c, 'UTF-8');

        if (seoWebsite.Last_Crawl_Completed_Date__c != null){
            consolePath += '&date=' + Utility.dateFormat(seoWebsite.Last_Crawl_Completed_Date__c, 'YYYY-MM-dd');
        }

        // Add the keywordids that we want the data for
        for (Competitor_Website__c competitor : this.competitorList){
        	if (competitor.Name != null){
	            consolePath += '&cd[]=' + EncodingUtil.urlEncode(competitor.Name, 'UTF-8');
	        }
        }

        String keywordQueryString = getKeywordIdQueryString();
        
        if (keywordQueryString != '') {
            consolePath += keywordQueryString;
        } else {
            return null;
        }

        return consolePath;
    }

    // Get SEO Website competitor comparison table
    public String getDomainChart() {
        String chartData = '';
        
        if (this.responseObj != null){
	        chartData = (String) this.responseObj.get('domainChart');
	    }
        
        return chartData;
    }

    // Get SEO Website competitor comparison table
    public Map<String, Map<String, Integer>> getCompetitorKeywords() {
        Map<String, Map<String, Integer>> keywordList = new Map<String, Map<String, Integer>>();
        
        if (this.responseObj != null){
	        Map<String, Object> keywordsResponse = (Map<String, Object>) this.responseObj.get('keywords');

	        if (keywordsResponse != null){
		        for (seoThemeKeywords__c seoKeyword : this.seoKeywords){
			        Map<String, Object> keywordResponse = (Map<String, Object>) keywordsResponse.get(seoKeyword.Name.toLowerCase());

			        Map<String, Integer> keywordDomains = new Map<String, Integer>();
			        for (Competitor_Website__c competitor : this.competitorList){
			        	Integer domainRank;

				        if (keywordResponse == null){
				        	domainRank = 0;
				        } else {
				        	domainRank = (Integer) keywordResponse.get(competitor.Name.toLowerCase());

				        	if (domainRank == null){
				        		domainRank = 100;
				        	}
				        }

			            keywordDomains.put(competitor.Name, domainRank);
			        }

			        keywordList.put(seoKeyword.Name, keywordDomains);
			    }
			}
	    }
        
        return keywordList;
    }

    // Return to SEO Website page
    public PageReference cancel(){
        PageReference seoWebsitePage = new PageReference('/'+seoWebsite.Id);
        seoWebsitePage.setRedirect(true);
        return seoWebsitePage;
    }

    // Get the querystring of keyword ids for this SEO website
    private String getKeywordIdQueryString() {
        String keywordQueryString = '';

        for (seoThemeKeywords__c seoKeyword : this.seoKeywords){
            keywordQueryString += '&k[]=' + EncodingUtil.urlEncode(seoKeyword.Id, 'UTF-8');
        }
        
        return keywordQueryString;
    }
}