src/objects/Invoice_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>Batch Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Batch_Processed__c</fullName>
        <label>Batch Processed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Batch_Type__c</fullName>
        <label>Batch Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoices</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Batch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Batch Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice Batch</label>
    <nameField>
        <label>Invoice Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Payments__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Batch</label>
        <referenceTo>Invoice_Batch__c</referenceTo>
        <relationshipLabel>Invoice Payments</relationshipLabel>
        <relationshipName>Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_Account_Code__c</fullName>
        <label>Xero Account Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Account_Id__c</fullName>
        <label>Xero Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Id__c</fullName>
        <label>Xero Invoice Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Number__c</fullName>
        <label>Xero Invoice Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Invoice Payment</label>
    <nameField>
        <label>Invoice Payments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sendXeroPaymentsIterable.cls
global class sendXeroPaymentsIterable implements Iterator<Invoice_Payments__c> {

	List<Invoice_Payments__c> invpayments {get;set;}
	Integer i {get;set;}

	private String period = 'Today';
	private String batch_name = '';
	private Date batch_date = Date.today();

	public sendXeroPaymentsIterable(String period) {
		this.period = period;
		System.debug('Period: ' + period);

		this.batch_name = DateTime.now().format('EEEE yyyy-MM-dd') + ' ' + this.period + ' Invoice Batch';
		System.debug('Batch Name: ' + this.batch_name);

		List<Invoice_Batch__c> todaysBatches = [
			SELECT
				Id,
				Name,
				Batch_Date__c,
				Batch_Number__c,
				Batch_Processed__c,
				status__c,
				Batch_Type__c
			FROM
				Invoice_Batch__c
			WHERE
				Batch_Type__c = 'Invoices'
				AND
				status__c = 'Batch Approved'
				AND
				Batch_Processed__c = 'No'
				AND
				Batch_Date__c =: this.batch_date
				AND
				Name =: this.batch_name
		];
		Invoice_Batch__c todaysBatch;

		if(todaysBatches.size() > 0) {
			todaysBatch = todaysBatches[0];
			this.invpayments = [
				SELECT
					Id,
					Name,
					Invoice_Batch__c,
					Payment_Amount__c,
					Payment_Date__c,
					Xero_Account_Code__c,
					Xero_Account_Id__c,
					Xero_Invoice_Id__c,
					Xero_Invoice_Number__c
				FROM
					Invoice_Payments__c
				WHERE
					Invoice_Batch__c =: todaysBatch.Id
			];
		}
		this.i = 0;
	}

	global boolean hasNext() {
		if(this.i >= this.invpayments.size())
			return false;
		else
			return true;
	}

	global Invoice_Payments__c next() {
		return this.invpayments[this.i++];
	}
}