src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Employee</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <description>Leads</description>
    <fields>
        <fullName>Assigned_To_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Employee</value>
            </filterItems>
            <filterItems>
                <field>Account.Employee_Department__c</field>
                <operation>equals</operation>
                <value>Sales</value>
            </filterItems>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Please select an active sales.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To (Old Field)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uncontactable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lead - Old</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads - Old</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CustomLeadSynchToStdLead.cls
public class CustomLeadSynchToStdLead {	
	public List<Lead__c> myCustomLeads{get;set;}
	public Map<Id, Lead__c> newleads{get;set;}

	public CustomLeadSynchToStdLead(Map<Id, Lead__c> customLeads){
		newleads = customLeads;
	}

	public boolean synchToStdLeads(){
		Map<String, Lead__C> mapLeads = new Map<String,Lead__c>();
		
		try{		
			//build custom map
			myCustomLeads = [SELECT Id, Email__c, Assigned_To__c,Assigned_To_Id__c, Lead_Status__c FROM Lead__C WHERE Id IN :newleads.keySet()];
			for(Lead__c item : myCustomLeads){				
				mapLeads.put(item.email__c, item);
			}
			
			
			//build standard map
			List<Lead> leads = [SELECT id, Email, Assigned_To__c,status FROM Lead WHERE Email in :mapLeads.keyset()];
			Map<String , Lead> mapStdLead = new Map<String, Lead>();
			for(Lead item:leads){
				mapStdLead.put(item.Email, item);
			}

			//synch value
			for(String leadEmail : mapStdLead.keySet()){

				if( mapLeads.get(leadEmail) != null){
					Lead__c myLead = (Lead__c)mapLeads.get(leadEmail);
					Lead currentLead = (Lead)mapStdLead.get(leadEmail);
					currentLead.Status = myLead.Lead_Status__c;
					currentLead.Assigned_To__c = myLead.Assigned_To_Id__c;
				}
			}
			update mapStdLead.values();

		}catch(Exception ex){
			System.debug(ex.getMessage());
			return false;
		}

		return true;
	}
}