src/objects/Login__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Config for accessing data from external systems, such as the SLX Console</description>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Login</label>
</CustomObject>

src/objects/seoThemeKeywords__c.object
<CustomObject>
    <fields>
        <fullName>Geolocation__c</fullName>
        <inlineHelpText>Override the SEO website&apos;s default geolocation to use a specific geolocation for this keyword only. Leave blank to use the SEO website&apos;s default setting.</inlineHelpText>
        <label>Geolocation</label>
        <picklist>
            <picklistValues>
                <fullName>Adelaide,South Australia,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Springs,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auckland,Auckland,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballarat,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast,Northern Ireland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brisbane,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundaberg,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caboolture,Caboolture,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cairns,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridge,Waikato,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canberra,Australian Capital Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chermside,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago,Illinois,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christchurch,Canterbury,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darwin,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubbo,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geelong,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow,Scotland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Coast,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gympie,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hervey Bay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hobart,Tasmania,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Houston,Texas,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lismore,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles,California,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mackay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maroochydore,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sydney,New South Wales,Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>seoWebsites__c</fullName>
        <label>seoWebsites</label>
        <referenceTo>seoWebsite__c</referenceTo>
        <relationshipLabel>SEO Keywords</relationshipLabel>
        <relationshipName>seoThemeKeywords</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SEO Keyword</label>
    <nameField>
        <label>Keyword</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/seoWebsite__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Geolocation__c</fullName>
        <globalPicklist>geolocations</globalPicklist>
        <inlineHelpText>The geolocation that keyword ranking refers to.</inlineHelpText>
        <label>Geolocation</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>website_url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>SEO Website</label>
    <nameField>
        <label>SEO Website</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Websites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SeoWebsiteServiceTest.cls
@isTest
private class SeoWebsiteServiceTest {
	
	@isTest
	Private Static void sendSeoReportTest() {
		seoWebsite__c seoWebsite = setupSeoWebsite();

        Test.startTest();

		SeoWebsiteService.sendSeoReport(seoWebsite.id);

		Test.stopTest();
	}


	Private Static seoWebsite__c setupSeoWebsite() {
		// Set mock callout class
		Test.setMock(HttpCalloutMock.class, new consoleHttpCalloutMock());

		// Create a test SEO website
		seoWebsite__c seoWebsite = new seoWebsite__c();
		seoWebsite.Name = 'My SEO Website';
		seoWebsite.website_url__c = 'http://www.example.com.au/';
		seoWebsite.geolocation__c = 'Sydney,New South Wales,Australia';
		insert seoWebsite;

		// Create a test SEO keyword
		seoThemeKeywords__c seoKeyword = new seoThemeKeywords__c();
		seoKeyword.Name = 'My keyword';
		seoKeyword.seoWebsites__c = seoWebsite.Id;
		insert seoKeyword;

		// Create a login custom setting
        Login__c consoleLogin = new Login__c();
        consoleLogin.Name = 'SLXConsole';
        consoleLogin.URL__c = 'http://ec2-52-65-47-83.ap-southeast-2.compute.amazonaws.com/';
        consoleLogin.username__c = 'salesforce';
        consoleLogin.password__c = 'mypass';
        insert consoleLogin;

        return seoWebsite;
	}
}