src/objects/Login__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Config for accessing data from external systems, such as the SLX Console</description>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Login</label>
</CustomObject>

src/objects/seoThemeKeywords__c.object
<CustomObject>
    <fields>
        <fullName>Geolocation__c</fullName>
        <inlineHelpText>Override the SEO website&apos;s default geolocation to use a specific geolocation for this keyword only. Leave blank to use the SEO website&apos;s default setting.</inlineHelpText>
        <label>Geolocation</label>
        <picklist>
            <picklistValues>
                <fullName>Adelaide,South Australia,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Springs,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auckland,Auckland,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballarat,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast,Northern Ireland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brisbane,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundaberg,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caboolture,Caboolture,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cairns,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridge,Waikato,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canberra,Australian Capital Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chermside,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago,Illinois,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christchurch,Canterbury,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darwin,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubbo,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geelong,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow,Scotland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Coast,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gympie,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hervey Bay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hobart,Tasmania,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Houston,Texas,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lismore,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles,California,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mackay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maroochydore,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sydney,New South Wales,Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>seoWebsites__c</fullName>
        <label>seoWebsites</label>
        <referenceTo>seoWebsite__c</referenceTo>
        <relationshipLabel>SEO Keywords</relationshipLabel>
        <relationshipName>seoThemeKeywords</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SEO Keyword</label>
    <nameField>
        <label>Keyword</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/seoWebsite__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Geolocation__c</fullName>
        <globalPicklist>geolocations</globalPicklist>
        <inlineHelpText>The geolocation that keyword ranking refers to.</inlineHelpText>
        <label>Geolocation</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prospect_Keywords__c</fullName>
        <label>Prospect Keywords</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Searching_From__c</fullName>
        <label>Search filter</label>
        <picklist>
            <picklistValues>
                <fullName>The Web</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pages from Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>website_url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>SEO Website</label>
    <nameField>
        <label>SEO Website</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Websites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SeoWebsiteControllerTest.cls
@isTest
private class SeoWebsiteControllerTest {
	
	@isTest
	Private Static void testGetRankHistoryChart() {
		seoWebsite__c seoWebsite = setupSeoWebsite();

        Test.startTest();

		// Load the controller
		ApexPages.currentPage().getParameters().put('id',seoWebsite.id);
		ApexPages.StandardController stdController = new ApexPages.StandardController(seoWebsite);
		SeoWebsiteController seoWebsiteController = new SeoWebsiteController(stdController);

		String chartData = seoWebsiteController.getRankHistoryChart();

		System.assertNotEquals(null, chartData, 'The callout returned a null response.');

		Test.stopTest();
	}


	@isTest
	Private Static void testGetKeywordsRankHistoryChart() {
		seoWebsite__c seoWebsite = setupSeoWebsite();

        Test.startTest();

		// Load the controller
		ApexPages.currentPage().getParameters().put('id',seoWebsite.id);
		ApexPages.StandardController stdController = new ApexPages.StandardController(seoWebsite);
		SeoWebsiteController seoWebsiteController = new SeoWebsiteController(stdController);

		String chartData = seoWebsiteController.getKeywordsRankHistoryChart();
		System.assertNotEquals(null, chartData, 'The callout returned a null response.');

		Test.stopTest();
	}


	@isTest
	Private Static void testGetKeywordsRankHistoryChartProspect() {
		seoWebsite__c seoWebsite = setupSeoWebsite();
		seoWebsite.Prospect_Keywords__c = '[{"keyword":"test keyword","google_organic_position":12,"google_organic_url":"http://www.example.com.au/about/","geolocation":"Sydney,New South Wales,Australia","search_filter":"","last_crawl_time":"2016-12-13 23:22:05"}]';
		update seoWebsite;

        Test.startTest();

		// Load the controller
		ApexPages.currentPage().getParameters().put('id',seoWebsite.id);
		ApexPages.StandardController stdController = new ApexPages.StandardController(seoWebsite);
		SeoWebsiteController seoWebsiteController = new SeoWebsiteController(stdController);

		String chartData = seoWebsiteController.getKeywordsRankHistoryChart();
		System.assertNotEquals(null, chartData, 'The callout returned a null response.');

		Test.stopTest();
	}


	@isTest
	Private Static void testGetProspectKeywordQueryString() {
		seoWebsite__c seoWebsite = setupSeoWebsite();

		seoWebsite.Prospect_Keywords__c = '[{"keyword":"test keyword","google_organic_position":12,"google_organic_url":"http://www.example.com.au/about/","geolocation":"Sydney,New South Wales,Australia","search_filter":"","last_crawl_time":"2016-12-13 23:22:05"}]';
		update seoWebsite;

        Test.startTest();

		// Load the controller
		ApexPages.currentPage().getParameters().put('id',seoWebsite.id);
		ApexPages.StandardController stdController = new ApexPages.StandardController(seoWebsite);
		SeoWebsiteController seoWebsiteController = new SeoWebsiteController(stdController);

		List<Map<String,String>> keywordsMap = seoWebsiteController.getProspectKeywordsMap();

		System.assertNotEquals(null, keywordsMap, 'The callout returned a null response.');

		Test.stopTest();
	}


	@isTest
	Private Static void testGetSparklineMap() {
		seoWebsite__c seoWebsite = setupSeoWebsite();

        Test.startTest();

		// Load the controller
		ApexPages.currentPage().getParameters().put('id',seoWebsite.id);
		ApexPages.StandardController stdController = new ApexPages.StandardController(seoWebsite);
		SeoWebsiteController seoWebsiteController = new SeoWebsiteController(stdController);

		Map<String, String> mySparklines = seoWebsiteController.getSparklineMap();

		System.assertNotEquals(null, mySparklines, 'The callout returned a null response.');

		Test.stopTest();
	}

	Private Static seoWebsite__c setupSeoWebsite() {
		// Set mock callout class
		Test.setMock(HttpCalloutMock.class, new consoleHttpCalloutMock());

		// Create a test SEO website
		seoWebsite__c seoWebsite = new seoWebsite__c();
		seoWebsite.Name = 'My SEO Website';
		seoWebsite.website_url__c = 'http://www.example.com.au/';
		seoWebsite.geolocation__c = 'Sydney,New South Wales,Australia';
		seoWebsite.Searching_From__c = '';
		insert seoWebsite;

		// Create a test SEO keyword
		seoThemeKeywords__c seoKeyword = new seoThemeKeywords__c();
		seoKeyword.Name = 'My keyword';
		seoKeyword.seoWebsites__c = seoWebsite.Id;
		insert seoKeyword;

		// Create a login custom setting
        Login__c consoleLogin = new Login__c();
        consoleLogin.Name = 'SLXConsole';
        consoleLogin.URL__c = 'http://ec2-52-65-47-83.ap-southeast-2.compute.amazonaws.com/';
        consoleLogin.username__c = 'salesforce';
        consoleLogin.password__c = 'mypass';
        insert consoleLogin;

        return seoWebsite;
	}
}