src/objects/Login__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Config for accessing data from external systems, such as the SLX Console</description>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>username__c</fullName>
        <label>username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Login</label>
</CustomObject>

src/classes/slxConsole.cls
public class slxConsole {
    // Return contents of a page from the console
    public static String getBaseURL() {
    
        // Get the configuration from the 'SLXConsole' Login in Custom Settings.
        Login__c consoleLogin = Login__c.getInstance('SLXConsole');

        if (consoleLogin == null) {
            System.debug('Missing Login SLXConsole custom setting');
            return '';
        }

        return consoleLogin.URL__c;
    }

    // Return contents of a page from the console
    public static String getConsolePage(String path) {
    
        // Get the configuration from the 'SLXConsole' Login in Custom Settings.
        Login__c consoleLogin = Login__c.getInstance('SLXConsole');

        if (consoleLogin == null) {
            System.debug('Missing Login SLXConsole custom setting');
            return '';
        }

        String consoleEndpoint = consoleLogin.URL__c;
        String consoleUsername = consoleLogin.username__c;
        String consolePassword = consoleLogin.password__c;
        
//        System.debug('path: ' + path);
    
        HttpRequest req = new HttpRequest();
        req.setEndpoint(consoleEndpoint + path);
        req.setMethod('GET');
        req.setHeader('Cookie','username=' + consoleUsername + '; password=' + consolePassword);
        
        // Create a new http object to send the request object
        // A response object is generated as a result of the request  
        Http http = new Http();
        HTTPResponse res = http.send(req);
        //System.debug('body: ' + res.getBody());
        
        return res.getBody();
    }

    // Call a page from the console asynchronously, (eg for use in triggers)
    @future(callout=true)
    public static void getConsolePageAsync(String path) {
    
        // Get the configuration from the 'SLXConsole' Login in Custom Settings.
        Login__c consoleLogin = Login__c.getInstance('SLXConsole');

        if (consoleLogin == null) {
            System.debug('Missing Login SLXConsole custom setting');
            return;
        }

        String consoleEndpoint = consoleLogin.URL__c;
        String consoleUsername = consoleLogin.username__c;
        String consolePassword = consoleLogin.password__c;
        
//        System.debug('path: ' + path);
    
        HttpRequest req = new HttpRequest();
        req.setEndpoint(consoleEndpoint + path);
        req.setMethod('GET');
        req.setHeader('Cookie','username=' + consoleUsername + '; password=' + consolePassword);
        
        // Create a new http object to send the request object
        // A response object is generated as a result of the request  
        Http http = new Http();
        HTTPResponse res = http.send(req);
        System.debug('body: ' + res.getBody());
    }
}