src/objects/SEO_Report_Schedule__c.object
<CustomObject>
    <description>SEO reports scheduled sending date</description>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SEO Report Schedule</label>
    <nameField>
        <label>SEO Report Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Report Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/scheduleSEOReport.cls
global class scheduleSEOReport implements Schedulable{
	
	
	global void execute(SchedulableContext SC){
		SEO_Report_Schedule__c r = new SEO_Report_Schedule__c();
      	r.Name = 'Fortnightly SEO Reports';
      	r.Status__c = 'Pending';
      	datetime scheduledate = datetime.now().addDays(4);
      	r.Schedule_Date__c = scheduledate;
      	insert r;
	}
	
	public static testMethod void scheduleReportTest() {
		
		Test.startTest();
		
		scheduleSEOReport s = new scheduleSEOReport();
		String sch = '0 0 2 * * ?';
		system.schedule('Test set invoice exclude flag', sch, s);
		
		Test.stopTest();
		
	}
	
	
}