src/objects/seoThemeKeywords__c.object
<CustomObject>
    <fields>
        <fullName>Geolocation__c</fullName>
        <inlineHelpText>Override the SEO website&apos;s default geolocation to use a specific geolocation for this keyword only. Leave blank to use the SEO website&apos;s default setting.</inlineHelpText>
        <label>Geolocation</label>
        <picklist>
            <picklistValues>
                <fullName>Adelaide,South Australia,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Springs,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auckland,Auckland,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballarat,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast,Northern Ireland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brisbane,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundaberg,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caboolture,Caboolture,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cairns,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridge,Waikato,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canberra,Australian Capital Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chermside,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago,Illinois,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christchurch,Canterbury,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darwin,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubbo,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geelong,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow,Scotland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Coast,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gympie,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hervey Bay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hobart,Tasmania,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Houston,Texas,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lismore,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles,California,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mackay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maroochydore,Queensland,Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>seoWebsites__c</fullName>
        <label>seoWebsites</label>
        <referenceTo>seoWebsite__c</referenceTo>
        <relationshipLabel>SEO Keywords</relationshipLabel>
        <relationshipName>seoThemeKeywords</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SEO Keyword</label>
    <nameField>
        <label>Keyword</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/seoWebsite__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Geolocation__c</fullName>
        <globalPicklist>geolocations</globalPicklist>
        <inlineHelpText>The geolocation that keyword ranking refers to.</inlineHelpText>
        <label>Geolocation</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prospect_Keywords__c</fullName>
        <label>Prospect Keywords</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Searching_From__c</fullName>
        <label>Search filter</label>
        <picklist>
            <picklistValues>
                <fullName>The Web</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pages from Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>website_url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>SEO Website</label>
    <nameField>
        <label>SEO Website</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Websites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SeoWebsiteController.cls
public with sharing class SeoWebsiteController {

    public seoWebsite__c seoWebsite {get;set;}

    public SeoWebsiteController(ApexPages.StandardController controller){
        if (!Test.isRunningTest()) controller.addFields(new String[]{'Id', 'Name', 'Prospect_Keywords__c', 'RecordTypeId', 'website_url__c', 'Geolocation__c', 'Searching_From__c'});
        this.seoWebsite = (seoWebsite__c)controller.getRecord();
    }
    
    // Get rank history for all keywords on this SEO Website
    public String getKeywordsRankHistoryChart() {
        String chartData = '';
        
        // Build the URL for the console
        String consolePath = getKeywordsRankHistoryURL();
        
        if (consolePath != null) {
            chartData = slxConsole.getConsolePage(consolePath);
        }
        
        return chartData;
    }

    public String getKeywordsRankHistoryURL() {
        String consolePath;

        if (seoWebsite.Prospect_Keywords__c != null){
            consolePath = '/?c=seo&action=prospectKeywordRankHistoryChart' 
            + '&websiteid=' + EncodingUtil.urlEncode(seoWebsite.Id, 'UTF-8') 
            + '&domain=' + EncodingUtil.urlEncode(seoWebsite.website_url__c, 'UTF-8');
        } else {
            String keywordQueryString = getKeywordIdQueryString();

            if (keywordQueryString != '') {
                consolePath = '/?c=seo&action=keywordRankHistoryChart' 
                + '&websiteid=' + EncodingUtil.urlEncode(seoWebsite.Id, 'UTF-8') 
                + keywordQueryString;
            }
        }

        system.debug('consolePath: ' + consolePath);

        return consolePath;
    }

    // Get SEO Website average rank history chart 
    public String getRankHistoryChart() {
        String chartData = '';
        
        // Build the URL for the console
        String consolePath = getRankHistoryURL();
        
        if (consolePath != null) {
            chartData = slxConsole.getConsolePage(consolePath);
        }
        
        return chartData;
    }

    public String getRankHistoryURL() {
        String consolePath = '/?c=seo&action=websiteRankHistoryChart' 
        + '&websiteid=' + EncodingUtil.urlEncode(seoWebsite.Id, 'UTF-8');

        String keywordQueryString = getKeywordIdQueryString();
        
        if (keywordQueryString != '') {
            consolePath += keywordQueryString;
        } else {
            return null;
        }

        return consolePath;
    }

    // Get Map of sparkline data for keywords in this SEO Website
    public Map<String, String> getSparklineMap() {
        Map<String, String> mySparklines = new Map<String, String>();
        
        // Build the URL for the console
        String consolePath = '/?c=seo&action=keywordSparklineChart' 
        + '&websiteid=' + EncodingUtil.urlEncode(seoWebsite.Id, 'UTF-8');
        
        String keywordQueryString = getKeywordIdQueryString();
        
        if (keywordQueryString != '') {
            consolePath += keywordQueryString;
        
            String chartData = slxConsole.getConsolePage(consolePath);
        
            JSONParser parser = JSON.createParser(chartData);

            while (parser.nextToken() == JSONToken.START_OBJECT) {
                System.debug('getCurrentToken: ' + parser.getCurrentToken());
            
                while (parser.nextToken() != null ) {
                    if (parser.getCurrentToken() != JSONToken.END_OBJECT) {
                
                        // Entering a keyword
                        String keywordid = parser.getText();
                        String sparkline = '';
                
                        while (parser.nextToken() != null && parser.getCurrentToken() != JSONToken.END_OBJECT) {
                
                            if (parser.getCurrentToken() == JSONToken.FIELD_NAME) {
                                String sparkDate = parser.getText();
                                parser.nextToken();
                                String sparkValue = parser.getText();
                                if (sparkValue == 'null') {
                                    sparkValue = ' ';
                                }
                            
                                // Add a comma between values
                                if ( sparkline != '' ) {
                                    sparkline += ', ';
                                }
                            
                                sparkline += sparkValue;
                            }
                        }
                    
                        System.debug('keywordid: ' + keywordid + ' sparkline: ' + sparkline);
                    
                        mySparklines.put(keywordid, sparkline);
                    }
                }
            }
        }
        
        return mySparklines;
    }
    
    
    // Get the querystring of keyword ids for this SEO website
    private String getKeywordIdQueryString() {
        String keywordQueryString = '';

        // Add the keywordids that we want the data for
        List<seoThemeKeywords__c> seoKeywords = [SELECT Id FROM seoThemeKeywords__c WHERE seoWebsites__c = :ApexPages.currentPage().getParameters().get('id')];

        if ( seoKeywords.size() > 0 ) {
            for (seoThemeKeywords__c seoKeyword : seoKeywords){
                keywordQueryString += '&k[]=' + EncodingUtil.urlEncode(seoKeyword.Id, 'UTF-8');
            }
        }
        
        return keywordQueryString;
    }


    // Get the map of prospect keywords
    public List<Map<String,String>> getProspectKeywordsMap() {
        List<Map<String,String>> keywords = (List<Map<String,String>>) JSON.deserialize(seoWebsite.Prospect_Keywords__c, List<Map<String,String>>.class);
        
        // Do some field modifications for the visualforce page
        for (Map<String,String> keyword : keywords){
            keyword.put('last_crawl_date', keyword.get('last_crawl_time').left(10));

            Url googleUrl = new Url(keyword.get('google_organic_url'));
            keyword.put('google_organic_url_relative', googleUrl.getPath());
        }

        return keywords;
    }

}