src/objects/seoThemeKeywords__c.object
<CustomObject>
    <fields>
        <fullName>Geolocation__c</fullName>
        <inlineHelpText>Override the SEO website&apos;s default geolocation to use a specific geolocation for this keyword only. Leave blank to use the SEO website&apos;s default setting.</inlineHelpText>
        <label>Geolocation</label>
        <picklist>
            <picklistValues>
                <fullName>Adelaide,South Australia,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Springs,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auckland,Auckland,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballarat,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast,Northern Ireland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brisbane,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundaberg,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caboolture,Caboolture,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cairns,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridge,Waikato,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canberra,Australian Capital Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chermside,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago,Illinois,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christchurch,Canterbury,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darwin,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubbo,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geelong,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow,Scotland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Coast,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gympie,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hervey Bay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hobart,Tasmania,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Houston,Texas,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lismore,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles,California,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mackay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maroochydore,Queensland,Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sniper_Date__c</fullName>
        <description>Date when sniper was ordered for this keyword</description>
        <label>Sniper Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>seoWebsites__c</fullName>
        <label>seoWebsites</label>
        <referenceTo>seoWebsite__c</referenceTo>
        <relationshipLabel>SEO Keywords</relationshipLabel>
        <relationshipName>seoThemeKeywords</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SEO Keyword</label>
    <nameField>
        <label>Keyword</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/seoWebsite__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Device__c</fullName>
        <label>Device</label>
        <picklist>
            <picklistValues>
                <fullName>Desktop</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geolocation__c</fullName>
        <globalPicklist>geolocations</globalPicklist>
        <inlineHelpText>The geolocation that keyword ranking refers to.</inlineHelpText>
        <label>Geolocation</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Searching_From__c</fullName>
        <label>Search filter</label>
        <picklist>
            <picklistValues>
                <fullName>The Web</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pages from Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>website_url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>SEO Website</label>
    <nameField>
        <label>SEO Website</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Websites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SeoKeywordController.cls
public with sharing class SeoKeywordController {

    private String keyword_id;
    private seoThemeKeywords__c seoThemeKeyword;
    private seoWebsite__c seoWebsite;

    public SeoKeywordController(ApexPages.StandardController controller){
        // Load the keyword and website objects
        if (!Test.isRunningTest()) controller.addFields(new String[]{'Id', 'Name', 'seoWebsites__c', 'geolocation__c', 'Sniper_Date__c'});
        seoThemeKeyword = (seoThemeKeywords__c)controller.getRecord();
        
        this.seoWebsite = [SELECT Id, Name, geolocation__c, website_url__c, Searching_From__c, device__c FROM seoWebsite__c where id =: seoThemeKeyword.seoWebsites__c][0];
    }


    public String getSerpHistoryChart() {
        String chartURL = getSerpHistoryURL();
        String chartData = slxConsole.getConsolePage(chartURL);        
        return chartData;
    }
    
    public String getSerpHistoryURL() {
        String geolocation = '';

        if (seoWebsite.geolocation__c != null) {
            geolocation = seoWebsite.geolocation__c;
        }

        if (seoThemeKeyword.geolocation__c != null) {
            geolocation = seoThemeKeyword.geolocation__c;
        }
        
        return '/?c=seo&action=serpHistoryChart&keyword=' + EncodingUtil.urlEncode(seoThemeKeyword.Name, 'UTF-8') 
        + '&searchFilter='+EncodingUtil.urlEncode(seoWebsite.Searching_From__c, 'UTF-8')
        + '&geolocation='+EncodingUtil.urlEncode(geolocation, 'UTF-8')
        + '&device='+EncodingUtil.urlEncode(Utility.ifnull(seoWebsite.device__c,''), 'UTF-8')
        + '&targetDomain=' + seoWebsite.website_url__c 
        + '&keywordid=' + this.seoThemeKeyword.Id 
        + '&sniperDate=' + Utility.dateFormat(this.seoThemeKeyword.Sniper_Date__c, 'YYYY-MM-dd')
        + '&websiteid=' + EncodingUtil.urlEncode(seoThemeKeyword.seoWebsites__c, 'UTF-8');
    }
    
    public String getRankHistoryChart() {
        String chartURL = getRankHistoryURL();
        String chartData = slxConsole.getConsolePage(chartURL);
        return chartData;
    }

    public String getRankHistoryURL() {
        String geolocation = '';

        if (seoWebsite.geolocation__c != null) {
            geolocation = seoWebsite.geolocation__c;
        }

        if (seoThemeKeyword.geolocation__c != null) {
            geolocation = seoThemeKeyword.geolocation__c;
        }
        
        return '/?c=seo&action=keywordRankHistoryChart&keyword=' + EncodingUtil.urlEncode(seoThemeKeyword.Name, 'UTF-8') 
        + '&searchFilter='+EncodingUtil.urlEncode(seoWebsite.Searching_From__c, 'UTF-8')
        + '&geolocation='+EncodingUtil.urlEncode(geolocation, 'UTF-8')
        + '&device='+EncodingUtil.urlEncode(Utility.ifnull(seoWebsite.device__c,''), 'UTF-8')
        + '&targetDomain=' + seoWebsite.website_url__c 
        + '&keywordid=' + this.seoThemeKeyword.Id 
        + '&sniperDate=' + Utility.dateFormat(this.seoThemeKeyword.Sniper_Date__c, 'YYYY-MM-dd')
        + '&websiteid=' + EncodingUtil.urlEncode(seoThemeKeyword.seoWebsites__c, 'UTF-8');
    }

    public String getLandingPagesHistoryChart() {
        String chartURL = getLandingPagesHistoryChartURL();
        String chartData = slxConsole.getConsolePage(chartURL);        
        return chartData;
    }
    
    public String getLandingPagesHistoryChartURL() {
        String geolocation = '';

        if (seoWebsite.geolocation__c != null) {
            geolocation = seoWebsite.geolocation__c;
        }

        if (seoThemeKeyword.geolocation__c != null) {
            geolocation = seoThemeKeyword.geolocation__c;
        }
        
        return '/?c=seo&action=serpHistoryChart&keyword=' 
        + EncodingUtil.urlEncode(seoThemeKeyword.Name, 'UTF-8') 
        + '&sitesearch=1&searchFilter='+EncodingUtil.urlEncode(seoWebsite.Searching_From__c, 'UTF-8')
        + '&geolocation='+EncodingUtil.urlEncode(geolocation, 'UTF-8')
        + '&device='+EncodingUtil.urlEncode(Utility.ifnull(seoWebsite.device__c,''), 'UTF-8')
        + '&targetDomain=' + seoWebsite.website_url__c 
        + '&keywordid=' + this.seoThemeKeyword.Id 
        + '&sniperDate=' + Utility.dateFormat(this.seoThemeKeyword.Sniper_Date__c, 'YYYY-MM-dd')
        + '&websiteid=' + EncodingUtil.urlEncode(seoThemeKeyword.seoWebsites__c, 'UTF-8') 
        + '&maxpositions=10';
    }
}