src/objects/seoThemeKeywords__c.object
<CustomObject>
    <fields>
        <fullName>Geolocation__c</fullName>
        <inlineHelpText>Override the SEO website&apos;s default geolocation to use a specific geolocation for this keyword only. Leave blank to use the SEO website&apos;s default setting.</inlineHelpText>
        <label>Geolocation</label>
        <picklist>
            <picklistValues>
                <fullName>Adelaide,South Australia,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Springs,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auckland,Auckland,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballarat,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast,Northern Ireland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brisbane,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundaberg,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caboolture,Caboolture,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cairns,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridge,Waikato,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canberra,Australian Capital Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chermside,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago,Illinois,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christchurch,Canterbury,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darwin,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubbo,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geelong,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow,Scotland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Coast,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gympie,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hervey Bay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hobart,Tasmania,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Houston,Texas,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lismore,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles,California,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mackay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maroochydore,Queensland,Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Google_Current__c</fullName>
        <label>Current</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>seoWebsites__c</fullName>
        <label>seoWebsites</label>
        <referenceTo>seoWebsite__c</referenceTo>
        <relationshipLabel>SEO Keywords</relationshipLabel>
        <relationshipName>seoThemeKeywords</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SEO Keyword</label>
    <nameField>
        <label>Keyword</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/seoWebsite__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Geolocation__c</fullName>
        <globalPicklist>geolocations</globalPicklist>
        <inlineHelpText>The geolocation that keyword ranking refers to.</inlineHelpText>
        <label>Geolocation</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prospect_Keywords__c</fullName>
        <label>Prospect Keywords</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>website_url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>SEO Website</label>
    <nameField>
        <label>SEO Website</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Websites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SeoGeoController.cls
public with sharing class SeoGeoController {

    public seoWebsite__c seoWebsite {get;set;}
    public boolean refreshRequired {get;set;}

    public string device {get;set;}

    public SelectOption[] selectedGeo { get; set; }
    public SelectOption[] allGeo { get; set; }


    public SeoGeoController(ApexPages.StandardController controller){
        if (!Test.isRunningTest()) controller.addFields(new String[]{'Id', 'Name', 'Prospect_Keywords__c', 'RecordTypeId', 'website_url__c', 'Geolocation__c'});
        this.seoWebsite = (seoWebsite__c)controller.getRecord();

        this.refreshRequired = true;

        // Initialize default values
        this.device = 'desktop';

        // Generate geolocation Select Options
        selectedGeo = new List<SelectOption>();
        allGeo = new List<SelectOption>();
        
        Schema.DescribeFieldResult geoField = seoWebsite__c.Geolocation__c.getDescribe();
        List<Schema.PicklistEntry> ple = geoField.getPicklistValues();

        for( Schema.PicklistEntry f : ple){
            allGeo.add(new SelectOption(f.getValue(), f.getLabel()));
        }
    }

    // Get the options for devices
    public List<SelectOption> getDeviceOptions() {
        List<SelectOption> deviceOptions = new List<SelectOption>();
        deviceOptions.add(new SelectOption('desktop','Desktop'));
        deviceOptions.add(new SelectOption('mobile','Mobile'));

        return deviceOptions;
    }

    // Get the querystring of keyword ids for this SEO website
    private String getKeywordIdQueryString() {
        String keywordQueryString = '';

        List<seoThemeKeywords__c> seoKeywords;

        // Add the keywordids that we want the data for.
        if (ApexPages.currentPage().getParameters().get('keywordid') != null){
            // Optionally restrict to a single keyword
            seoKeywords = [SELECT Id FROM seoThemeKeywords__c WHERE seoWebsites__c = :ApexPages.currentPage().getParameters().get('id') AND Id = :ApexPages.currentPage().getParameters().get('keywordid') ORDER BY Google_Current__c];
        } else {
            // Otherwise use all keywords for this website
            seoKeywords = [SELECT Id FROM seoThemeKeywords__c WHERE seoWebsites__c = :ApexPages.currentPage().getParameters().get('id') ORDER BY Google_Current__c];
        }

        if ( seoKeywords.size() > 0 ) {
            for (seoThemeKeywords__c seoKeyword : seoKeywords){
                keywordQueryString += '&k[]=' + EncodingUtil.urlEncode(seoKeyword.Id, 'UTF-8');
            }
        }

        return keywordQueryString;
    }

    // Submit the selected geolocations
    public PageReference submit(){
        // We now allow zero geolocations, because you may want to just compare to mobile
//        if (selectedGeo.size() <= 0){
//            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please select at least one Geolocation to compare'));
//        }

        return null;
    }

    // Return to SEO Website page
    public PageReference cancel(){
        PageReference seoWebsitePage = new PageReference('/'+seoWebsite.Id);
        seoWebsitePage.setRedirect(true);
        return seoWebsitePage;
    }

    // Get geo comparison table
    public String getGeoTable() {
        String geoTable;

        // Build the URL for the console
        String consolePath = getGeoURL();
        
        if (consolePath != null) {
            geoTable = slxConsole.getConsolePage(consolePath);
        }

        // Check if there are any 'loading' cells in the page, so we can stop re-loading.
        if (geoTable == null || geoTable.contains('geoloading')){
            this.refreshRequired = true;
        } else {
            this.refreshRequired = false;
        }

        return geoTable;
    }

    // Get geo comparison url
    public String getGeoURL() {
        // Build the URL for the console
        String consolePath = '/seo/keywordGeoCompare?output=table&websiteid=' + EncodingUtil.urlEncode(seoWebsite.Id, 'UTF-8');

        for ( SelectOption so : selectedGeo ) {
            consolePath += '&g[]=' + EncodingUtil.urlEncode(so.getValue(), 'UTF-8');
        }

        if (seoWebsite.Geolocation__c != null){
            consolePath += '&geolocation=' + EncodingUtil.urlEncode(seoWebsite.Geolocation__c, 'UTF-8');
        }

        if (this.device == 'mobile'){
            consolePath += '&device=mobile';
        }

        String keywordQueryString = getKeywordIdQueryString();
        
        if (keywordQueryString != '') {
            consolePath += keywordQueryString;
        } else {
            return null;
        }

        return consolePath;
    }
}