src/objects/seoThemeKeywords__c.object
<CustomObject>
    <fields>
        <fullName>Geolocation__c</fullName>
        <inlineHelpText>Override the SEO website&apos;s default geolocation to use a specific geolocation for this keyword only. Leave blank to use the SEO website&apos;s default setting.</inlineHelpText>
        <label>Geolocation</label>
        <picklist>
            <picklistValues>
                <fullName>Adelaide,South Australia,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alice Springs,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auckland,Auckland,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballarat,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belfast,Northern Ireland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brisbane,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundaberg,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caboolture,Caboolture,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cairns,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambridge,Waikato,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canberra,Australian Capital Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chermside,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago,Illinois,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Christchurch,Canterbury,New Zealand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Darwin,Northern Territory,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubbo,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geelong,Victoria,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasgow,Scotland,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Coast,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gympie,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hervey Bay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hobart,Tasmania,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Houston,Texas,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lismore,New South Wales,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles,California,United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mackay,Queensland,Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manchester,England,United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maroochydore,Queensland,Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>seoWebsites__c</fullName>
        <label>seoWebsites</label>
        <referenceTo>seoWebsite__c</referenceTo>
        <relationshipLabel>SEO Keywords</relationshipLabel>
        <relationshipName>seoThemeKeywords</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SEO Keyword</label>
    <nameField>
        <label>Keyword</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Keywords</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/seoWebsite__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>seoWebsites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geolocation__c</fullName>
        <globalPicklist>geolocations</globalPicklist>
        <inlineHelpText>The geolocation that keyword ranking refers to.</inlineHelpText>
        <label>Geolocation</label>
        <type>Picklist</type>
    </fields>
    <label>SEO Website</label>
    <nameField>
        <label>SEO Website</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEO Websites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BulkKeywordsInsert.cls
public with sharing class BulkKeywordsInsert {
	public String bulk_keywords {set; get;}
	public String website_name {get;set;}
	private String website_id {get;set;}
	public String geolocation {get;set;}
	public seoThemeKeywords__c seoThemeKeyword {get;set;}

	public BulkKeywordsInsert(ApexPages.StandardController controller){
		seoThemeKeyword 	= (seoThemeKeywords__c)controller.getRecord();
		this.website_id 	= seoThemeKeyword.seoWebsites__c;
		
		try{
			this.website_name = [select Name from seoWebsite__c where id =: seoThemeKeyword.seoWebsites__c][0].Name;
		}catch(Exception e){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'No SEO website found'));
		}
	}
	
	public PageReference save(){
		try{
			String[] keywords_array = this.bulk_keywords.split('\n');
			List<seoThemeKeywords__c> keywords = new List<seoThemeKeywords__c>();
			for(String keyword_name : keywords_array){
				if(keyword_name.trim() != ''){
					seoThemeKeywords__c keyword = new seoThemeKeywords__c();
					keyword.seoWebsites__c      = this.website_id;
					keyword.Name 				= keyword_name;

					system.debug('geolocation: ' + this.geolocation);
					system.debug('Geolocation__c: ' + this.seoThemeKeyword.Geolocation__c);

					if (this.seoThemeKeyword.Geolocation__c != null){
						keyword.Geolocation__c		= this.seoThemeKeyword.Geolocation__c;
					}

					keywords.add(keyword);	
				}
			}
			insert keywords;
		}catch(Exception e){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'why not working here? '+e));
			return null;
		}
		PageReference seoWebsitePage = new PageReference('/'+this.website_id);
        seoWebsitePage.setRedirect(true);
        return seoWebsitePage;
	}
	
	public PageReference cancel(){
		PageReference seoWebsitePage = new PageReference('/'+this.website_id);
        seoWebsitePage.setRedirect(true);
        return seoWebsitePage;
	}
	
	public static testMethod void bulkKeywordsInsertTest() {
		Test.StartTest();
		
		Account acc = new Account();
		acc.name = 'acc1';
		insert acc;
		
		seoWebsite__c seowebsite = new seoWebsite__c();
		seowebsite.Name = 'testwebsite';
		seowebsite.Account__c = acc.Id;
		insert seowebsite;	
		
		seoThemeKeywords__c keyword = new seoThemeKeywords__c();
		keyword.Name = 'test';
		keyword.seoWebsites__c = seowebsite.Id;
			
		
		ApexPages.standardController controller = new ApexPages.standardController(keyword);
		BulkKeywordsInsert con = new BulkKeywordsInsert(controller);
		
		con.bulk_keywords = 'test1';
		con.save();
		con.cancel();
			
		Test.stopTest();
	}
	
	public static testMethod void bulkKeywordsInsertTest1() {
		Test.StartTest();
		
		
		seoThemeKeywords__c keyword = new seoThemeKeywords__c();
		
			
		
		ApexPages.standardController controller = new ApexPages.standardController(keyword);
		BulkKeywordsInsert con = new BulkKeywordsInsert(controller);
		
		con.bulk_keywords = 'test1';
		con.save();
		con.cancel();
			
		Test.stopTest();
	}
	
	
	
	
	
	
	
	

}