src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Signup_Payments__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Signup Payments</relationshipLabel>
        <relationshipName>Signup_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Response__c</fullName>
        <label>Last Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sign_Up__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sign Up</label>
        <referenceTo>Sign_Up__c</referenceTo>
        <relationshipLabel>Signup Payments</relationshipLabel>
        <relationshipName>Signup_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Signup Payment</label>
    <nameField>
        <label>Signup Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signup Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/xeroSignupPaymentsIterable.cls
global class xeroSignupPaymentsIterable implements Iterator<Signup_Payments__c> {
	
	List<Signup_Payments__c> signupPayment {get;set;} 
	Integer i {get;set;}
	
	public xeroSignupPaymentsIterable() {
		this.signupPayment = [SELECT Id,Name,Account__c,Sign_Up__c,Amount__c,CreatedDate,Last_Response__c FROM Signup_Payments__c];
		this.i = 0;		
	}
	global boolean hasNext() {
		if(this.i >= this.signupPayment.size()) 
        	return false; 
		else 
        	return true;	
	}
	global Signup_Payments__c next() {
   		return this.signupPayment[this.i++];	
	}
	
}