src/objects/Sign_Up__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sign Ups</relationshipLabel>
        <relationshipName>Sign_Ups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>AdWords Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admob Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConvertoPages</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending 1st Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending CM Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold to Pause</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sign Up</label>
    <nameField>
        <label>Sign Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sign Ups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GMTGOWebservice_TEST.cls
@isTest(SeeAllData=true)
global class GMTGOWebservice_TEST {

    // ***********************************
    // ** TEST Methods for Webservices  **
    // ***********************************

    static testMethod void test_user_authenticate() {
        //GMTGOWebservice.WebServiceAuthenticate response = new GMTGOWebservice.user_authenticate('test@test.com','testpassword');
    }
    static testMethod void test_forget_password() {
        
    }
    static testMethod void test_update_password() {
        
    }
    
    public static testMethod void testRunAs() {
      // Setup test data
      // This code runs as the system user
     Profile p = [SELECT Id FROM Profile WHERE Name='GMTGO Profile'];
	 User u = [select Id from User where Profile.Id =:p.ID limit 1][0];

      System.runAs(u) {
         // The following code runs as user 'u' 
         System.debug('Current User: ' + UserInfo.getUserName());
         System.debug('Current Profile: ' + UserInfo.getProfileId()); 
         //GMTGOWebservice.dashboard('0016F00001pqWgpQAE','7090184323','2017-04-04','2017-04-10');
         Sign_Up__c[] signups = [SELECT Status__c,CreatedDate FROM Sign_Up__c WHERE Account__c ='0016F00001pqWgpQAE' and Product_Type__c = 'AdWords Management' order by CreatedDate DESC];
         system.debug(signups);
         
         signups = [SELECT Status__c,CreatedDate FROM Sign_Up__c WHERE Product_Type__c = 'AdWords Management' order by CreatedDate DESC limit 2];
         system.debug(signups);
         
         signups = [SELECT Status__c,CreatedDate FROM Sign_Up__c order by CreatedDate DESC limit 2];
         system.debug(signups);
      }
      
      Sign_Up__c[] signups = [SELECT Status__c,CreatedDate FROM Sign_Up__c WHERE Account__c ='0016F00001pqWgpQAE' and Product_Type__c = 'AdWords Management' order by CreatedDate DESC];
      system.debug(signups);
   }
}