src/objects/Snapshot_Keyword_Unrank__c.object
<CustomObject>
    <description>Snapshot Keyword Unrank</description>
    <fields>
        <fullName>Google_Unranked_Count_DaysAgo2__c</fullName>
        <description>Google Unranked Count DaysAgo2</description>
        <inlineHelpText>Google Unranked Count DaysAgo2</inlineHelpText>
        <label>Google Unranked Count DaysAgo2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Google_Unranked_Count__c</fullName>
        <description>Google Unranked Count</description>
        <inlineHelpText>Google Unranked Count</inlineHelpText>
        <label>Google Unranked Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Google_Unranked_Increase_2_days__c</fullName>
        <description>Google Unranked Increase 2 days</description>
        <inlineHelpText>Google Unranked Increase 2 days</inlineHelpText>
        <label>Google Unranked Increase 2 days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Keyword_Count__c</fullName>
        <description>Keywords</description>
        <inlineHelpText>Keywords</inlineHelpText>
        <label>Keywords</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Owner_Email__c</fullName>
        <description>Project Owner Email</description>
        <inlineHelpText>Project Owner Email</inlineHelpText>
        <label>Project Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Owner_Name__c</fullName>
        <description>Owner</description>
        <inlineHelpText>Owner</inlineHelpText>
        <label>Project Owner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SEO_Website__c</fullName>
        <description>Snapshot Keyword Unrank</description>
        <inlineHelpText>Snapshot Keyword Unrank</inlineHelpText>
        <label>SEO Website</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>website_url__c</description>
        <inlineHelpText>website_url__c</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Snapshot Keyword Unrank</label>
    <nameField>
        <displayFormat>SEO-{00000}</displayFormat>
        <label>Snapshot Keyword Unrank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Keyword Unranks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SnapshotNotification.cls
public with sharing class SnapshotNotification {

	//public String objectName {get;set;}
	//public String senderEmail {get;set;}
	public Messaging.SingleEmailMessage[] mails = new List<Messaging.SingleEmailMessage>();
	

	public SnapshotNotification(){
		setupNotificationContent();
		sendoutNotification();
	}

	private void setupNotificationContent(){
	//get the email template
        EmailTemplate template = [Select id, HtmlValue from EmailTemplate where name = 'SEO Keyword Unrank Notification'];


		//get records
		List<Snapshot_Keyword_Unrank__c>  records = [SELECT id, Name,Project_Owner_Email__c ,Google_Unranked_Count__c , Google_Unranked_Count_DaysAgo2__c, Google_Unranked_Increase_2_days__c ,Project_Owner_Name__c, 
															Keyword_Count__c, SEO_Website__c, URL__c 
													 FROM Snapshot_Keyword_Unrank__c 
													 WHERE CreatedDate = TODAY];

		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();											 
		String emailBody = '';
		String htmlBody = '';		

		for( Snapshot_Keyword_Unrank__c item: records){
			if((item.Project_Owner_Email__c  <> null) && (item.Project_Owner_Email__c  <> '')){
				// get user records
		        
				try{	
			    emailBody = '';
		            mail = new Messaging.SingleEmailMessage();
		            // get template
		            mail.setTemplateID(template.Id); 
		            String[] toAddresses = new String[]{};
		            toAddresses.add(item.Project_Owner_Email__c);

		            
		            // set email content
		            mail.setToAddresses(toAddresses);
		            mail.setSenderDisplayName('SeoKeywords');
                    mail.setSubject('SEO Notification for increase in unranked keywords');
		            mail.setBccSender(false);
		            mail.setUseSignature(false);
		            htmlBody = template.HtmlValue;
		            //htmlBody = htmlBody.replace('{!Snapshot_Keyword_Unrank__c.Google_Unranked_Increase_2_days__c}', item.Google_Unranked_Increase_2_days__c.toPlainString());
		            htmlBody = htmlBody.replace('{!Snapshot_Keyword_Unrank__c.Google_Unranked_Count__c}', ''+item.Google_Unranked_Count__c.toPlainString());
		            htmlBody = htmlBody.replace('{!Snapshot_Keyword_Unrank__c.Google_Unranked_Count_DaysAgo2__c}', ''+item.Google_Unranked_Count_DaysAgo2__c.toPlainString());
		            htmlBody = htmlBody.replace('{!Snapshot_Keyword_Unrank__c.Keyword_Count__c}', ''+item.Keyword_Count__c.toPlainString());
		            htmlBody = htmlBody.replace('{!Snapshot_Keyword_Unrank__c.Project_Owner_Name__c}', item.Project_Owner_Name__c);
		            htmlBody = htmlBody.replace('{!Snapshot_Keyword_Unrank__c.URL__c}', item.URL__c);
		            htmlBody = htmlBody.replace('{!Snapshot_Keyword_Unrank__c.SEO_Website__c}', item.SEO_Website__c);
		            mail.setHtmlBody(htmlBody);        
		            mails.add(mail);
	            } catch (Exception e) {
	            	  mail = new Messaging.SingleEmailMessage();
		              emailBody = 'Cannot get email address from CM ' + e.getMessage();
		              String[] toAddresses = new String[] {'hanh.luu@sponsoredlinx.com'};
		              mail.setSaveAsActivity(false);
		              mail.setToAddresses(toAddresses);
		              mail.setSubject('SeoKeywords Notification Error');
		              mail.setSenderDisplayName('SeoKeywords Notification Error');		              
		              mail.setBccSender(false);
		              mail.setUseSignature(false);
		              mail.setHtmlBody(emailBody);
		              Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		              return;
	            }
			}
			
		}
	}

	private void sendoutNotification(){
        try{
        	if ( !Test.isRunningTest() ){
		          Messaging.sendEmail(mails);
		    }
          }catch(Exception e){
            System.debug(e.getMessage());
          }
    }
	
}