src/objects/Snapshot_Keyword_Unrank__c.object
<CustomObject>
    <description>Snapshot Keyword Unrank</description>
    <fields>
        <fullName>Google_Unranked_Count_DaysAgo2__c</fullName>
        <description>Google Unranked Count DaysAgo2</description>
        <inlineHelpText>Google Unranked Count DaysAgo2</inlineHelpText>
        <label>Google Unranked Count DaysAgo2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Google_Unranked_Count__c</fullName>
        <description>Google Unranked Count</description>
        <inlineHelpText>Google Unranked Count</inlineHelpText>
        <label>Google Unranked Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Google_Unranked_Increase_2_days__c</fullName>
        <description>Google Unranked Increase 2 days</description>
        <inlineHelpText>Google Unranked Increase 2 days</inlineHelpText>
        <label>Google Unranked Increase 2 days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Keyword_Count__c</fullName>
        <description>Keywords</description>
        <inlineHelpText>Keywords</inlineHelpText>
        <label>Keywords</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Owner_Email__c</fullName>
        <description>Project Owner Email</description>
        <inlineHelpText>Project Owner Email</inlineHelpText>
        <label>Project Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Owner_Name__c</fullName>
        <description>Owner</description>
        <inlineHelpText>Owner</inlineHelpText>
        <label>Project Owner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SEO_Website__c</fullName>
        <description>Snapshot Keyword Unrank</description>
        <inlineHelpText>Snapshot Keyword Unrank</inlineHelpText>
        <label>SEO Website</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>website_url__c</description>
        <inlineHelpText>website_url__c</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Snapshot Keyword Unrank</label>
    <nameField>
        <displayFormat>SEO-{00000}</displayFormat>
        <label>Snapshot Keyword Unrank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Keyword Unranks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SnapshotNotificationTest.cls
@isTest
private class SnapshotNotificationTest
{

	@testSetup static void setup(){

	}

	@isTest
	static void testSuccessCase()
	{

			// create email template
			EmailTemplate e = new EmailTemplate (developerName = 'SEO Keyword Unrank Notification', HtmlValue = '', TemplateType= 'Custom', Name = 'SEO Keyword Unrank Notification');
			e.HtmlValue += '{!Snapshot_Keyword_Unrank__c.Google_Unranked_Increase_2_days__c} ';
			e.HtmlValue += '{!Snapshot_Keyword_Unrank__c.Google_Unranked_Count__c} ';
			e.HtmlValue += '{!Snapshot_Keyword_Unrank__c.Google_Unranked_Count_DaysAgo2__c} ';
			e.HtmlValue += ' {!Snapshot_Keyword_Unrank__c.Keyword_Count__c} ';
			e.HtmlValue += '{!Snapshot_Keyword_Unrank__c.Project_Owner_Name__c} ';
			e.HtmlValue += '{!Snapshot_Keyword_Unrank__c.URL__c} ';
			e.HtmlValue += '{!Snapshot_Keyword_Unrank__c.SEO_Website__c} ';

			// create Snapshot_Keyword_Unrank__c
			List<Snapshot_Keyword_Unrank__c> words = new List<Snapshot_Keyword_Unrank__c>();
			for (integer i =0; i< 5;i++){
				Snapshot_Keyword_Unrank__c word = new Snapshot_Keyword_Unrank__c();
				word.Project_Owner_Email__c = 'test' + i +'@gmail.com';
				word.Google_Unranked_Count__c = 9;
				word.Google_Unranked_Count_DaysAgo2__c = 1;
				word.Google_Unranked_Increase_2_days__c = 26.35;
				word.Project_Owner_Name__c = 'Test';
				word.Keyword_Count__c = 28;
				word.SEO_Website__c= 'http://www.abc.com.au';
				word.URL__c = 'http://www.abc.com.au';

				words.add(word);
			}
			insert words;

			SnapshotNotification myTest = new SnapshotNotification();
			System.assertNotEquals(myTest.mails.size(),0);
	}


	@isTest
	static void testFailCase()
	{
		
			// create Snapshot_Keyword_Unrank__c
			DmlException d = new DmlException();
			Test.startTest();
			SnapshotNotification myTest = new SnapshotNotification();	
			Test.stopTest();
			
			
	}

}