src/objects/ss_NonLogin__c.object
<CustomObject>
    <description>snapshot of daily non login user</description>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application</description>
        <inlineHelpText>Application</inlineHelpText>
        <label>Application</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firstname__c</fullName>
        <label>Firstname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastLogin__c</fullName>
        <label>Last Login</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lastname__c</fullName>
        <label>Lastname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <label>Profile</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Snapshot Non Login</label>
    <nameField>
        <label>SnapshotNonLogin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SnapshotNonLogins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DailyLoginHistory.cls
public class DailyLoginHistory {
	

	public DailyLoginHistory(){
		Map<Id,LoginHistory> systemHistories = new Map<id,LoginHistory>([SELECT USerId, application FROM LoginHistory WHERE LoginTime = today ORDER BY LoginTime asc]);
		Set<Id> loginUserIds = new Set<Id>();

		for( LoginHistory item:systemHistories.values()){
			if(item.application.equalsIgnoreCase('Browser')){
				loginUserIds.add(item.UserId);
			}
		}

		List<USer> activeUsers = [SELECT id , Username , firstname, lastname, email ,LastLoginDate ,Alias, Profile.Name  FROM User WHERE isActive = true];
		Map<Id,User> nonLoginUsers = new Map<Id, User>();
		for(User item: activeUsers){
			if(!loginUserIds.contains(item.Id)){
				nonLoginUsers.put(item.Id, item);
			}
		}

		// copy all nonloginuser to snapshot object
		List<ss_NonLogin__c> listOfNonLogin = new List<ss_NonLogin__c>();
		for(User item:nonLoginUsers.values()){
			ss_NonLogin__c indivudual = new ss_NonLogin__c();
			indivudual.Alias__c = item.Alias;
			indivudual.Firstname__c = item.firstname;
			indivudual.Lastname__c = item.lastname;
			indivudual.Username__c = item.Username ;
			indivudual.LastLogin__c = item.lastlogindate;
			indivudual.Profile__c = item.Profile.Name;
			indivudual.Application__c = ''+ systemHistories.get(item.Id);
			indivudual.Name = item.Username;
			indivudual.isActive__c = true;
			listOfNonLogin.add(indivudual);
		}

		try{
			if( listOfNonLogin.size()>0){
				insert listOfNonLogin;
			}

		}catch (Exception ex){
			System.debug('DailyLoginHistory : Error when insert non login user :' + ex.getMessage());
		}

	}
	
}