src/objects/Xero_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Xero Invoices</relationshipLabel>
        <relationshipName>Xero_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <externalId>true</externalId>
        <label>InvoiceNumber</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>DRAFT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTHORISED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBMITTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOIDED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TEMPLATE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Xero Invoice</label>
    <nameField>
        <label>Xero Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/xeroInvoiceIterable.cls
global class  xeroInvoiceIterable implements Iterator<Xero_Invoice__c>{
	Integer i {get;set;}
	List<Xero_Invoice__c> xeroInvoices {get;set;}
	
	
	public xeroInvoiceIterable(Date search_date) {
		
		this.xeroInvoices = [Select Id, Reference__c, InvoiceNumber__c, Account__c, Name from Xero_Invoice__c where Date__c =: search_date and (Status__c = 'AUTHORISED' or Status__C = 'PAID') and Total__c > 200];
		this.i = 0;
		
		
		
	}

	global boolean hasNext() {
		if(this.i >= this.xeroInvoices.size()) 
        	return false; 
		else 
        	return true;	
	}

	global Xero_Invoice__c next() {
   		return this.xeroInvoices[this.i++];	
	}
}